#!/usr/bin/env python3
"""Record the final evidence-bounded taxonomy adjudications."""
import json
from pathlib import Path

QUEUE = Path(__file__).resolve().parent / "data/speech-taxonomy-adjudication-queue.json"
DECISIONS = {
    "zhong25d_interspeech": ("confirmed-current-boundary", "The abstract identifies speakers in novels for audiobook voice assignment by using LLM-generated synthetic dialogues to enlarge scarce annotated context. The evidence supports speaker-verification, bounded by implicit/anaphoric context categories, synthetic dialogue construction, and reported identification accuracy.", ["title", "abstract"], "people-variation-and-health", "identity-and-life-stage", "speaker-verification"),
    "zhou25_interspeech": ("confirmed-current-boundary", "The abstract adapts Whisper for streaming by adding a causal CTC path that emits partial transcripts and a second Whisper decoder that reranks them. The evidence supports long-context-decoding, bounded by U2, LibriSpeech/earnings-call data, hybrid tokenization, partial-output revision, and reported data-efficiency/generalization results.", ["title", "abstract"], "recognition-and-alignment", "context-and-open-vocabulary", "long-context-decoding"),
    "zhou25b_interspeech": ("confirmed-current-boundary", "The abstract compares three automatic phone/word aligners on non-native French against manual segmentations, where cross-language phonetic interference makes alignment unreliable. The evidence supports alignment, bounded by WebMAUS, MFA, SPPAS, two Chinese speakers, manual references, and the reported tool ranking.", ["title", "abstract"], "recognition-and-alignment", "boundaries-and-alignment", "alignment"),
    "zhou25e_interspeech": ("confirmed-current-boundary", "The abstract reduces SSL content-embedding dimensions for singing voice conversion to preserve content while limiting speaker-timbre leakage. The evidence supports voice-conversion, bounded by any-to-any SVC, channel selection, token/embedding trade-offs, SSL/ContentVec variants, and the reported generalization.", ["title", "abstract"], "voice-generation-and-control", "identity-and-conversion", "voice-conversion"),
    "zhou25f_interspeech": ("confirmed-current-boundary", "The abstract uses emotion-inducing tasks and speech/text sentiment cues to model depression-related differences in emotional expression, including flattened prosody and negative-information bias. The evidence supports paralinguistic-state, bounded by emoGAT, depressed/control participants, task conditions, graph attention, and reported accuracy/variance changes.", ["title", "abstract"], "meaning-and-interaction", "prosody-and-paralinguistics", "paralinguistic-state"),
    "zhou25g_interspeech": ("confirmed-current-boundary", "The abstract predicts a listener's intelligibility on new audio from a few prior audio/score pairs instead of requiring an audiogram. The evidence supports accessibility-fit, bounded by SSIPNet, Clarity data, support-pair conditioning, unseen-audio prediction, audiogram comparison, and the small-data setting.", ["title", "abstract"], "people-variation-and-health", "human-centered-accessibility", "accessibility-fit"),
    "zhou25h_interspeech": ("confirmed-current-boundary", "The abstract detects what phoneme was actually produced, not only what was expected, using similarity modeling and a simulated accented-error corpus. The evidence supports pronunciation-variation, bounded by VCTK-accent, multi-task training, phoneme-level errors, two new metrics, and the pronunciation-assessment scope.", ["title", "abstract"], "recognition-and-alignment", "pronunciation-and-variation", "pronunciation-variation"),
    "zhou25i_interspeech": ("confirmed-current-boundary", "The abstract recognizes known and unknown emotion categories across corpora by aligning distributions and regularizing confidence so unknown samples are rejected rather than forced into known classes. The evidence supports paralinguistic-state, bounded by spatiotemporal features, MMD/inverse entropy, open-set recognition, four datasets, and baseline comparisons.", ["title", "abstract"], "meaning-and-interaction", "prosody-and-paralinguistics", "paralinguistic-state"),
    "zhu25_interspeech": ("confirmed-current-boundary", "The abstract controls personal sound zones under uncertain acoustic transfer functions, balancing acoustic contrast against distortion with a robust ACC-PM optimization. The evidence supports spatial-filtering, bounded by temperature/head-movement perturbations, norm bounds, second-order-cone reformulation, simulation, and acoustic-contrast improvement.", ["title", "abstract"], "listening-and-separation", "spatial-listening", "spatial-filtering"),
    "zhu25b_interspeech": ("confirmed-current-boundary", "The abstract generates confusable keyword examples with language models and TTS, then evaluates whether a custom KWS system separates near-miss words. The evidence supports open-vocabulary-recognition, bounded by enrollment/input embeddings, confusable groups, c-AUC, Speech Commands, zero-labor synthesis, and reported gains.", ["title", "abstract"], "recognition-and-alignment", "context-and-open-vocabulary", "open-vocabulary-recognition"),
    "zhu25c_interspeech": ("confirmed-current-boundary", "The abstract detects which speaker a listener attends to from EEG by combining frequency-derived spatial patterns with long-range spatiotemporal structure. The evidence supports non-airborne-sensing, bounded by SSF-DST, cocktail-party AAD, EEG spectro-spatial features, parameter reduction, and classification results.", ["title", "abstract"], "sound-and-production", "room-channel-and-sensing", "non-airborne-sensing"),
    "zhuang25_interspeech": ("confirmed-current-boundary", "The abstract adds a monotonic-alignment objective while fine-tuning Whisper without changing its network, improving recognition and translation and validating the approach on Cantonese-to-Mandarin data. The evidence supports alignment, bounded by Whisper fine-tuning, monotonic training, MDCCST, ASR/translation tasks, and reported improvements.", ["title", "abstract"], "recognition-and-alignment", "boundaries-and-alignment", "alignment"),
    "zhuo25_interspeech": ("confirmed-current-boundary", "The abstract obtains Vietnamese ASR from 70,000 hours of unlabeled speech and only 50 hours of labeled data through iterative ASR-biased self-supervision. The evidence supports few-shot-adaptation, bounded by VietASR, low-resource Vietnamese, pretraining/fine-tuning split, lightweight deployment, and real-world comparisons.", ["title", "abstract"], "languages-accents-and-resources", "low-resource-learning", "few-shot-adaptation"),
    "znotins25_interspeech": ("confirmed-current-boundary", "The abstract provides a statically deployable open toolkit for Latvian and Latgalian transcription with fine-tuned and multilingual Whisper models, usable locally or in cloud infrastructure. The evidence supports speech-data-collection, bounded by LATE, open-source/precompiled distribution, language models, transcription formatting, and deployment scope.", ["title", "abstract"], "languages-accents-and-resources", "data-creation", "speech-data-collection"),
    "zuo25_interspeech": ("confirmed-current-boundary", "The paper treats depression severity as ordered rather than binary by learning thresholds for progressively different levels of depression from speech. The evidence supports clinical-speech-marker, bounded by ordinal loss, latent severity space, threshold tasks, speech-based classification, and comparison with existing methods.", ["title", "abstract", "full_paper"], "people-variation-and-health", "clinical-markers", "clinical-speech-marker"),
    "zuo25b_interspeech": ("confirmed-current-boundary", "The abstract creates a short-utterance text-dependent speaker-verification corpus from text-independent data using ASR timestamps and common-phrase selection, then measures phrase-length effects. The evidence supports speaker-verification, bounded by Sub3Vox/VoxCeleb1, 3.7 million utterances, 1,250 speakers, enrollment/test phrase matching, EER, and sub-three-second duration.", ["title", "abstract"], "people-variation-and-health", "identity-and-life-stage", "speaker-verification"),
    "zwilling25_interspeech": ("confirmed-current-boundary", "The abstract records collection partnerships, distributed infrastructure, participant-facing procedures, prompts, and annotations for a large open database of disordered speech. The evidence supports speech-data-collection, bounded by the Speech Accessibility Project, dysarthria/apraxia/dysphonia/atypical speech, curation practices, reproducibility, and ASR testbed use.", ["title", "abstract"], "languages-accents-and-resources", "data-creation", "speech-data-collection"),
}


def main():
    payload = json.loads(QUEUE.read_text())
    rows = {r["paper_id"]: r for r in payload["rows"]}
    for pid, (decision, note, sections, theme, subtheme, concept) in DECISIONS.items():
        row = rows[pid]
        if row["taxonomy_review_state"] == "taxonomy-adjudicated":
            raise SystemExit(f"already adjudicated: {pid}")
        row.update({"taxonomy_review_state": "taxonomy-adjudicated", "final_decision": decision, "reviewer_note": note, "reviewed_sections": sections, "final_theme_id": theme, "final_subtheme_id": subtheme, "final_concept_id": concept})
    adjudicated = sum(r["taxonomy_review_state"] == "taxonomy-adjudicated" for r in rows.values())
    payload["adjudicated_count"] = adjudicated
    payload["open_count"] = len(rows) - adjudicated
    decisions = sorted({r.get("final_decision") for r in rows.values() if r["taxonomy_review_state"] == "taxonomy-adjudicated"})
    payload["decision_counts"] = {d: sum(r.get("final_decision") == d for r in rows.values() if r["taxonomy_review_state"] == "taxonomy-adjudicated") for d in decisions}
    QUEUE.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps({"batch": len(DECISIONS), "adjudicated": adjudicated, "open": payload["open_count"]}))


if __name__ == "__main__":
    main()
