"""Write no-jargon notes for D3 batch 045."""
import json
from pathlib import Path
H=Path(__file__).resolve().parent;D,R=H/"data",H/"reports"
C={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-fortyfifth-d3-papers.json").read_text())["papers"]}
P={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-papers.json").read_text())["papers"]}
N={
"alexos25_interspeech":("A speech-enabled language model can be tricked into producing a harmful answer even when its text safety training appears strong.","Speech adds an attack surface: an adversarial spoken query must survive speech recognition and still steer the language model, while defenses need scarce harmful speech examples.","Apply ordinary text safety tuning and assume the speech front end does not change the jailbreak problem.","Train with synthesized harmful and benign speech queries and test against strong white-box attacks across two model sizes and data configurations.","The paper develops adversarial-training methods tailored to speech-enabled language models.","Safety is a path property: the audio, recognition, and language-model stages jointly determine whether a harmful request is blocked, so safety examples must cover the spoken route.","The paper reports relative safety gains of 45%–300% in its tested settings using four hours of harmful speech with 150 hours of benign speech.","The two models, synthesized data, attack family, safety measure, and training recipe bound the result; robustness to unseen speakers, attacks, languages, and real-world misuse remains open."),
"battula25_interspeech":("A person’s confidence is useful to assess in an interview, but the relevant physiological signal is normally hard to collect without a sensor.","The proposed chain estimates breathing from speech, extracts heart-rate variation with ICA, and maps that estimate to confidence; each step can add error or reflect demographic and situational differences.","Treat confidence as a direct acoustic class or require a wearable heart-rate sensor for every interaction.","Infer heart rate from speech-derived breathing patterns, then examine whether the inferred heart rate separates confident and non-confident speakers.","The paper presents a three-stage speech-to-breathing-to-heart-rate approach for confidence analysis.","The key conceptual move is indirect sensing: speech is used as a window onto a bodily rhythm, but the inferred physiology is not the same thing as confidence itself.","The paper reports that confident speakers had an average heart rate about 10 beats per minute lower in its tested data.","The datasets, Indian demographic, 41-speaker collection, clinical and wearable references, confidence labels, and unreported general accuracy bound the claim; correlation is not a validated psychological diagnosis."),
"bhattacharya25b_interspeech":("An audio language model may answer a temporal question correctly for the wrong reasons or change its answer when the same content is phrased equivalently.","Accuracy alone cannot show whether a model tracks time relations or knows when its answer is unstable; speech duration and temporal ordering create failures not visible in ordinary classification tests.","Report one accuracy number on a fixed question set and treat it as reasoning competence and confidence.","Build the TREA temporal-reasoning dataset, benchmark audio language models against people, and measure uncertainty through invariance to semantically identical perturbations.","The paper introduces Temporal Reasoning Evaluation of Audio and an uncertainty metric for large audio language models.","Evaluation must separate getting the answer right from behaving consistently under meaning-preserving changes; these are different properties and can move in opposite directions.","The paper reports that tested open-source models lagged human performance and that accuracy and perturbation-based uncertainty were not necessarily correlated.","The dataset, perturbations, models, human comparison, and temporal tasks bound conclusions; invariance is one operational uncertainty test, not a complete account of confidence."),
"bressensdorf25_interspeech":("When speakers of two dialects meet, a sound change can spread unevenly: a conservative dialect may move toward an innovative one, changing how grammatical information is pronounced.","The change is both social and physical: speakers remember variable signals, categories can emerge gradually, and inflectional cues can move between suffixes and stem vowels.","Treat dialect contact as a fixed label difference or assume both communities shift symmetrically toward an average.","Initialize an interactive phonetic agent model with real speech from two Southern Italian varieties and simulate metaphony, then compare diphthongization and categorical contrasts.","The paper tests an agent-based model of dialect contact and morpho-phonological sound change.","A dialect is not a static inventory: production is repeatedly updated through perceptual memory and interaction, allowing social contact to reshape acoustic categories over time.","The reported results provide support for an asymmetric shift toward the innovative dialect and are consistent with feedback models of sound change.","The two dialects, 54 speakers collapsed to 13 agents, selected words, F1 trajectory representation, and model assumptions limit generalization to other communities or changes."),
"burkhardt25_interspeech":("An emotion database becomes more useful when it preserves ambiguous judgments and records how natural the acted speech sounds, rather than discarding every item without strong agreement.","Emotion labels are perceptions with disagreement, and glottal behavior may contain information that ordinary audio features miss; a clean majority label can hide meaningful uncertainty.","Keep only samples with high rater agreement and treat one categorical emotion label as ground truth.","Extend Berlin EmoDB with previously omitted ambiguous samples, glottograms, and perceived-naturalness labels, then test their value in preliminary classifiers.","The paper extends the Berlin Database of Emotional Speech with ambiguity, glottograms, and naturalness information.","Dataset construction is part of the scientific model: disagreement and phonation measurements expose how an emotion label is produced and where it is uncertain.","The paper reports an 8.1% UAR improvement for an SVM when glottogram information is incorporated in its preliminary study.","The acted German corpus, old recording conditions, rater thresholds, classifier, and preliminary evaluation bound the result; improved classification does not establish better emotion understanding."),
"chae25_interspeech":("Lyrics must say something coherent while fitting a song’s verse, chorus, and line-level syllable pattern; ordinary line-by-line text generation often breaks the musical form.","Syllables constrain several nested units at once, so satisfying a line can damage a phrase or chorus, and semantic coherence must survive the edits.","Generate each line independently and count syllables only after generation.","Generate complete lyrics conditioned on text and song form while controlling syllable counts at word, phrase, line, and paragraph levels.","The paper proposes song-form-aware full-song lyrics generation with multi-level syllable control.","The output is a structured object: constraints at smaller units must compose into a song-level form, rather than being repaired after a generic text model has already committed to lines.","The paper reports controlled lyrics-generation experiments and makes generated samples available for inspection.","Text prompts, song forms, syllable-count rules, dataset construction, and evaluation criteria bound the claim; syllable fit is not the same as singability, musicality, or authorship."),
"chae25b_interspeech":("A speech codec should spend bits on speech detail that matters to listeners, not on background noise, especially when the transmission budget changes from moment to moment.","Noise can consume code capacity while speech components vary in importance; removing noise and preserving speech quality are coupled rate-allocation decisions.","Use one constant bitrate for every frame or denoise after compression without changing the allocation.","Use variable-bitrate residual vector quantization to allocate more representation to important speech frames and combine it with a feature denoiser.","The paper proposes Variable Bitrate RVQ for noise-robust speech coding.","Compression is selective reconstruction: the codec decides which parts of a noisy frame deserve precision, so rate, distortion, denoising, and perceptual quality must be evaluated together.","The paper reports improved rate-distortion trade-offs and perceptual quality over constant-bitrate baselines in noisy conditions.","Noise conditions, bitrates, codec architecture, datasets, perceptual measures, and model sizes bound the result; a cleaner perceptual signal is not necessarily a faithful waveform."),
"chan25_interspeech":("A multilingual speaker must produce a stop contrast in several languages even when those languages use different cues such as closure voicing or aspiration.","The same person can keep language-specific categories while still showing dominance effects, and different acoustic cues can carry different weight in each language.","Assume one speaker-wide voicing rule or average all languages into one acoustic category.","Measure nine acoustic correlates in Malay, English, and Mandarin speech from early multilingual Malaysians and use random forests to compare cue weighting.","The paper studies relative cue weighting in multilingual stop-voicing production.","Multilingual pronunciation is coordinated but not collapsed: language-specific cue bundles coexist with influence from which language is dominant for the speaker.","The paper reports language-specific production for all early multilinguals, dominance-driven variation, and a salient role for closure voicing in Malaysian English.","The Malaysian speakers, three languages, stop inventory, nine correlates, and random-forest analysis bound generalization to other multilingual populations or contrasts."),
}
keys=["bp","wh","naive","ap","mech","math","ww","limits"];notes=[];claims=[];md=["# INTERSPEECH 2025 forty-fifth-pass full-paper notes","","Eight official-PDF readings deepen speech-model security, physiological inference, temporal evaluation, dialect change, emotion-data design, lyric structure, noisy coding, and multilingual cue weighting.",""]
for i,(pid,c) in enumerate(C.items(),1):
    d=dict(zip(keys,N[pid]));d.update({"paper_id":pid,"title":P[pid]["title"],"subtheme":({"alexos25_interspeech":"privacy-security-and-accountability","battula25_interspeech":"clinical-and-assistive-speech","bhattacharya25b_interspeech":"metrics-and-targets","bressensdorf25_interspeech":"accent-and-cultural-boundaries","burkhardt25_interspeech":"low-resource-and-data-creation","chae25_interspeech":"text-to-speech-and-content","chae25b_interspeech":"echo-and-reconstruction","chan25_interspeech":"multilingual-and-crosslingual"}[pid])});notes.append(d)
    md += [f"## {i}. {d['subtheme']}","",f"**Paper:** [{d['title']}]({P[pid]['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]+[f"- **{label}:** {d[key]}" for label,key in zip(["Ordinary problem","Why hard","Naive attempt","Central move","Mechanism","Conceptual structure","What paper reports","Limits"],keys)]+[""]
    claims.append({"claim_id":f"IS25-D3C45-{i:02d}","paper_id":pid,"subtheme":d["subtheme"],"claim":d["ww"],"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":d["limits"]})
(D/"interspeech-2025-fortyfifth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(D/"interspeech-2025-fortyfifth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
R.mkdir(exist_ok=True);(R/"INTERSPEECH_2025_FORTYFIFTH_D3_NOTES.md").write_text("\n".join(md)+"\n");print(json.dumps({"notes":len(notes),"claims":len(claims)}))
