"""Write first-principles notes for D3 batch 048."""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPORTS = HERE / "reports"
captured = {row["paper_id"]: row for row in json.loads((DATA / "interspeech-2025-fortyeighth-d3-papers.json").read_text())["papers"]}
papers = {row["paper_id"]: row for row in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

N = {
"le25b_interspeech": ("A transmitted or recorded speech signal can contain clipped samples, missing packets, noise, reverberation, bandwidth loss, and codec artifacts at once.", "Each distortion removes or corrupts different evidence, and a single undifferentiated enhancer can repair one defect while amplifying another.", "Apply one generic enhancement network to the waveform and hope it learns every corruption jointly.", "Cascade specialized modules in a deliberate order: declipping, separation, packet-loss compensation, and spectral inpainting, with a detector deciding when the first and third modules are needed.", "Model the degraded signal as a composition of distortion operators; use Demucs for declipping, BSRoformer for separation, BS-PLCNet in a PQMF subband domain for packet loss, and a time-frequency recurrent inpainting network for spectral artifacts.", "The key object is a masked signal and a composition of operators. Separating domains and ordering repairs reduces the optimization problem from one tangled inverse map to several bounded inverse problems.", "The system reports URGENT challenge results competitive with the compared systems; adding inpainting and self-distillation improves several quality measures, while downstream accuracy and objective metrics do not all move together.", "Challenge datasets, distortion order, detector errors, resampling to 48 kHz for some modules, metric choice, and author-reported rankings bound the claim; plausible filling is not recovery of the original samples."),
"quinterovillalobos25_interspeech": ("In an unstable online call, a speaker may continue talking while the listener never receives part of the utterance.", "The system must identify what was lost without treating an incomplete remote transcript as complete, then request a short useful repair rather than forcing a full repetition.", "Assume the call is reliable, or ask the speaker to repeat everything after any connection failure.", "Compare local and remote ASR streams, identify unreceived content after reconnection, extract keywords from the missing segment, and prompt the speaker to repeat only the relevant information.", "The system is an interaction loop: dual transcripts provide two views of the communication event, discrepancy detection estimates the missing interval, and keyword extraction compresses the repair request into actionable cues.", "This is not waveform packet-loss concealment. It preserves conversational meaning through human-in-the-loop selective repetition when acoustic reconstruction is unsafe or unavailable.", "The paper demonstrates a WebRTC/WebSocket prototype using Whisper and NLTK keyword extraction in a simulated brief disconnection; it is a show-and-tell feasibility demonstration rather than a controlled recovery benchmark.", "Two-person demonstration conditions, simulated network failure, ASR errors, keyword quality, privacy/latency trade-offs, and absence of a listening study bound the result."),
"lee25d_interspeech": ("A silent-speech interface needs to infer intended speech from muscle activity when an acoustic waveform is absent or inaccessible.", "EMG channels reflect overlapping facial and articulatory actions, sensors are sparse, and synchronized EMG plus true articulatory measurements are scarce.", "Map EMG directly to a waveform or text while ignoring the physical intermediate movements.", "Use an EMG encoder with convolutional and Transformer layers to predict EMA positions, pitch, loudness, and auxiliary phonemes, making articulatory structure an intermediate target.", "The model minimizes L2 losses for EMA, pitch, and loudness and cross-entropy for phonemes. The predicted EMA coordinates represent tongue, lip, and jaw movement rather than an opaque speech label.", "Articulatory features provide a structured bottleneck: the system keeps coordinated movement and voice-source information separate, then can use those predictions for later speech reconstruction.", "On 7,565 utterances from one male American English speaker, the paper reports strong EMA and loudness prediction and evaluates held-out utterances using correlations against acoustic-inversion targets.", "Targets are pseudo-ground truth from acoustic-to-articulatory inversion, the speaker is not diverse, experiments focus on vocalized open-vocabulary speech, and feature prediction is not the same as intelligible silent-speech synthesis."),
"koudounas25c_interspeech": ("A speaker may ask a spoken-language-understanding service to forget their training examples without destroying the service for everyone else.", "Removing files is not enough because model parameters retain influence; forgetting must be measured against efficacy, retained utility, and computation across languages and architectures.", "Delete the records and assume the trained model has forgotten, or retrain from scratch for every request.", "Define forget and retain speaker sets, compare eight machine-unlearning methods against a gold model trained without the forget set, and evaluate both what is forgotten and what remains useful.", "The benchmark treats unlearning as producing a model close to the retain-only gold model. Metrics include test and forget-set F1, membership-inference attack behavior, generalization, and speedup, making the trade-off explicit.", "Consent becomes a measurable model-state constraint rather than a checkbox: a deletion request is successful only if identity-linked influence is reduced without unacceptable loss of spoken intent recognition.", "The paper benchmarks four datasets in four languages, two speech encoders per dataset, and eight unlearning methods; it shows that no single method dominates all efficacy, utility, and efficiency axes.", "Benchmark identities and intent tasks are proxies for real consent, attack strength and gold-model assumptions matter, and unlearning guarantees do not establish that every downstream copy or generated artifact is withdrawn."),
"phukan25g_interspeech": ("A speech emotion or depression model may need to remove a person's contribution from training without rebuilding a large model from zero.", "Paralinguistic models encode sensitive attributes, and fast forgetting can damage emotion or depression prediction utility; the best feature representation may change the unlearning trade-off.", "Fine-tune the full model on retained data or average models without structuring which data must be forgotten.", "Extend SISA with weight averaging: shard the training data, retrain only affected slices, and average the surviving submodels; compare pretrained speech representations and downstream networks.", "SISA++ turns a global deletion into local retraining plus parameter aggregation. The evaluation separates forgetting performance from retained task performance and measures computational savings.", "The mechanism uses data partitioning as a control boundary: the model remembers where influence entered, so a request can remove a bounded subset of training history.", "Experiments use CREMA-D speech emotion recognition and E-DAIC depression detection; the paper reports TRILLsson features with a Transformer as a robust recipe under its tested settings.", "The result depends on shard design, feature extractor, downstream task, attack/evaluation protocol, and access to the original training pipeline; fast unlearning is not proof of legal or social consent compliance."),
"li25n_interspeech": ("Dysarthric speech is scarce and variable, so recognizers need more training examples without pretending that synthetic speech is equivalent to a person's real motor patterns.", "Synthetic speech can scale text and speaker combinations but may miss irregular timing, articulation, spectral detail, and clinically meaningful variation.", "Replace authentic dysarthric recordings with large quantities of generated speech because more data should always improve recognition.", "Train speaker-specific TTS systems, generate synthetic dysarthric utterances at several scales, combine them with authentic data for dysarthric speech recognition, and compare feature distributions and recognition results.", "The study varies whether training uses authentic Set A/Set B data, synthetic data derived from Set A, or much larger synthetic additions. It measures ASR performance and compares acoustic feature distributions between authentic and synthetic samples.", "Synthetic data is a distributional proposal, not a label-preserving copy: the relevant question is whether generated speech spans the motor and acoustic variation needed by the recognizer.", "Across the tested Chinese dysarthric speech setup, synthetic speech alone does not replace authentic data and large synthetic additions yield only marginal gains over authentic training.", "The language, seven-speaker usable subset, TTS model, data scale, ASR architecture, and speaker-independent split bound generalization; a synthetic-data result is not clinical validation."),
"aboeitta25_interspeech": ("Automatic speech recognition must transcribe dysarthric speech whose phonetic timing and articulation violate assumptions learned from typical speech.", "CTC can misalign distorted phonemes, ordinary end-to-end models can produce grammatical but acoustically unsupported text, and severity and speaker shifts change the error pattern.", "Use a standard ASR model and treat WER as the complete measure of success.", "Benchmark CTC, Whisper, and LLM-enhanced decoders, including bridge networks and a Q-Former that connects Whisper acoustic features to Vicuna for context-aware decoding.", "The comparison keeps TORGO and UASpeech speaker-independent splits and evaluates WER by dysarthria severity. The decoder choice changes how much linguistic context can repair uncertain acoustic evidence.", "The paper exposes an evidence trade-off: a stronger language prior can improve semantic reconstruction, but it can also make a plausible transcript less directly grounded in the signal.", "Whisper improves over CTC baselines, and Whisper-Vicuna reports the lowest WER in the tested TORGO and UASpeech comparisons; all results remain author-reported.", "Dataset splits, severity labels, model scale, decoding prompts, and WER limit the claim; lower WER does not prove faithful preservation of disfluencies or speaker intent."),
"m25_interspeech": ("Voice synthesis for dysarthric speakers should preserve intelligibility, identity, and prosodic character without treating disability severity as noise to erase.", "A zero-shot synthesizer may copy speaker identity while changing pathological speech patterns unevenly across severity groups, creating a fairness problem hidden by average quality scores.", "Report one average similarity or intelligibility score and assume it applies equally to healthy and dysarthric speakers.", "Generate speech from TORGO prompts with F5-TTS, measure intelligibility, speaker similarity, and prosody similarity, then compare severity groups using parity difference and disparate impact.", "The study defines metrics over group means: WER/CER for intelligibility, SIM-o cosine similarity for speaker traits, and AutoPCP for prosody. Fairness is assessed by deviations from healthy-speaker reference behavior.", "The mechanism is an evaluation reframing: voice cloning is not one scalar quality target when a model may preserve identity but unevenly alter disability-linked prosody or intelligibility.", "The paper reports severity-dependent differences in the objective measures and uses those differences to characterize intrinsic bias in F5-TTS cloning.", "TORGO, reference-prompt choice, automatic metrics, severity grouping, and zero-shot model behavior bound the result; parity in proxies does not establish respectful control, consent, or listener benefit."),
}

keys = ["bp", "wh", "naive", "ap", "mech", "math", "ww", "limits"]
subs = {
    "le25b_interspeech": "packet-loss-concealment", "quinterovillalobos25_interspeech": "packet-loss-concealment",
    "lee25d_interspeech": "articulatory-coordination", "koudounas25c_interspeech": "user-control-and-consent",
    "phukan25g_interspeech": "user-control-and-consent", "li25n_interspeech": "dysarthria-and-atypical-speech",
    "aboeitta25_interspeech": "dysarthria-and-atypical-speech", "m25_interspeech": "accessibility-fit",
}
subtheme_to_theme = {
    "packet-loss-concealment": ("listening-and-separation", "echo-and-reconstruction"),
    "articulatory-coordination": ("sound-and-production", "source-filter-production"),
    "user-control-and-consent": ("people-variation-and-health", "human-centered-evaluation"),
    "dysarthria-and-atypical-speech": ("people-variation-and-health", "clinical-and-assistive-speech"),
    "accessibility-fit": ("people-variation-and-health", "human-centered-evaluation"),
}
notes = []
claims = []
markdown = ["# INTERSPEECH 2025 forty-eighth-pass full-paper notes", "", "Eight official-PDF readings deepen packet-loss repair, articulatory sensing, speech-model unlearning, paralinguistic privacy, synthetic dysarthric data, dysarthric ASR, and fairness in dysarthric voice cloning.", ""]
for index, (paper_id, fields) in enumerate(N.items(), 1):
    paper = papers[paper_id]
    note = dict(zip(keys, fields))
    theme_id, subtheme_id = subtheme_to_theme[subs[paper_id]]
    note.update({"paper_id": paper_id, "title": paper["title"], "theme_id": theme_id, "subtheme_id": subtheme_id, "concept_id": subs[paper_id], "dots": {"theme_id": theme_id, "subtheme_id": subtheme_id, "concept_id": subs[paper_id], "sibling_family": "batch-048"}, "eval": fields[5], "source": {"kind": "official-isca-archive-paper-page-plus-captured-pdf-text", "pdf_sha256": captured[paper_id]["pdf_sha256"], "full_text_sha256": captured[paper_id]["full_text_sha256"], "pdf_path": f"data/interspeech-2025-pdfs/{paper_id}.pdf", "text_path": captured[paper_id]["full_text_path"]}, "depth": "D3", "evidence_boundary": "D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."})
    notes.append(note)
    claims.append({"claim_id": f"IS25-D3C48-{index:02d}", "paper_id": paper_id, "subtheme": subtheme_id, "claim": note["ww"], "evidence_depth": "D3", "pdf_sha256": captured[paper_id]["pdf_sha256"], "full_text_sha256": captured[paper_id]["full_text_sha256"], "support_status": "paper-reported-not-independently-verified", "independent_support_status": "not-established", "limitations": note["limits"]})
    markdown += [f"## {index}. {subtheme_id}", "", f"**Paper:** [{paper['title']}]({paper['paper_url']})", f"**Evidence:** D3; PDF SHA-256 `{captured[paper_id]['pdf_sha256']}`; full text captured.", ""]
    markdown += [f"- **{label}:** {note[key]}" for label, key in zip(["Ordinary problem", "Why hard", "Naive attempt", "Central move", "Mechanism", "Mathematical/conceptual structure", "What paper reports", "Limits"], keys)] + [""]

(DATA / "interspeech-2025-fortyeighth-d3-notes.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "evidence_depth": "D3", "notes": notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-fortyeighth-claim-ledger.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "claim_count": len(claims), "claims": claims}, indent=2, ensure_ascii=False) + "\n")
REPORTS.mkdir(exist_ok=True)
(REPORTS / "INTERSPEECH_2025_FORTYEIGHTH_D3_NOTES.md").write_text("\n".join(markdown) + "\n")
print(json.dumps({"notes": len(notes), "claims": len(claims)}))
