"""Write no-jargon notes for D3 batch 025."""
import json
from pathlib import Path

H = Path(__file__).resolve().parent; D, R = H / "data", H / "reports"
C = {x["paper_id"]: x for x in json.loads((D / "interspeech-2025-twentyfifth-d3-papers.json").read_text())["papers"]}
P = {x["paper_id"]: x for x in json.loads((D / "interspeech-2025-papers.json").read_text())["papers"]}
N = {
"istaiteh25_interspeech": ("A translation or spoken answer can sound similar to a source while quietly changing or contradicting its meaning.", "Similarity rewards shared words or embeddings but does not distinguish agreement, contradiction, and unrelated content.", "Score overlap and call a high similarity score faithful.", "Classify the logical relation between speech and text or between two speech segments as entailment, contradiction, or neutral across languages and modalities.", "Speech-text, text-speech, and speech-speech pairs are added to a multilingual inference framework and compared with similarity-based BLASER evaluation.", "The target is a three-way relation, not a continuous closeness score; F1 measures whether the evaluator detects meaning-preserving and meaning-changing pairs.", "The paper reports F1 gains of 0.19 for speech-speech and 0.13 for speech-text over BLASER in distinguishing entailment from non-entailment.", "Languages, pair construction, translations, labels, and evaluation sets bound the result; logical classification does not guarantee complete translation assessment or human usefulness."),
"kano25_interspeech": ("A summary of a long spoken presentation must retain the important points without forcing a model to search the whole sequence and compose everything at once.", "Long speech contains many irrelevant stretches, and an abstractive system can lose key content while generating fluent text.", "Generate the summary directly and assume the generator will discover the important spans.", "First identify useful excerpts from the speech, then use that auxiliary selection signal to guide abstractive summary generation.", "An extractive-abstractive model is trained on a web-presentation corpus, with an extractive summary predicted from raw speech alongside the final text summary.", "Selection narrows the content problem before wording is generated; METEOR compares the final summary with reference summaries while the extractive task supplies structure.", "The method gives consistent gains and up to 1.4 METEOR points over a strong abstractive baseline.", "The corpus, reference summaries, metric, summary length, and presentation style bound the result; lexical overlap does not prove that all important facts were preserved."),
"kunze25_interspeech": ("Wearable child recordings produce enormous naturalistic audio, but researchers need reliable labels such as who or what kind of voice appears before studying development.", "In-the-wild recordings are noisy, imbalanced, difficult to share, and unlike curated speech data, so a better model may not solve the real bottleneck.", "Keep changing the architecture and features until the classifier improves, while ignoring the data collection and permission process.", "Treat data relevance, quantity, label quality, and permission to share as first-class parts of the recognition problem.", "Three years of voice-type classification experiments on child-worn recordings compare representation features, architectures, and parameter search against data changes.", "Performance is limited by the relationship between labels and the recording environment; classification scores reveal whether engineering changes matter relative to data coverage.", "Model and tuning improvements produce marginal gains, while more relevant and larger shareable data produce more progress.", "The child-wearable setting, label scheme, permissions, and task definition bound the result; conclusions do not automatically transfer to adult or laboratory speech."),
"li25aa_interspeech": ("A speech classifier can be made to behave normally on ordinary inputs while an attacker causes a chosen label when a hidden manipulation is present.", "A visible poisoned sound is easy to notice, but an attack hidden inside a learned representation can preserve apparent audio quality.", "Assume clean-sounding audio means the classifier is safe, or search only for obvious waveform triggers.", "Rearrange latent representations inside a pretrained speech generator so the attack changes the target label while remaining hard to hear.", "LRBA uses the normalizing flow in VITS to create rearranged utterances and poisons a small fraction of training data for speech classification.", "The attack separates perceptual quality from decision integrity; attack success rate, poisoning rate, and mean-opinion score test the tradeoff.", "The paper reports high attack success at a low poisoning rate while retaining high perceived quality and outperforming prior attacks in stealthiness.", "The VITS model, classifier, target labels, poisoning setup, and listener measure bound the threat; this is an attack demonstration, not evidence that every speech system is vulnerable."),
"li25j_interspeech": ("A person who cannot reliably speak may still communicate through brain signals, but imagined speech produces weaker and less direct evidence than spoken speech.", "EEG is noisy and varies across imagined, intended, and spoken modes; a model trained on one mode may discard useful shared structure or use too many channels.", "Train separate decoders for each mode using every available EEG channel.", "Train one model across modes with dynamic masking, then use its learned channel relevance to make a smaller single-mode decoder.", "A joint EEG decoder covers imagined, intended, and spoken speech and is evaluated on four-vowel classification, including a channel-selection transfer step.", "Shared and mode-specific evidence are balanced by masking; vowel accuracy tests decoding while selected-channel performance tests whether the joint model identifies useful measurements.", "Imagined-speech accuracy rises to 34.95% from a 29.18% baseline, and channel-selected single-mode models outperform models using all channels.", "The four-vowel task, participants, EEG hardware, mode definitions, and accuracy metric bound the result; it does not demonstrate unrestricted communication or clinical readiness."),
"lin25e_interspeech": ("Emotion can be expressed simultaneously by words, voice melody, and a face, and a listener must decide what to do when those channels disagree.", "Older and younger listeners may rely on channels differently, so a single average emotion score hides both channel priorities and conflict resolution.", "Combine all channels as if they were equally reliable or measure each channel in isolation.", "Use a cross-channel conflict task that directs attention to one channel while manipulating congruence in the others, then compare age groups and channel effects.", "Younger and older adults perform an audiovisual face-prosody-semantics Stroop task with happy and sad cues under congruent and incongruent conditions.", "Reaction or accuracy differences reveal selective attention and integration costs; congruence tests whether one channel can override another.", "Older adults show reduced emotion integration, especially for prosody and other nonverbal cues, with larger age differences under incongruence.", "The task, emotions, participant groups, language, and interpretation of Stroop costs bound the result; laboratory conflict does not directly predict everyday communication."),
"novitasari25b_interspeech": ("Written output from speech must include words, capitalization, and punctuation, but asking one recognizer to learn all three at once can damage the underlying word recognition.", "Formatting decisions occur at different levels from phonetic recognition, and voice activity boundaries provide timing information that text-only decoding lacks.", "Train directly on formatted transcripts and accept errors in both formatting and the words themselves.", "Distill word-recognition knowledge from an unformatted teacher into a formatted student and add voice-activity cues to support boundary and formatting decisions.", "A mixed-case end-to-end ASR student receives knowledge from a unicase teacher and voice-activity information; case-sensitive and insensitive outputs are measured.", "The system separates acoustic-to-word evidence from formatting supervision; word error and case/punctuation errors expose whether formatting harms recognition.", "The method reports up to a 9.2% relative error reduction at comparable decoding cost.", "Training data, formatting conventions, teacher quality, decoding budget, and reported error definitions bound the result; punctuation accuracy is not the same as transcript understanding."),
"zhang25b_interspeech": ("Listeners must distinguish lexical tones whose pitch contours overlap and whose categories may not behave like cleanly separated bins.", "Pitch height, movement, duration, and phonation interact, and a continuum between tones may be heard gradually rather than categorically.", "Assign each tone one fixed pitch contour and assume every listener makes an all-or-none category decision.", "Measure perceptual cues for all four Changde Mandarin tones and test whether tone continua meet behavioral standards for categorical perception.", "Production and perception data examine T1–T4 contours and T2-T3 and T2-T4 continua using tone identification and cue analyses.", "The key object is the listener's response curve across an acoustic continuum; categorical perception requires a sharp boundary and reduced cross-category sensitivity, not just different labels.", "T1 is high-level, T2 low-rising, T3 falling rather than level, and the T2-T3 and T2-T4 continua do not meet typical categorical-perception standards.", "The Changde variety, speakers, stimuli, cue manipulation, and category criteria bound the result; it should not be generalized to Standard Mandarin or all tonal perception."),
}
keys=["bp","wh","naive","ap","mech","math","ww","limits"]; notes=[]; claims=[]
md=["# INTERSPEECH 2025 twenty-fifth-pass full-paper notes","","Eight official-PDF readings deepen semantic evaluation, long-context summarization, data bottlenecks, security, assistive communication, multisensory meaning, formatting, and tonal perception. Results are author-reported and not independently reproduced.",""]
for i,(pid,values) in enumerate(N.items(),1):
 d=dict(zip(keys,values)); c=C[pid]; d.update({"paper_id":pid,"title":P[pid]["title"],"subtheme":c["subtheme_label"]}); notes.append(d)
 md += [f"## {i}. {d['subtheme']}","",f"**Paper:** [{d['title']}]({P[pid]['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]
 md += [f"- **{label}:** {d[key]}" for label,key in zip(["Ordinary problem","Why hard","Naive attempt","Central move","Mechanism","Conceptual structure","What paper reports","Limits"],keys)]+[""]
 claims.append({"claim_id":f"IS25-D3C25-{i:02d}","paper_id":pid,"subtheme":d["subtheme"],"claim":d["ww"],"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":d["limits"]})
(D/"interspeech-2025-twentyfifth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(D/"interspeech-2025-twentyfifth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
R.mkdir(exist_ok=True); (R/"INTERSPEECH_2025_TWENTYFIFTH_D3_NOTES.md").write_text("\n".join(md)+"\n"); print(json.dumps({"notes":len(notes),"claims":len(claims)}))
