"""Write first-principles notes for D3 batch 052."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent; DATA = HERE / "data"; REPORTS = HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftysecond-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}
N = {
"christodoulidou25_interspeech": ("recognition-and-alignment", "boundaries-and-sequence-structure", "alignment", "A field study needs reliable vowel measurements from children's dialect speech even when recordings are noisy and automatic transcripts are imperfect.", "Child speech, non-standard dialect, and field conditions shift the acoustic and language distributions assumed by pretrained transcription and alignment models.", "Run an off-the-shelf ASR and forced aligner and treat every predicted boundary as ground truth.", "Correct the transcript before forced alignment and adapt the acoustic model toward child speech, then compare automatic measurements with manual annotations.", "WhisperX supplies a transcription, manual correction changes the lexical scaffold, and MFA places segment boundaries; adaptation changes the acoustic model used for alignment.", "The pipeline separates lexical uncertainty from boundary uncertainty: a better transcript and a better acoustic model affect the measured vowel interval through different paths.", "Manual transcript correction improves acoustic vowel measures, and adaptation of the pretrained MFA model helps, while merely increasing the adaptation sample does not add the same improvement.", "The 275-child Scottish-English field corpus, manual reference quality, recording conditions, and selected vowel measures bound transfer; alignment quality is not a complete child-speech recognizer evaluation."),
"ghosh25_interspeech": ("recognition-and-alignment", "boundaries-and-sequence-structure", "disfluency-preservation", "Speech therapy and feedback need to locate the onset and extent of dysfluencies, not only label an entire utterance as fluent or disfluent.", "Weak utterance labels do not say where an event begins, dysfluencies can overlap ordinary variation, and synthetic speech does not reproduce real timing reliably.", "Assign one label to the whole utterance or cut the signal with fixed windows and ignore uncertainty in pseudo-labels.", "Represent overlapping windows as a graph, refine edge weights with a weakly supervised pseudo-oracle, and use uncertainty-aware normalized cuts to segment events; add real frame-level annotations.", "Speech embeddings form graph nodes, similarity edges are adjusted by a classifier, and Monte Carlo dropout controls how strongly uncertain predictions affect the partition.", "Graph partitioning converts local acoustic similarity into event boundaries, while uncertainty limits the influence of labels least supported by the weak supervision.", "StutterCut reports better F1 and more precise stuttering-onset detection on real and synthetic data, and the extended FluencyBank boundaries make the evaluation less dependent on synthetic events.", "Dysfluency types, annotation quality, speaker population, synthetic-real mismatch, and feedback protocol constrain the claim; segmentation accuracy is not demonstrated therapy benefit."),
"han25d_interspeech": ("listening-and-separation", "source-separation-and-spatial-listening", "target-conditioned-separation", "A vehicle assistant must separate overlapping passengers' speech in a changing cabin without introducing distortion that harms recognition.", "Distributed heterogeneous microphones have different impulse responses, sources cross spatial zones, and a separator can improve isolation while damaging the words an ASR system needs.", "Use a generic monaural mask or optimize separation quality without modeling the cabin or downstream recognition cost.", "Combine channel-aware spatial features with mask-based MVDR, augment training with both simulated and real impulse responses, and evaluate the separated signal through ASR.", "The mask estimates speech/noise structure from multichannel features; MVDR uses spatial covariance to preserve the chosen target, while mixed impulse-response augmentation exposes zone-boundary variation.", "Separation is constrained by two objectives: suppress interference through spatial covariance while retaining a distortionless target direction for the recognizer.", "CabinSep reports a 17.5% relative ASR error reduction over DualSep on real recordings at 0.4 GMACs, with better behavior around speaker-zone boundaries.", "Cabin geometry, array placement, impulse-response coverage, ASR backend, and compute measure constrain generalization; ASR improvement is not proof of perceptual superiority for every listener."),
"jing25b_interspeech": ("listening-and-separation", "source-separation-and-spatial-listening", "spatial-filtering", "In a noisy multi-talker scene, a listener or recognizer needs the speaker inside a requested spatial region while suppressing nearby voices.", "Direction of arrival alone is ambiguous, beamwidth controls a precision-recall tradeoff, and multiple speakers can occupy overlapping acoustic and spatial regions.", "Apply a fixed beamformer or condition extraction only on a speaker embedding while ignoring where the target is.", "Guide an end-to-end target extractor with DOA and beamwidth embeddings so the requested spatial region becomes an explicit conditioning signal.", "The model combines spatial and temporal features, uses the DOA as a center and beamwidth as the permitted region, and generates the target waveform for enhancement and ASR.", "The beamwidth is a controllable spatial prior: narrowing it suppresses more off-axis energy but risks target loss, while widening it preserves coverage at the cost of interference.", "The paper reports stronger target enhancement, interference suppression, and downstream ASR performance in the evaluated noisy multi-talker scenarios.", "DOA estimation, array geometry, spatial overlap, noise type, beamwidth selection, and benchmark composition bound transfer; reported ASR gains do not establish universal spatial hearing quality."),
"huang25h_interspeech": ("languages-accents-and-resources", "accent-and-cultural-boundaries", "accent-robustness", "Accent analysis should relate an observable accent difference to speech production rather than treating a phoneme mismatch as an unexplained label.", "Accent strength is a proxy derived from reference pronunciations, while articulatory inversion is itself uncertain and dialect differences can be localized to particular sounds.", "Count transcription differences and declare them an accent score, or infer articulatory movement without checking whether it tracks the accent proxy.", "Use dictionary-based phonetic differences as an accent-strength index and correlate it with articulatory features inferred from acoustic speech.", "Self-supervised articulatory inversion estimates tongue and related articulator features; phoneme-level deviations from dictionary references provide the comparison variable across American and British English.", "The analysis links two imperfect measurements—phonological deviation and inferred movement—so correlation tests whether an accent proxy has a plausible production-level signature.", "The paper reports dialect differences in tongue positioning, especially for rhotic and low-back vowels, and associations between derived articulatory parameters and indexed accent strength.", "Read speech, two dialect groups, dictionary assumptions, inversion error, and correlation do not establish a universal accent scale or causal articulatory explanation."),
"hamann25_interspeech": ("languages-accents-and-resources", "accent-and-cultural-boundaries", "cultural-meaning", "Listeners must discriminate sound sequences that are native, permitted only in loanwords, or absent from the native phonotactics.", "Native-language expectations shape perception, but exposure to foreign languages and lexical status may create graded rather than binary categories.", "Treat every non-native sequence as equally foreign or infer perception directly from phonotactic legality.", "Compare AX discrimination of a loan-permitted sequence with a prohibited sequence and measure whether individual English exposure explains performance.", "Japanese listeners discriminate /ti/ and /zi/ contrasts in an online task; sequence status and self-reported English input are tested as competing explanations.", "Phonotactic knowledge acts as a prior over possible sequences, but the experiment tests whether that prior fully determines auditory discrimination.", "Thirty-nine listeners performed better on the loanword-permitted sequence, though the foreign sequence was also often discriminated; self-reported English input did not explain the result.", "Online testing, sequence choices, speaker exposure, sample size, and self-report limit generalization; discrimination is not equivalent to lexical access or translation competence."),
"li25b_interspeech": ("voice-generation-and-control", "text-to-speech-and-content", "text-to-speech-planning", "Long-form speech should sound like one coherent reading rather than a row of independently synthesized sentences with changing style and voice.", "Paragraph context affects prosody and discourse emphasis, but autoregressive context is expensive and sentence concatenation loses information across boundaries.", "Synthesize each sentence independently and concatenate the waveforms, or attend to the entire paragraph without controlling the generation cost.", "Maintain long-term and local context in a dynamic memory and use a prefix mask to provide bidirectional context to sentence-level synthesis while keeping generation causal.", "The context-aware memory retrieves and updates paragraph information; local details and long-term style guide each sentence, while prefix tokens supply in-context information without unrestricted future leakage.", "The system separates memory access from waveform generation, trading a bounded context representation for coherence and lower context-inference cost.", "The model outperforms the reported baselines on paragraph-level prosody expressiveness, coherence, and context-inference cost.", "Text genre, speaker/style conditioning, subjective measures, memory capacity, and paragraph length bound transfer; coherence scores do not prove human preference in broad long-form use."),
"liang25e_interspeech": ("voice-generation-and-control", "text-to-speech-and-content", "text-to-speech-planning", "One speech model should support synthesis, editing, and continuation while preserving voice and acoustic continuity across the operation.", "Separate task-specific models duplicate knowledge, and acoustic tokens contain internal relationships that a simple semantic-to-acoustic mapping can discard.", "Train independent systems for synthesis, editing, and continuation or map semantic tokens to acoustic tokens without modeling acoustic context.", "Use a unified non-autoregressive framework whose input conditions select synthesis, editing, or continuation, while shared training captures common acoustic structure.", "The model dynamically changes conditioning for each task and remains compatible with multiple speech discretizers such as HuBERT, DAC, and SpeechTokenizer.", "A shared representation is treated as a reusable coordinate system for several transformations; voice preservation and audio quality test whether task sharing retains the right invariants.", "SpeechSEC reports MOS-like audio quality of 4.20 versus 4.00 and voice preservation of 0.72 versus 0.58 for synthesis, with usable editing and continuation results.", "Reported scores, codec choice, task mixture, prompts, speakers, and sample protocol bound the comparison; multi-task compatibility is not proof of editing safety or continuity in arbitrary audio."),
}
notes=[]; claims=[]; md=["# INTERSPEECH 2025 fifty-second-pass full-paper notes","","Eight official-PDF readings deepen alignment and disfluency preservation, spatial separation, accent perception, and coherent/editable speech synthesis.",""]
for i,(paper_id,fields) in enumerate(N.items(),1):
    theme,subtheme,concept,bp,wh,naive,ap,mech,math,ww,limits=fields; p=papers[paper_id]; c=captured[paper_id]
    note={"paper_id":paper_id,"title":p["title"],"theme_id":theme,"subtheme_id":subtheme,"concept_id":concept,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"eval":math,"ww":ww,"limits":limits,"dots":{"theme_id":theme,"subtheme_id":subtheme,"concept_id":concept,"sibling_family":"batch-052"},"source":{"kind":"official-isca-archive-paper-page-plus-captured-pdf-text","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"pdf_path":f"data/interspeech-2025-pdfs/{paper_id}.pdf","text_path":c["full_text_path"]},"depth":"D3","evidence_boundary":"D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}
    notes.append(note); claims.append({"claim_id":f"IS25-D3C52-{i:02d}","paper_id":paper_id,"subtheme":subtheme,"claim":ww,"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":limits})
    md += [f"## {i}. {subtheme}","",f"**Paper:** [{p['title']}]({p['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]
    md += [f"- **{label}:** {note[key]}" for label,key in zip(["Ordinary problem","Why hard","Naive attempt","Central move","Mechanism","Mathematical/conceptual structure","What paper reports","Limits"],["bp","wh","naive","ap","mech","math","ww","limits"])] + [""]
(DATA/"interspeech-2025-fiftysecond-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(DATA/"interspeech-2025-fiftysecond-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
REPORTS.mkdir(exist_ok=True); (REPORTS/"INTERSPEECH_2025_FIFTYSECOND_D3_NOTES.md").write_text("\n".join(md)+"\n")
print(json.dumps({"notes":len(notes),"claims":len(claims)}))
