#!/usr/bin/env python3
"""Write evidence-bound first-principles notes for the fifteenth D3 pass."""
import json
from pathlib import Path

H = Path(__file__).resolve().parent; D = H / "data"; R = H / "reports"
C = {x["paper_id"]: x for x in json.loads((D / "interspeech-2025-fifteenth-d3-papers.json").read_text())["papers"]}
P = {x["paper_id"]: x for x in json.loads((D / "interspeech-2025-papers.json").read_text())["papers"]}
N = {
"aboeitta25_interspeech": ("Dysarthric speech changes the sound-to-text mapping, so ordinary ASR errors are not just random noise.", "Distorted phonemes and speaker variability make a recognizer's learned acoustic-to-word mapping unreliable.", "Use a standard recognizer alone, or assume a language model can repair every acoustic error without changing the evidence.", "Compare self-supervised encoders and Whisper with CTC, sequence-to-sequence, and language-model decoding, including cross-dataset and severity tests.", "The language model supplies grammatical and lexical constraints after acoustic decoding; Whisper-Vicuna reports the lowest WER in the paper's TORGO and UASpeech experiments.", "The key intervention is not a new sound model alone: it changes how uncertain acoustic evidence is reconciled with linguistic structure.", "The paper reports Whisper-Vicuna WER of 0.21 on TORGO and 0.24 on UASpeech, with results bounded by the two dysarthric datasets and author-run evaluation.", "Cross-dataset testing is useful, but the datasets, severity labels, decoding prompts, and reported WER do not establish clinical deployment or independent reproduction."),
"braun25_interspeech": ("A speech-based dementia score can correlate with human scores while still being systematically wrong for some people.", "Word-naming performance and fallback rules can make severe impairment look easier to detect than mild impairment or healthy speech.", "Report one overall correlation and treat it as equally meaningful across severity groups.", "Inspect the automated Syndrom-Kurz-Test pipeline by subgroup, transcription quality, item type, and fallback behavior rather than relying on one aggregate number.", "The analysis links scoring artifacts to speech production decline, ASR errors, and fallback handling; apparent agreement can therefore arise from the test design.", "The paper turns evaluation from a single correlation into a chain of measurement decisions whose errors can favor particular groups.", "The paper reports high overall correlation but weaker behavior for healthy and mildly impaired groups and identifies overoptimistic correlations for severely impaired speakers.", "This is an analysis of one standardized assessment and its data; it warns against clinical claims, not a universal ranking of dementia-screening systems."),
"berger25_interspeech": ("A text-to-speech system should pronounce an accent it has barely seen without requiring a large new pronunciation database.", "Pronunciation frontend errors occur before waveform generation and are costly to label for every accent.", "Train a separate full-size pronunciation model for every target accent.", "Transfer pronunciation knowledge from a large multi-accent frontend and measure how much target-accent data is needed as source accents vary in similarity.", "The frontend predicts phones, lexical stress, and prosodic boundaries; target accents are trained with reduced data and compared with full-data and single-accent baselines.", "Accent similarity becomes a data-selection variable: transfer is not merely shared representation, but choosing a source whose pronunciation structure is useful for the target.", "The paper reports up to 95% less pronunciation training data for robust performance and examines 14 English accents using LibriTTS and HiFi-TTS-derived data.", "Accuracy is reported for the studied accents, frontend labels, and datasets; transfer to other languages, voices, and synthesis backends remains unestablished."),
"bataev25_interspeech": ("A recognizer must recognize rare or domain-specific words without paying the full cost of beam search on every utterance.", "Greedy decoding is cheap but loses context; beam search recovers some context at a large compute cost.", "Use beam search everywhere, or add a sequential language model whose data structure serializes every transition.", "Represent n-gram transitions for parallel GPU lookup and inject their scores into greedy decoding for CTC, transducer, and attention models.", "NGPU-LM uses hash-based transition lookup and customizable greedy decoding so context biasing can recover domain words with less than 7% reported overhead.", "The conceptual trade is between linguistic context and decoding latency; data structure and hardware choices move that boundary without changing the acoustic model.", "The paper reports recovery of more than half the greedy/beam accuracy gap in out-of-domain tests and up to 10.6% relative WER improvement in its experiments.", "The results depend on tested ASR architectures, domains, GPU implementation, and author-reported measurements; deployment energy and other hardware remain open."),
"bashir25_interspeech": ("A speech-quality score should remain meaningful when processing changes the timing of the speech, not only its spectrum.", "Reference-based intelligibility predictors compare aligned clean and degraded signals; time modification breaks that alignment.", "Use MFCC-based dynamic time warping or assume time modification is a small nuisance.", "Align clean and time-modified speech with selected spectro-temporal modulation features, then feed the alignment into existing reference-based intelligibility predictors.", "The system uses DTW over modulation features and compares two ways of incorporating the alignment into RB-SIPAs across noise and time-modification conditions.", "The move separates two questions that are often mixed: finding corresponding speech events and predicting whether the resulting signal is intelligible.", "The paper reports better alignment behavior and better correlation with listening scores than MFCC-based alternatives under its tested conditions.", "The listening datasets, degradation types, chosen modulation channels, and reference availability bound the claim; correlation is not a complete model of listener experience."),
"alcalapadilla25_interspeech": ("A hearing aid should extract the person the listener wants from any direction without exceeding real-time and complexity limits.", "A fixed-direction extractor cannot follow a target that moves, while binaural hearing-aid hardware limits compute and latency.", "Train one extractor per direction or encode direction as a large one-hot vector.", "Encode direction of arrival with compact complex exponentials and inject it into a low-complexity target-speaker extractor through several conditioning designs.", "The extractor receives binaural signals plus direction information; simulations vary room, target angle, and interference while comparing FiLM, concatenation, and other integrations.", "Direction is treated as a continuous control signal that conditions separation, rather than as a class label that forces a separate model for each angle.", "The complex-exponential encoding outperforms the baseline in 16 of 21 objective-measure cases in the paper's simulated and hearing-aid evaluation.", "The evidence is primarily objective and author-reported, with simulated rooms and tested angles; listener benefit, hardware implementation, and unseen acoustic conditions remain open."),
"akti25_interspeech": ("Voice conversion should change who is speaking and how they express themselves without carrying over unwanted traits from the source voice.", "Content, speaker identity, and expressive style are entangled in speech, especially when source and target speakers differ.", "Use one latent representation for everything, or add style features without testing whether source identity leaks through.", "Use multilingual discrete units for content, augmentation-based similarity loss and mix-style normalization to reduce leakage, and local F0 plus global pitch/energy embeddings for expression.", "A conditional variational autoencoder separates content and style; cross-attention injects local pitch while style embeddings carry global pitch and energy.", "Disentanglement is evaluated as a controlled trade: preserve linguistic content while moving speaker identity and emotion, rather than optimizing one perceptual score.", "The paper reports better emotion and speaker similarity than baselines, with WER, EER, classification accuracy, and MOS used to expose different tradeoffs.", "The experiments use English corpora and author-reported human ratings; disentanglement outside the tested emotions, languages, speakers, and recording conditions remains unresolved."),
"amoniyan25_interspeech": ("A speech sound can carry social meaning differently across communities; a model built from one population can mistake local variation for a universal rule.", "The pronunciation of /s/ varies with ethnicity, age, gender, and linguistic ecology, and these factors can interact.", "Treat a finding from a Western monolingual sample as the general explanation for /s/ variation.", "Measure 4,056 Nigerian English /s/ tokens using spectral and temporal cues, then model ethnicity, year of birth, gender, and speaker variation together.", "Center of gravity, zero crossings, duration, and skewness operationalize fronting and retraction; mixed statistical models test which social and speaker factors explain each cue.", "The paper makes the social boundary part of the acoustic mechanism: the same segment is interpreted through a multilingual community rather than a single universal speaker category.", "The paper reports younger speakers as more fronted, Igbo speakers as more fronted, and Yoruba/Hausa speakers as more retracted, with little overall gender effect.", "The result is bounded to Nigerian English, the ICE-NigE corpus, the sampled years, and the chosen /s/ measures; it does not justify racial or gender generalizations elsewhere."),
"behera25_interspeech": ("An enhancement model should adapt when the noise at test time differs from training, even without labeled examples from the new environment.", "Noise and recording domains shift at deployment, while collecting clean/noisy pairs for every new domain is expensive.", "Freeze the enhancement model and hope training-domain noise statistics transfer.", "Use a Y-shaped enhancement model with self-supervised reconstruction or masked-spectrogram tasks during test-time adaptation.", "The main enhancement task shares representations with an auxiliary task optimized on the current noisy signal, with strategies trading adaptation gain against test-time cost.", "The method treats deployment as a second learning stage: the signal supplies an unsupervised clue about the new domain while the enhancement objective remains the output target.", "The paper reports consistent speech-quality improvements over its baseline on synthetic and real-world datasets.", "The adaptation steps, compute budget, noise conditions, and author-reported metrics bound the result; listener benefit and long-term stability remain open."),
"carofilis25_interspeech": ("A recognizer needs to adapt to a new domain when only a little labeled speech is available but related audio is abundant.", "Unlabeled audio can add coverage but can also inject wrong pseudo-labels and reinforce domain errors.", "Fine-tune once on the small labeled set or choose pseudo-labels randomly.", "Incrementally combine in-domain labels with related-domain data, then filter pseudo-labels using multi-model consensus or named-entity recognition.", "The pipeline retrains in stages and uses agreement or entity preservation to decide which generated transcripts enter the next training round.", "Data selection is treated as part of learning: the value of unlabeled speech depends on which errors are admitted, not only on how much audio is added.", "The paper reports up to 22.3% relative improvement on Wow and 24.8% on Fisher over random selection, with consensus strongest and NER cheaper.", "The gains are bounded to the two English corpora, model ensemble, filtering thresholds, and author-reported WER; other domains and languages remain unresolved."),
"cai25_interspeech": ("Large child-speech collections need segment boundaries, but an adult-trained aligner may place those boundaries according to a different rule than a human analyst.", "Children's articulation and developmental variation make forced alignment less stable, and disagreement can change measured vowel durations or trajectories.", "Treat an adult forced aligner as interchangeable with manual annotation.", "Compare human-human reliability with manual-versus-Montreal-Forced-Aligner boundaries across child ages and inspect systematic discrepancies.", "The study evaluates vowel boundaries in Australian-English child speech and asks how alignment error changes from ages four to eleven.", "The conceptual issue is not simply alignment accuracy: a boundary is an analytic decision whose meaning must be shared by the tool and the human measurement protocol.", "The paper reports that MFA falls short of human annotation, with smaller discrepancies for older children.", "The evidence is tied to the tested vowels, ages, language variety, and annotators; it supports semi-automatic caution rather than universal aligner failure."),
"das25_interspeech": ("A spoof detector should recognize synthetic audio from new generators and public-domain conditions, not only the generator seen during training.", "Semantic embeddings can learn the message instead of the traces of synthesis, while in-domain scores can hide failure under distribution shift.", "Optimize only on a matched generator and report one in-domain score.", "Use non-semantic universal audio representations and compare them with handcrafted, semantic, and end-to-end alternatives under out-of-domain tests.", "TRILL and TRILLsson representations are evaluated as features for a spoofing classifier across in-domain and public-domain conditions.", "The method changes what evidence the detector is allowed to use: it seeks production artifacts that survive a change in spoken content and generator.", "The paper reports comparable in-domain performance and stronger out-of-domain results than the tested baselines.", "The generators, corpora, representation models, and author-reported tests define the boundary; future synthesis methods and adversarial adaptation remain open."),
}
fields = [("bp", "Big picture"), ("wh", "Why hard"), ("naive", "Naive attempt"), ("ap", "Central move"), ("mech", "Mechanism"), ("math", "Conceptual structure"), ("ww", "What paper reports"), ("limits", "Limits")]
notes=[]; claims=[]; out=["# INTERSPEECH 2025 fifteenth-pass full-paper notes", "", "Eight official-PDF analyses deepen clinical speech, accent boundaries, recognition, enhancement, separation, and voice conversion. Results remain author-reported and were not independently reproduced.", ""]
for i,pid in enumerate(C,1):
    vals=N[pid]; p=P[pid]; cap=C[pid]; d=dict(zip(["bp","wh","naive","ap","mech","math","ww","limits"],vals)); d.update({"subtheme":cap["subtheme"],"paper_id":pid,"title":p["title"]}); notes.append(d)
    out += [f"## {i}. {cap['subtheme']}", "", f"**Paper:** [{p['title']}]({p['paper_url']})", f"**Evidence:** D3; PDF SHA-256 {cap['pdf_sha256']}; {cap['page_count']} pages.", ""] + [f"- **{lab}:** {d[key]}" for key,lab in fields] + [""]
    claims.append({"claim_id":f"IS25-D3C15-{i:02d}","paper_id":pid,"subtheme":cap["subtheme"],"claim":d["ww"],"evidence_depth":"D3","pdf_sha256":cap["pdf_sha256"],"full_text_sha256":cap["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":d["limits"]})
(D / "interspeech-2025-fifteenth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(D / "interspeech-2025-fifteenth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
(R / "INTERSPEECH_2025_FIFTEENTH_D3_NOTES.md").write_text("\n".join(out)+"\n")
print(json.dumps({"notes":len(notes),"claims":len(claims)}))
