#!/usr/bin/env python3
import json
from pathlib import Path
H=Path(__file__).resolve().parent; D=H/'data'; R=H/'reports'
C={x['paper_id']:x for x in json.loads((D/'interspeech-2025-thirteenth-d3-papers.json').read_text())['papers']}
P={x['paper_id']:x for x in json.loads((D/'interspeech-2025-papers.json').read_text())['papers']}
N=[
('listening-and-separation/echo-and-reconstruction','rong25_interspeech','Packet loss removes evidence rather than merely adding noise; a universal enhancer must reconstruct missing regions and then handle other distortions.','Lost segments interact with noise, reverberation, clipping, bandwidth limits, codec damage, and residual loss.','Use one denoiser and assume missing samples behave like ordinary noise.','Use a three-stage pipeline: filling, separation, and restoration.','The filling stage predicts lost regions, separation suppresses noise/reverb/clipping, and restoration repairs bandwidth, codec, and remaining loss.','Stage-wise spectral or waveform reconstruction is evaluated in the URGENT challenge setting.','Packet loss is a missing-evidence problem and should not be collapsed into generic denoising.','The system ranked second in URGENT Track 1.','Challenge conditions, author-reported ranking, and no independent run limit the claim.'),
('recognition-and-alignment/adaptation-and-open-vocabulary','kim25d_interspeech','Open-vocabulary keyword spotting must find arbitrary words without preparing word-aligned training data for every target.','Forced alignment is costly, while streaming recognition cannot wait for a separately aligned corpus.','Build a fixed-vocabulary detector or use an external forced aligner and precomputed word segments.','Integrate W-CTC forced alignment into a fully end-to-end streaming system.','CTC paths supply word-span alignment while the text encoder and verifier are trained in the same pipeline.','CTC alignment links acoustic frames to text; keyword audio-text similarity then scores arbitrary words.','Open vocabulary is a training and alignment problem, not only a larger keyword list.','The paper reports superior performance on the Libriphrase hard set.','Benchmark, language, and author-reported result limit generalization and independent reproducibility.'),
('people-variation-and-health/clinical-and-assistive-speech','inoue25b_interspeech','Silent-speech decoding could let speech-impaired users communicate without vocalizing, but biosignal recordings vary across people and electrode layouts.','EEG and EMG configurations are heterogeneous and patient data are scarce, so a single fixed-subject model does not transfer well.','Train one model per subject with one fixed electrode configuration.','Handle heterogeneous electrodes and use multitask training for cross-subject and cross-language calibration.','A shared model learns from varying EEG/EMG layouts while multitask objectives stabilize word classification across speakers and languages.','Word classification accuracy measures whether neural signals preserve enough information for decoding.','Assistive speech is constrained by sensing hardware and patient variation as much as by the decoder.','Accuracy is 95.3% for healthy participants and 54.5% for a patient, versus 70.1% and 13.2% for single-subject baselines.','Patient count, setup, calibration, and author-reported results limit clinical deployment claims.')]
F=[('bp','Big picture'),('wh','Why hard'),('naive','Naive attempt'),('ap','Central move'),('mech','Mechanism'),('math','Mathematical idea'),('dots','Connections'),('ww','What paper reports'),('limits','Limits')]
notes=[]; claims=[]; out=['# INTERSPEECH 2025 thirteenth-pass full-paper notes','','Three official-PDF analyses close the remaining reviewed-evidence gaps for packet-loss concealment, open-vocabulary recognition, and augmentative communication. Results remain author-reported and were not independently reproduced.','']
for i,row in enumerate(N,1):
 d=dict(zip(['subtheme','paper_id','bp','wh','naive','ap','mech','math','dots','ww','limits'],row)); notes.append(d); p,cap=P[d['paper_id']],C[d['paper_id']]
 out += [f'## {i}. {d["subtheme"]}','',f'**Paper:** [{p["title"]}]({p["paper_url"]})  ',f'**Evidence:** D3; PDF SHA-256 {cap["pdf_sha256"]}; {cap["page_count"]} pages.','']+[f'- **{lab}:** {d[key]}' for key,lab in F]+['']
 claims.append({'claim_id':f'IS25-D3C13-{i:02d}','paper_id':d['paper_id'],'subtheme':d['subtheme'],'claim':d['ww'],'evidence_depth':'D3','pdf_sha256':cap['pdf_sha256'],'full_text_sha256':cap['full_text_sha256'],'support_status':'paper-reported-not-independently-verified','independent_support_status':'not-established','limitations':d['limits']})
(D/'interspeech-2025-thirteenth-d3-notes.json').write_text(json.dumps({'venue':'INTERSPEECH 2025','evidence_depth':'D3','notes':notes},indent=2,ensure_ascii=False)+'\n')
(D/'interspeech-2025-thirteenth-claim-ledger.json').write_text(json.dumps({'venue':'INTERSPEECH 2025','claim_count':len(claims),'claims':claims},indent=2,ensure_ascii=False)+'\n')
(R/'INTERSPEECH_2025_THIRTEENTH_D3_NOTES.md').write_text('\n'.join(out)+'\n')
print(json.dumps({'notes':len(notes)}))
