#!/usr/bin/env python3
"""Write first-principles notes for the tenth captured INTERSPEECH D3 set."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA, REPORTS = HERE / "data", HERE / "reports"
capture = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-tenth-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

def note(subtheme, pid, bp, wh, naive, ap, mech, math, dots, ww, limits):
    return {"subtheme":subtheme,"paper_id":pid,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"dots":dots,"ww":ww,"limits":limits}

notes = [
 note("sound-and-production/time-frequency-measurement","guo25b_interspeech","Speech in noise may depend on acoustic information above the frequency range normally used by speech systems.","High-frequency cues can be masked, and an ASR result does not automatically explain why a human listener benefits from them.","Discard everything above 6–8 kHz because it is assumed irrelevant to phonemes.","Use a phoneme recognizer as a controlled probe of which frequency bands help under masking and spatial separation.","A neural network decodes phonemes from cochleagrams of broadband, 8-kHz-low-pass, and 6-kHz-low-pass speech under quiet and masked conditions.","Recognition accuracy and phoneme-omission probabilities are compared across target-to-masker ratios, filtering conditions, and consonant/vowel classes.","The model is a probe for an acoustic cue, not proof that it hears like a person.","Broadband speech improves phoneme accuracy in masked conditions, especially at lower TMR, while adding no quiet-condition benefit; removing extended high frequencies increases consonant omissions.","VCTK speech, selected maskers, cochleagram assumptions, and a model-based probe bound the conclusion; audiological benefit and general ASR deployment are not established."),
 note("listening-and-separation/echo-and-reconstruction","zhao25b_interspeech","Echo cancellation must work when the room's echo path differs from anything seen during training.","The echo path is hidden, changes with geometry, and can be noisy when measured; double talk makes suppression without near-end damage harder.","Train on synthetic mixtures and assume the learned filter generalizes to every room.","Give the model a room impulse response as a prompt so it can condition cancellation on acoustic structure at test time.","ICCRN receives several RIR-prompt fusion variants; tests cover matched and mismatched synthetic RIRs plus recorded real RIRs in double-talk and far-end single-talk conditions.","ERLE measures echo suppression, PESQ near-end quality, SDR near-end fidelity, and MACs/parameters expose the prompt cost.","The room response becomes an explicit conditioning variable instead of an unobserved nuisance.","Fusion method (d) is strongest on mismatched and real-RIR ICCRN tests; the reported real-RIR double-talk values are PESQ 2.19 and ERLE 4.79.","The selected model, fusion choices, RIRs, and author-reported tables bound the claim; independent reproduction and broad room coverage remain absent."),
 note("recognition-and-alignment/boundaries-and-sequence-structure","freisinger25_interspeech","Long transcripts are easier to use when topics are organized into nested sections rather than one flat stream.","Spoken transcripts lack visible chapters, boundaries are ambiguous, and coarse and fine topic changes must be represented across languages and recordings.","Predict one boundary label at each position and evaluate only whether a nearby cut is correct.","Generate a hierarchical table of contents and use a metric that respects its levels; add pause duration only when training can use it.","TOC-NEMO uses LoRA fine-tuning and optional pause cues on AMI, VideoAula, and LectureDE; zero-shot prompting and supervised baselines provide comparisons.","Linear F1/B and hierarchical B distinguish flat boundary quality from agreement across levels; bootstrap and leave-one-speaker-out averages are reported.","A boundary's meaning depends on the level of organization it creates, not only its time location.","Fine-tuned TOC-NEMO plus pause cues reports the strongest linear scores, including AMI F1 30.34/B 24.81 and VideoAula F1 67.34/B 55.18.","Datasets, prompts, annotations, and metric behavior constrain the result; transcript segmentation is not proof of human topic understanding."),
 note("voice-generation-and-control/text-to-speech-and-content","lee25h_interspeech","A useful device speech generator must be intelligible, natural, fast enough for streaming, and usable across speakers.","Codec TTS often predicts several discrete code levels sequentially, making large models slow even when waveform quality is good.","Use a large autoregressive decoder and accept long latency, or predict code levels independently and lose their dependencies.","Use a Mamba acoustic model with depthwise residual-codec decoding: masked refinement preserves dependencies, while implicit neural representation predicts levels in parallel.","SMAM is tested with MLM, INR, and no-MLM decoding in a zero-shot speaker-conditioned setup; CER, similarity, quality, real-time factor, latency, and listening scores separate tradeoffs.","MLM reports 26M parameters, CER 2.73, RTF 0.701, latency 0.065 s, MOS 4.02, and SMOS 3.36; INR uses 25M parameters and RTF 0.568 with latency 0.061 s.","This is structured prediction under a time budget: preserving codec dependencies improves quality while parallel prediction improves speed.","The proposed models are smaller and faster than listed non-streaming baselines while remaining competitive; removing MLM degrades quality measures.","Codec, datasets, hardware, and zero-shot speaker conditions bound the conclusion; other languages and devices are not established."),
 note("people-variation-and-health/human-centered-evaluation","harmsen25_interspeech","Reading fluency assessment should capture accuracy, smoothness, phrasing, and pacing without manually scoring every child.","ASR and timing errors can corrupt the educational measure, and agreement with transcript proxies is not the same as instructional validity.","Use words-correct-per-minute alone or treat an accurate transcript as sufficient evidence that every fluency measure is valid.","Extract fifteen measures from ASR transcripts and timings, then compare them with the same measures from human transcripts.","The study evaluates 244 recordings from 131 Dutch children aged 6–13, compares four ASR systems, and correlates automatic and human-derived fluency measures.","WER, timing F1, and Pearson correlations quantify separate links from audio to educational measure; 12 of 15 measures show strong correlations.","An automatic metric is useful only if its errors preserve the human construct being measured.","The best reported system has WER 12.3% and timing F1 0.82; twelve measures meet r ≥ 0.7.","Dutch child reading, fixed texts, age distribution, ASR choice, and transcript comparison limit generalization; intervention or diagnosis validity is not established."),
 note("evaluation-deployment-and-consequence/robustness-and-system-boundary","do25_interspeech","Spoken-language understanding must fit on a device with limited memory and power without losing needed intent and slot decisions.","Pruning can remove rare but important vocabulary or acoustic layers, while average scores can hide task-specific loss.","Shrink a model uniformly or remove the smallest weights without asking which tokens and layers support the task.","Prune task-irrelevant vocabulary first, prune layers structurally, then refine with distillation and contrastive losses.","PruneSLU starts from Whisper-tiny, selects a base vocabulary, chooses layers by loss, and trains with language-model, distillation, and contrastive components on STOP and SLURP.","Exact match, EM-Tree, intent accuracy, slot F1, parameter counts, and pruning/loss ablations expose the tradeoff.","Deployment is constrained optimization: retained representation must preserve task structure, not merely parameter magnitude.","The 15M model retains 98% of original STOP performance, reaches STOP EM 72.31 and SLURP slot F1 71.42, and improves on listed compression baselines.","STOP/SLURP domains, Whisper initialization, five seeds, and author-reported comparisons bound the result; energy and open-world commands are not tested."),
 note("evaluation-deployment-and-consequence/metrics-and-targets","kibria25_interspeech","A quality predictor should approximate what listeners hear without requiring a listening test for every utterance.","Ratings are noisy, quality depends on local defects and whole-utterance context, and large encoders make prediction impractical.","Train a large model on MOS labels and treat every listener score as equally reliable.","Use attention for local and global context in a small model, then sequentially teach it from refined targets to reduce noisy-rating effects.","AttentiveMOS uses Swin and transformer attention with 86K parameters and is evaluated across in-domain, out-of-domain, and cross-domain MOS datasets.","MSE measures rating error while Pearson and Spearman measure agreement; SOMOS-clean reports MSE 0.257, PCC 0.449, and SRCC 0.442.","A metric predictor is itself a deployment model whose compactness and domain shift must be measured alongside correlation.","It beats listed lightweight baselines in the reported SOMOS-clean comparison, but PCC falls to 0.359 on out-of-domain LIVETALK.","MOS labels, listener composition, dataset domains, and the sharp shift drop limit claims of general quality assessment."),
 note("listening-and-separation/noise-enhancement","leschanowsky25_interspeech","A codec can sound pleasant yet make words harder to understand, so intelligibility needs its own evaluation target.","Quality scores and WER can miss phoneme-specific distortions and listener-dependent effects, especially for generative codecs.","Use MOS or WER as a universal proxy for whether listeners identify speech sounds.","Provide a standardized rhyme-test toolkit and compare its subjective results with objective intelligibility measures.","SITool runs Diagnostic and Modified Rhyme Tests in laboratory or crowdsourcing settings; thirteen codecs are evaluated with phoneme, gender, and wordlist analyses.","Subjective scores are compared with STOI, ESTOI, and WER; only STOI and ESTOI significantly correlate in the reported analysis.","The target determines the metric: intelligibility is not interchangeable with naturalness or transcription accuracy.","Some neural codecs outperform traditional codecs in subjective intelligibility, but objective agreement varies and scores show gender- and wordlist-specific differences.","The codec set, English tests, listener screening, and objective metrics bound the conclusion; the toolkit does not remove human evaluation."),
]

fields=[("bp","Big picture"),("wh","Why hard"),("naive","Naive attempt"),("ap","Central move"),("mech","Mechanism"),("math","Mathematical idea"),("dots","Connections"),("ww","What paper reports"),("limits","Limits")]
out=["# INTERSPEECH 2025 tenth-pass full-paper notes","","Eight additional official-PDF analyses target the thinnest D3 subthemes and add deployment and metric comparisons. Results remain author-reported and were not independently reproduced.",""]
claims=[]
for i,row in enumerate(notes,1):
    paper,cap=papers[row["paper_id"]],capture[row["paper_id"]]
    out += [f"## {i}. {row['subtheme']}","",f"**Paper:** [{paper['title']}]({paper['paper_url']})  ",f"**Evidence:** D3; PDF SHA-256 {cap['pdf_sha256']}; {cap['page_count']} pages.",""]
    out += [f"- **{label}:** {row[key]}" for key,label in fields]+[""]
    claims.append({"claim_id":f"IS25-D3C10-{i:02d}","paper_id":row["paper_id"],"subtheme":row["subtheme"],"claim":row["ww"],"evidence_depth":"D3","pdf_sha256":cap["pdf_sha256"],"full_text_sha256":cap["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":row["limits"]})
(DATA/"interspeech-2025-tenth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(DATA/"interspeech-2025-tenth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
(REPORTS/"INTERSPEECH_2025_TENTH_D3_NOTES.md").write_text("\n".join(out)+"\n")
print(json.dumps({"notes":len(notes),"report":"reports/INTERSPEECH_2025_TENTH_D3_NOTES.md"}))
