"""Write plain-language notes and bounded claims for D3 batch 021."""
import json
from pathlib import Path
H=Path(__file__).resolve().parent; D=H/"data"; R=H/"reports"
C={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-twentyfirst-d3-papers.json").read_text())["papers"]}; P={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-papers.json").read_text())["papers"]}
N={
"funfgeld25_interspeech":("Listeners must infer whether a speaker means the opposite of the words, even when the words themselves sound positive.","Irony depends on timing and pitch accents as well as lexical content, and listeners from different varieties may use those cues differently.","Treat the words or one global pitch statistic as sufficient for sarcasm.","Vary prenuclear and nuclear accent placement/type and measure regional listeners' sarcasm decisions and response times.","German utterances are presented in seven prosodic conditions to listeners from Freiburg and Trier, who classify them as sarcastic or sincere.","The experiment separates cue presence, accent type, region, decision, and reaction time rather than reducing intonation to one pitch average.","Prenuclear accent presence and especially L*+H nuclear accents drive irony judgments; some conditions also yield faster ironic responses.","The utterances, regions, prosodic manipulations, and binary judgment task bound the result; other languages and natural conversations remain open."),
"carta25_interspeech":("A speech recognizer should serve Sardinian varieties despite fragmented data and internal linguistic diversity.","Low-resource languages lack enough transcribed, balanced, and variety-labeled speech for ordinary training recipes.","Pool whatever recordings exist and report one aggregate score that hides variety differences.","Build a reproducible audio-text corpus with explicit variety annotation and evaluate both pretrained and fine-tuned recognizers across varieties.","SardinianVoxes contains about 170 hours of transcribed speech, and the paper defines a benchmark for state-of-the-art and fine-tuned speech-to-text models.","A corpus is a measurement object: coverage, transcription, variety labels, and split design determine what an error rate means.","The paper contributes a public resource and evaluation protocol intended to make Sardinian speech technology measurable.","The reported resource, varieties, transcription quality, and benchmark models bound the claim; future collection and independent use are still needed."),
"degroot25_interspeech":("Enhancement should make dysarthric speech easier to understand or recognize without changing the speaker into an artificial typical voice.","Dysarthric speech varies greatly and enhancement can improve a recognizer while damaging intelligibility or perceived quality.","Optimize a generic noise-reduction score and assume lower noise means better recognition.","Compare two diffusion enhancers with a signal-processing baseline on typical and dysarthric speech, then measure ASR, objective quality, and listener judgments.","The systems enhance two English dysarthric corpora; Whisper-Turbo is evaluated before and after enhancement and fine-tuning.","The paper treats intelligibility, speech quality, and recognition as separate targets, exposing disagreement between them.","The study reports a systematic comparison rather than a single score; gains and tradeoffs depend on corpus, enhancer, and evaluation target.","The corpora, listener tests, Whisper model, and enhancement settings bound the result; a recognition gain is not automatically a clinical benefit."),
"falez25_interspeech":("A detector should say where a fake voice came from, not only that it sounds fake.","Open-set generators and new vocoders create sources not seen during training, and a binary label cannot explain origin.","Train a binary real/fake classifier and treat its confidence as source identity.","Define few-shot identification and verification protocols that trace a generator or one of its components under open-set conditions.","Models are trained on internal and MLAAD data and evaluated across three ASVspoof sets, MLAAD, and Blizzard23.","Identification asks which source class matches a few references; verification asks whether a claimed source is supported, making the decision object explicit.","The paper reports discrimination of unseen source attributes and argues for a standardized source-tracing ontology.","Datasets, source taxonomy, reference count, and generator families bound the result; real-world provenance and adversarial adaptation remain open."),
"chatzichristodoulou25_interspeech":("Emotion recognition should reflect ambiguous human judgments in natural recordings rather than force every clip into one certain label.","Emotions are subjective, classes are imbalanced, and speech and language cues interact.","Train one classifier on hard one-hot labels and sample classes uniformly only after training.","Use cross-modal representation fusion, soft human annotation targets, balanced sampling, multitask learning, and a meta-classifier in stages.","MEDUSA builds an ensemble from self-supervised acoustic and linguistic representations, uses Manifold MixUp, and combines predictions with a trainable meta-classifier.","Soft targets preserve disagreement; balanced sampling changes which examples influence learning; the meta-classifier learns when component predictions should be trusted.","MEDUSA ranked first in the naturalistic categorical emotion challenge task reported by the paper.","Challenge splits, annotation distributions, modalities, and ranking define the result; a leaderboard position does not establish emotion truth or cross-cultural validity."),
"fu25_interspeech":("A listener or robot should locate several overlapping sounds in three dimensions even when noise and reverberation distort the binaural cues.","Sources can overlap, source count may be unknown, and reflections blur the timing and level differences that encode direction.","Estimate one direction with a fixed-resolution classifier or assume the number of sources in advance.","Use a gated coarse-to-fine model that first detects sectors and then regresses azimuth/elevation with a masked multitask loss.","AuralNet processes binaural signals with multi-head attention, jointly detects sources and estimates azimuth/elevation, and is tested in noisy-reverberant conditions.","Classification chooses a spatial sector while regression refines its coordinates; masking lets the loss ignore nonexistent sources.","The paper reports superiority over recent methods in its noisy-reverberant multi-source experiments.","The room simulation/recordings, binaural setup, sector design, and source overlap define the claim; far-field microphone arrays and speech-specific attribution remain open."),
"choi25c_interspeech":("A text-to-speech system should reach good quality without spending excessive computation learning every intermediate diffusion state.","Diffusion models learn a long sequence of noisy-to-clean transformations, and the text and speech views contain different information about the target.","Train the diffusion model longer or add more capacity without teaching it what text and speech already agree on.","Align hidden states using both text-guided and speech-guided objectives so the diffusion process starts with more useful semantic structure.","A-DMA aligns contextual text representations and discriminative speech features during diffusion TTS training, then compares convergence and synthesis quality with baselines.","Alignment reduces the mismatch between two representations before the generative process; convergence speed and output quality are separate objectives.","The paper reports doubled convergence speed with better performance than its baselines.","The text/speech encoders, datasets, diffusion schedule, and quality measures bound the claim; hardware cost and new languages remain open."),
"elhajal25_interspeech":("An ASR system should understand dysarthric speech even when speakers talk slowly and differ greatly from one another.","Recognizer errors may come from rhythm and voice characteristics rather than word content, but changing them can erase identity or introduce artifacts.","Fine-tune an ASR model directly on scarce dysarthric data and hope it learns a stable pronunciation mapping.","Convert dysarthric speech toward a healthier rhythm and voice using unsupervised rhythm/voice conversion, then test whether ASR benefits.","A syllable-based rhythm model extends RnV conversion; LF-MMI and Whisper are trained or fine-tuned with converted speech and tested on Torgo.","The intervention separates a conversion target from the recognition target; WER reveals whether the transformed signal is easier for ASR.","The paper reports significant LF-MMI WER reductions, especially for more severe dysarthria, while Whisper fine-tuning changes little.","Torgo, conversion artifacts, severity labels, ASR architectures, and WER bound the result; intelligibility, speaker identity, and clinical acceptability need separate tests."),
}
keys=["bp","wh","naive","ap","mech","math","ww","limits"]; notes=[]; claims=[]; md=["# INTERSPEECH 2025 twenty-first-pass full-paper notes","","Eight official-PDF readings deepen additional conceptual families. Results are author-reported and not independently reproduced.",""]
for i,(pid,vals) in enumerate(N.items(),1):
 d=dict(zip(keys,vals)); c=C[pid]; d.update({"paper_id":pid,"title":P[pid]["title"],"subtheme":c["subtheme"]}); notes.append(d); md += [f"## {i}. {d['subtheme']}","",f"**Paper:** [{d['title']}]({P[pid]['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]
 md += [f"- **{label}:** {d[key]}" for label,key in zip(["Ordinary problem","Why hard","Naive attempt","Central move","Mechanism","Conceptual structure","What paper reports","Limits"],keys)]+[""]
 claims.append({"claim_id":f"IS25-D3C21-{i:02d}","paper_id":pid,"subtheme":d["subtheme"],"claim":d["ww"],"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":d["limits"]})
(D/"interspeech-2025-twentyfirst-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n"); (D/"interspeech-2025-twentyfirst-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n"); R.mkdir(exist_ok=True); (R/"INTERSPEECH_2025_TWENTYFIRST_D3_NOTES.md").write_text("\n".join(md)+"\n"); print(json.dumps({"notes":len(notes),"claims":len(claims)}))
