#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
HERE=Path(__file__).resolve().parent; DATA=HERE/'data'
A={
 'hopponen25_interspeech':('languages-accents-and-resources','accent-and-cultural-boundaries','dialect-and-variety','The FROST-EMA corpus makes accent and language variation measurable in both articulation and speaker verification.'),
 'horiguchi25b_interspeech':('listening-and-separation','source-separation-and-spatial-listening','blind-source-separation','Overlapping diarization can use speaker identity evidence without first storing a huge simulated mixture corpus.'),
 'hou25_interspeech':('recognition-and-alignment','adaptation-and-open-vocabulary','domain-and-context-biasing','Contextual ASR must rank a large bias list so relevant names and terms do not compete equally for recognition.'),
 'hovsepyan25_interspeech':('people-variation-and-health','clinical-and-assistive-speech','clinical-speech-marker','Low-frequency speech spectra are tested as a possible marker of Parkinsonian motor and neural changes.'),
 'hrabanek25_interspeech':('meaning-and-interaction','prosody-and-intent','prosodic-meaning','Creaky voice is tested as a cue to a Korean stop contrast rather than assumed to carry the same meaning for every listener.'),
 'hsieh25_interspeech':('people-variation-and-health','clinical-and-assistive-speech','dysarthria-and-atypical-speech','Dysarthric speech recognition must adapt to heterogeneous intelligibility groups instead of expecting one augmentation to help everyone.'),
 'hsieh25b_interspeech':('languages-accents-and-resources','accent-and-cultural-boundaries','dialect-and-variety','Pronunciation assessment for Mandarin learners makes non-native accent variation an explicit speech-learning target.'),
 'hu25_interspeech':('recognition-and-alignment','boundaries-and-sequence-structure','alignment','Transcript prompts and dictionary knowledge align acoustic evidence with phonemic and prosodic annotation.'),
 'hu25b_interspeech':('meaning-and-interaction','grounding-and-action','referential-grounding','Audio-text retrieval asks whether a voice representation can connect spoken sound to a matching textual or multimodal referent.'),
 'hu25c_interspeech':('meaning-and-interaction','prosody-and-intent','paralinguistic-state','Emotion labels are not equally separated in speech; label semantics are used as anchors for subtle affective distinctions.'),
 'hu25e_interspeech':('recognition-and-alignment','boundaries-and-sequence-structure','alignment','Word timestamps make the time boundary of each recognized unit explicit for retrieval and subtitles.'),
 'hu25f_interspeech':('meaning-and-interaction','dialogue-and-turn-taking','turn-boundary','Duplex speech-to-speech interaction must model simultaneous streams, barge-in, and turn exchange rather than wait for isolated turns.'),
 'hu25g_interspeech':('listening-and-separation','noise-enhancement','nonstationary-noise','Wireless enhancement must spend limited sensor bits and energy where spatial speech evidence is useful.'),
 'hu25l_interspeech':('people-variation-and-health','human-centered-evaluation','listener-effort','Listener ratings differ by person, so speech quality and emotion models need an ordinal comparison scale that does not erase individual judgment.'),
 'hu25m_interspeech':('listening-and-separation','noise-enhancement','nonstationary-noise','Active noise control must choose microphones and filter order jointly under real-time computation constraints.'),
 'huang25b_interspeech':('evaluation-deployment-and-consequence','privacy-security-and-accountability','spoofing-and-deepfake','A speech classifier must remain trustworthy when an attacker hides a sample-specific trigger inside compressed audio.'),
 'huang25c_interspeech':('listening-and-separation','echo-and-reconstruction','perceptual-enhancement','Speech editing must change a requested region without hallucinating unrelated content or failing under background audio.'),
 'huang25d_interspeech':('meaning-and-interaction','dialogue-and-turn-taking','dialogue-state','Multi-turn spoken understanding must keep the relevant history while ignoring conversational details that no longer affect intent and slots.'),
 'huang25e_interspeech':('evaluation-deployment-and-consequence','privacy-security-and-accountability','spoofing-and-deepfake','Deepfake detection needs a generalization explanation because unseen domains expose whether the detector learned artifacts or forgery evidence.'),
 'huang25f_interspeech':('sound-and-production','source-filter-production','articulatory-coordination','Apical-vowel contrasts link measured tongue configurations to the acoustic categories listeners hear.'),
 'huang25h_interspeech':('languages-accents-and-resources','accent-and-cultural-boundaries','accent-robustness','Accent strength is related to inferred articulatory differences, making pronunciation variation a physical rather than purely label-based boundary.'),
 'huang25i_interspeech':('people-variation-and-health','clinical-and-assistive-speech','dysarthria-and-atypical-speech','Stuttering recognition must preserve both what was said and the clinically relevant event, rather than treat disfluency as disposable noise.'),
 'huang25j_interspeech':('evaluation-deployment-and-consequence','metrics-and-targets','word-error-versus-understanding','Word-level edits reveal why equal error rates can hide larger consequences for rare words and semantic distance.'),
 'hui25_interspeech':('languages-accents-and-resources','accent-and-cultural-boundaries','cultural-meaning','Māori vowel length is perceived through duration and stress, and room acoustics test whether those cues survive everyday listening.'),
 'hussein25_interspeech':('recognition-and-alignment','acoustic-unit-mapping','self-supervised-speech-units','Speech representations must preserve semantic information for recognition while retaining acoustic detail for reconstruction.'),
 'hutin25_interspeech':('sound-and-production','source-filter-production','vocal-tract-filter','French schwa and neighboring vowels are compared through controlled acoustic conditions to separate vowel quality from stress and spelling.'),
 'huttner25_interspeech':('people-variation-and-health','human-centered-evaluation','accessibility-fit','Communication difficulty is a listener-and-speaker experience that must be related to vocal effort, noise, hearing status, and turn timing.'),
 'hwang25_interspeech':('people-variation-and-health','clinical-and-assistive-speech','clinical-speech-marker','Dysphagia detection tests whether large-scale speech representations can support a medical decision under scarce clinical data.')}
REJECT={'hsieh25c_interspeech':'Automatic singing evaluation targets musical performance rather than ordinary speech production, perception, or spoken interaction.','hu25h_interspeech':'HRTF interpolation is spatial-audio rendering without a speech-specific signal or task.','hu25k_interspeech':'Video-to-audio generation targets general audiovisual sound, not speech or spoken language.'}
papers={p['paper_id']:p for p in json.loads((DATA/'interspeech-2025-papers.json').read_text())['papers']}; rows=[]
for pid,reason in REJECT.items():
 p=papers[pid]; a=p.get('abstract',''); rows.append({'paper_id':pid,'title':p['title'],'decision':'unsupported','confidence':'analyst-reviewed-D2','theme_id':None,'subtheme_id':None,'concept_id':None,'semantic_reasoning':reason,'evidence_fields':['title','abstract'],'evidence_excerpt':a[:1400],'source_location':p['paper_url'],'source_sha256':hashlib.sha256(a.encode()).hexdigest(),'evidence_depth':'D2','review_state':'analyst-reviewed','claim_boundary':'Official abstract was sufficient to establish that the paper is outside the speech taxonomy; no speech concept is assigned.'})
for pid,a in A.items():
 p=papers[pid]; abstract=p.get('abstract','')
 if not abstract: raise SystemExit('missing abstract: '+pid)
 rows.append({'paper_id':pid,'title':p['title'],'decision':'supported','confidence':'analyst-reviewed-D2','theme_id':a[0],'subtheme_id':a[1],'concept_id':a[2],'semantic_reasoning':a[3],'evidence_fields':['problem','mechanism','evaluation','boundary'],'evidence_excerpt':abstract[:1400],'source_location':p['paper_url'],'source_sha256':hashlib.sha256(abstract.encode()).hexdigest(),'evidence_depth':'D2','review_state':'analyst-reviewed','claim_boundary':'Abstract supports the problem and proposed move; full-paper mechanism, tables, ablations, and limitations remain unreviewed.'})
payload={'schema_version':1,'batch_id':'interspeech-2025-semantic-d2-batch-014','status':'analyst-reviewed-D2-batch','claim_boundary':'These 30 assignments are analyst readings bounded by official abstracts; three are explicit out-of-scope decisions and supported rows do not establish full-paper mechanisms or results.','reviewed_count':len(rows),'rows':rows}
(DATA/'interspeech-2025-semantic-reviewed-d2-batch-014.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False)+'\n')
print(json.dumps({'batch_id':payload['batch_id'],'reviewed_count':len(rows),'supported':len(A),'unsupported':len(REJECT)}))
