#!/usr/bin/env python3
"""Write a content-addressed manifest for the current bounded speech release."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
FILES = [
    "GOAL.md",
    "FIRST_PRINCIPLES_GOAL.md",
    "build_conceptual_taxonomy.py",
    "build_icassp_semantic_review_queue.py",
    "taxonomy_normalization.py",
    "build_interspeech_semantic_batch_015.py",
    "build_interspeech_semantic_batch_016.py",
    "build_interspeech_semantic_batch_017.py",
    "build_interspeech_semantic_batch_018.py",
    "build_interspeech_semantic_batch_019.py",
    "build_interspeech_semantic_batch_020.py",
    "build_interspeech_semantic_batch_021.py",
    "build_interspeech_semantic_batch_022.py",
    "build_interspeech_semantic_batch_023.py",
    "build_interspeech_semantic_batch_024.py",
    "build_interspeech_semantic_batch_025.py",
    "data/interspeech-2025-semantic-reviewed-batch-025.json",
    "build_interspeech_semantic_batch_026.py",
    "build_interspeech_semantic_batch_027.py",
    "build_interspeech_semantic_batch_028.py",
    "build_interspeech_semantic_batch_029.py",
    "build_interspeech_semantic_batch_030.py",
    "build_interspeech_semantic_batch_031.py",
    "build_interspeech_semantic_batch_032.py",
    "build_interspeech_semantic_batch_033.py",
    "build_interspeech_semantic_batch_034.py",
    "build_interspeech_semantic_batch_035.py",
    "build_interspeech_semantic_batch_036.py",
    "build_interspeech_semantic_batch_037.py",
    "build_interspeech_semantic_batch_038.py",
    "build_interspeech_semantic_batch_039.py",
    "build_interspeech_semantic_batch_040.py",
    "build_interspeech_semantic_batch_041.py",
    "build_interspeech_semantic_batch_042.py",
    "build_interspeech_semantic_batch_043.py",
    "build_interspeech_semantic_batch_044.py",
    "build_interspeech_semantic_batch_045.py",
    "build_interspeech_semantic_batch_046.py",
    "build_interspeech_semantic_batch_047.py",
    "build_interspeech_semantic_batch_048.py",
    "build_interspeech_semantic_batch_049.py",
    "build_interspeech_semantic_batch_050.py",
    "build_interspeech_semantic_batch_051.py",
    "build_interspeech_semantic_batch_052.py",
    "build_interspeech_semantic_batch_053.py",
    "build_sixteenth_d3_set.py", "build_sixteenth_d3_reports.py", "build_sixteenth_semantic_batch.py",
    "build_seventeenth_d3_set.py", "build_seventeenth_d3_reports.py", "build_seventeenth_semantic_batch.py",
    "build_eighteenth_d3_set.py", "build_eighteenth_d3_reports.py",
    "build_nineteenth_d3_set.py", "build_nineteenth_d3_reports.py",
    "build_twentieth_d3_set.py", "build_twentieth_d3_reports.py",
    "build_twentyfirst_d3_set.py", "build_twentyfirst_d3_reports.py",
    "build_twentisecond_d3_set.py", "build_twentisecond_d3_reports.py",
    "build_twentythird_d3_set.py", "build_twentythird_d3_reports.py",
    "build_twentyfourth_d3_set.py", "build_twentyfourth_d3_reports.py",
    "build_twentyfifth_d3_set.py", "build_twentyfifth_d3_reports.py",
    "build_twentysixth_d3_set.py", "build_twentysixth_d3_reports.py",
    "build_twentyseventh_d3_set.py", "build_twentyseventh_d3_reports.py",
    "build_twentyeighth_d3_set.py", "build_twentyeighth_d3_reports.py",
    "build_twentyninth_d3_set.py", "build_twentyninth_d3_reports.py",
    "build_thirtieth_d3_set.py", "build_thirtieth_d3_reports.py",
    "build_thirtyfirst_d3_set.py", "build_thirtyfirst_d3_reports.py",
    "build_thirtysecond_d3_set.py", "build_thirtysecond_d3_reports.py",
    "build_thirtythird_d3_set.py", "build_thirtythird_d3_reports.py",
    "build_thirtyfourth_d3_set.py", "build_thirtyfourth_d3_reports.py",
    "build_thirtyfifth_d3_set.py", "build_thirtyfifth_d3_reports.py",
    "build_thirtysixth_d3_set.py", "build_thirtysixth_d3_reports.py",
    "build_thirtyseventh_d3_set.py", "build_thirtyseventh_d3_reports.py",
    "build_thirtyeighth_d3_set.py", "build_thirtyeighth_d3_reports.py",
    "build_thirtyninth_d3_set.py", "build_thirtyninth_d3_reports.py",
    "build_fortieth_d3_set.py", "build_fortieth_d3_reports.py",
    "build_fortyfirst_d3_set.py", "build_fortyfirst_d3_reports.py",
    "build_fortysecond_d3_set.py", "build_fortysecond_d3_reports.py",
    "build_fortythird_d3_set.py", "build_fortythird_d3_reports.py",
    "build_fortyfourth_d3_set.py", "build_fortyfourth_d3_reports.py",
    "build_fortyfifth_d3_set.py", "build_fortyfifth_d3_reports.py",
    "build_fortysixth_d3_set.py", "build_fortysixth_d3_reports.py",
    "build_icassp_semantic_batch.py",
    "build_icassp_semantic_batch_002.py",
    "build_icassp_semantic_batch_003.py",
    "build_icassp_semantic_batch_004.py",
    "build_icassp_semantic_batch_005.py",
    "build_icassp_semantic_batch_006.py",
    "build_icassp_semantic_batch_012.py",
    "build_icassp_semantic_batch_013.py",
    "build_icassp_semantic_batch_014.py",
    "build_icassp_semantic_batch_015.py",
    "build_icassp_semantic_batch_016.py",
    "build_icassp_semantic_batch_017.py",
    "build_icassp_semantic_batch_018.py",
    "build_icassp_semantic_batch_019.py",
    "build_icassp_semantic_batch_020.py",
    "build_icassp_semantic_batch_021.py",
    "build_icassp_semantic_batch_022.py",
    "build_icassp_semantic_batch_023.py",
    "build_icassp_semantic_batch_024.py",
    "build_icassp_semantic_batch_025.py",
    "build_icassp_semantic_batch_026.py",
    "build_icassp_semantic_batch_027.py",
    "build_icassp_semantic_batch_028.py",
    "build_icassp_semantic_batch_029.py",
    "build_icassp_semantic_batch_030.py",
    "build_icassp_semantic_batch_031.py",
    "build_icassp_semantic_batch_032.py",
    "build_icassp_semantic_batch_033.py",
    "build_icassp_semantic_batch_034.py",
    "build_icassp_semantic_batch_035.py",
    "build_icassp_semantic_batch_036.py",
    "build_icassp_semantic_batch_037.py",
    "build_icassp_semantic_batch_038.py",
    "build_icassp_semantic_batch_039.py",
    "build_icassp_semantic_batch_040.py",
    "build_icassp_semantic_batch_041.py",
    "build_icassp_semantic_batch_042.py",
    "build_icassp_semantic_batch_043.py",
    "build_icassp_semantic_batch_044.py",
    "build_icassp_paper_evidence.py",
    "build_semantic_review_queue.py",
    "build_corpus_semantic_assignments.py",
    "build_semantic_gap_report.py",
    "build_atlas_index.py",
    "build_semantic_review_batch.py",
    "build_semantic_d2_batch.py",
    "build_semantic_d2_batch_002.py",
    "build_semantic_d2_batch_003.py",
    "build_semantic_d2_batch_004.py", "build_semantic_d2_batch_005.py", "build_semantic_d2_batch_006.py", "build_semantic_d2_batch_007.py", "build_semantic_d2_batch_008.py", "build_semantic_d2_batch_009.py", "build_semantic_d2_batch_010.py", "build_semantic_d2_batch_011.py", "build_semantic_d2_batch_012.py",
    "build_first_principles_synthesis.py",
    "build_subtheme_syntheses.py",
    "build_concept_family_crosswalk.py",
    "build_concept_evidence_gaps.py",
    "build_reading_paths.py",
    "build_deep_paper_analyses.py",
    "build_evaluation_audit.py",
    "build_third_d3_set.py", "build_third_d3_reports.py",
    "build_fourth_d3_set.py", "build_fourth_d3_reports.py", "build_fourth_semantic_batch.py",
    "build_fifth_d3_set.py", "build_fifth_d3_reports.py", "build_fifth_semantic_batch.py",
    "build_sixth_d3_set.py", "build_sixth_d3_reports.py", "build_sixth_semantic_batch.py",
    "build_seventh_d3_set.py", "build_seventh_d3_reports.py", "build_seventh_semantic_batch.py",
    "build_eighth_d3_set.py", "build_eighth_d3_reports.py", "build_eighth_semantic_batch.py",
    "build_ninth_d3_set.py", "build_ninth_d3_reports.py", "build_ninth_semantic_batch.py",
    "build_tenth_d3_set.py", "build_tenth_d3_reports.py", "build_tenth_semantic_batch.py",
    "build_eleventh_d3_set.py", "build_eleventh_d3_reports.py", "build_eleventh_semantic_batch.py",
    "build_twelfth_d3_set.py", "build_twelfth_d3_reports.py", "build_twelfth_semantic_batch.py",
    "build_thirteenth_d3_set.py", "build_thirteenth_d3_reports.py", "build_thirteenth_semantic_batch.py",
    "build_semantic_d2_batch_013.py",
    "build_semantic_d2_batch_014.py",
    "build_fourteenth_d3_set.py", "build_fourteenth_d3_reports.py", "build_fourteenth_semantic_batch.py",
    "build_fifteenth_d3_set.py", "build_fifteenth_d3_reports.py", "build_fifteenth_semantic_batch.py",
    "README.md",
    "index.html",
    "site/index.html",
    "data/icassp-2026-papers.json",
    "data/icassp-2026-themes.json",
    "data/icassp-2026-source-manifest.json",
    "data/interspeech-2025-papers.json",
    "data/interspeech-2025-themes.json",
    "data/speech-baseline-source.json",
    "data/speech-first-principles-taxonomy.json",
    "data/icassp-2026-semantic-review-queue.json",
    "data/icassp-2026-semantic-reviewed-batch-001.json",
    "data/icassp-2026-semantic-reviewed-batch-002.json",
    "data/icassp-2026-semantic-reviewed-batch-003.json",
    "data/icassp-2026-semantic-reviewed-batch-004.json",
    "data/icassp-2026-semantic-reviewed-batch-005.json",
    "data/icassp-2026-semantic-reviewed-batch-006.json",
    "data/icassp-2026-semantic-reviewed-batch-007.json",
    "data/icassp-2026-semantic-reviewed-batch-008.json",
    "data/icassp-2026-semantic-reviewed-batch-009.json", "data/icassp-2026-semantic-reviewed-batch-010.json", "data/icassp-2026-semantic-reviewed-batch-011.json", "data/icassp-2026-semantic-reviewed-batch-012.json", "data/icassp-2026-semantic-reviewed-batch-013.json",
    "data/icassp-2026-semantic-reviewed-batch-014.json",
    "data/icassp-2026-semantic-reviewed-batch-015.json",
    "data/icassp-2026-semantic-reviewed-batch-016.json",
    "data/icassp-2026-semantic-reviewed-batch-017.json",
    "data/icassp-2026-semantic-reviewed-batch-018.json",
    "data/icassp-2026-semantic-reviewed-batch-019.json",
    "data/icassp-2026-semantic-reviewed-batch-020.json",
    "data/icassp-2026-semantic-reviewed-batch-021.json",
    "data/icassp-2026-semantic-reviewed-batch-022.json",
    "data/icassp-2026-semantic-reviewed-batch-023.json",
    "data/icassp-2026-semantic-reviewed-batch-024.json",
    "data/icassp-2026-semantic-reviewed-batch-025.json",
    "data/icassp-2026-semantic-reviewed-batch-026.json",
    "data/icassp-2026-semantic-reviewed-batch-027.json",
    "data/icassp-2026-semantic-reviewed-batch-028.json",
    "data/icassp-2026-semantic-reviewed-batch-029.json",
    "data/icassp-2026-semantic-reviewed-batch-030.json",
    "data/icassp-2026-semantic-reviewed-batch-031.json",
    "data/icassp-2026-semantic-reviewed-batch-032.json",
    "data/icassp-2026-semantic-reviewed-batch-033.json",
    "data/icassp-2026-semantic-reviewed-batch-034.json",
    "data/icassp-2026-semantic-reviewed-batch-035.json",
    "data/icassp-2026-semantic-reviewed-batch-036.json",
    "data/icassp-2026-semantic-reviewed-batch-037.json",
    "data/icassp-2026-semantic-reviewed-batch-038.json",
    "data/icassp-2026-semantic-reviewed-batch-039.json",
    "data/icassp-2026-semantic-reviewed-batch-040.json",
    "data/icassp-2026-semantic-reviewed-batch-041.json",
    "data/icassp-2026-semantic-reviewed-batch-042.json",
    "data/icassp-2026-semantic-reviewed-batch-043.json",
    "data/icassp-2026-semantic-reviewed-batch-044.json",
    "data/icassp-2026-semantic-reviewed-batch-045.json",
    "data/icassp-2026-semantic-reviewed-batch-046.json",
    "build_icassp_semantic_batch_047.py",
    "build_icassp_semantic_batch_048.py",
    "build_icassp_semantic_batch_049.py",
    "build_icassp_semantic_batch_050.py",
    "build_icassp_semantic_batch_051.py",
    "build_icassp_semantic_batch_052.py",
    "build_icassp_semantic_batch_053.py",
    "build_icassp_semantic_batch_054.py",
    "build_icassp_semantic_batch_055.py",
    "build_icassp_semantic_batch_056.py",
    "build_icassp_semantic_batch_057.py",
    "build_icassp_semantic_batch_058.py",
    "build_icassp_semantic_batch_059.py",
    "build_icassp_semantic_batch_060.py",
    "build_icassp_semantic_batch_061.py",
    "build_icassp_semantic_batch_062.py",
    "build_icassp_semantic_batch_063.py",
    "build_icassp_semantic_batch_064.py",
    "build_icassp_semantic_batch_065.py",
    "build_icassp_semantic_batch_066.py",
    "build_icassp_semantic_batch_067.py",
    "build_icassp_semantic_batch_068.py",
    "build_icassp_semantic_batch_069.py",
    "build_icassp_semantic_batch_070.py",
    "build_icassp_semantic_batch_071.py",
    "build_icassp_semantic_batch_072.py",
    "build_icassp_semantic_batch_073.py",
    "build_icassp_semantic_batch_074.py",
    "build_icassp_semantic_batch_075.py",
    "build_icassp_semantic_batch_076.py",
    "build_icassp_semantic_batch_077.py",
    "build_icassp_semantic_batch_078.py",
    "build_icassp_semantic_batch_079.py",
    "build_icassp_semantic_batch_080.py",
    "build_icassp_semantic_batch_081.py",
    "build_icassp_semantic_batch_082.py",
    "build_icassp_semantic_batch_083.py",
    "build_icassp_semantic_batch_084.py",
    "build_icassp_semantic_batch_085.py",
    "build_icassp_semantic_batch_086.py",
    "build_icassp_semantic_batch_087.py",
    "build_icassp_semantic_batch_088.py",
    "build_icassp_semantic_batch_089.py",
    "data/icassp-2026-semantic-reviewed-batch-047.json",
    "data/icassp-2026-semantic-reviewed-batch-048.json",
    "data/icassp-2026-semantic-reviewed-batch-049.json",
    "data/icassp-2026-semantic-reviewed-batch-050.json",
    "data/icassp-2026-semantic-reviewed-batch-051.json",
    "data/icassp-2026-semantic-reviewed-batch-052.json",
    "data/icassp-2026-semantic-reviewed-batch-053.json",
    "data/icassp-2026-semantic-reviewed-batch-054.json",
    "data/icassp-2026-semantic-reviewed-batch-055.json",
    "data/icassp-2026-semantic-reviewed-batch-056.json",
    "data/icassp-2026-semantic-reviewed-batch-057.json",
    "data/icassp-2026-semantic-reviewed-batch-058.json",
    "data/icassp-2026-semantic-reviewed-batch-059.json",
    "data/icassp-2026-semantic-reviewed-batch-060.json",
    "data/icassp-2026-semantic-reviewed-batch-061.json",
    "data/icassp-2026-semantic-reviewed-batch-062.json",
    "data/icassp-2026-semantic-reviewed-batch-063.json",
    "data/icassp-2026-semantic-reviewed-batch-064.json",
    "data/icassp-2026-semantic-reviewed-batch-065.json",
    "data/icassp-2026-semantic-reviewed-batch-066.json",
    "data/icassp-2026-semantic-reviewed-batch-067.json",
    "data/icassp-2026-semantic-reviewed-batch-068.json",
    "data/icassp-2026-semantic-reviewed-batch-069.json",
    "data/icassp-2026-semantic-reviewed-batch-070.json",
    "data/icassp-2026-semantic-reviewed-batch-071.json",
    "data/icassp-2026-semantic-reviewed-batch-072.json",
    "data/icassp-2026-semantic-reviewed-batch-073.json",
    "data/icassp-2026-semantic-reviewed-batch-074.json",
    "data/icassp-2026-semantic-reviewed-batch-075.json",
    "data/icassp-2026-semantic-reviewed-batch-076.json",
    "data/icassp-2026-semantic-reviewed-batch-077.json",
    "data/icassp-2026-semantic-reviewed-batch-078.json",
    "data/icassp-2026-semantic-reviewed-batch-079.json",
    "data/icassp-2026-semantic-reviewed-batch-080.json",
    "data/icassp-2026-semantic-reviewed-batch-081.json",
    "data/icassp-2026-semantic-reviewed-batch-082.json",
    "data/icassp-2026-semantic-reviewed-batch-083.json",
    "data/icassp-2026-semantic-reviewed-batch-084.json",
    "data/icassp-2026-semantic-reviewed-batch-085.json",
    "data/icassp-2026-semantic-reviewed-batch-086.json",
    "data/icassp-2026-semantic-reviewed-batch-087.json",
    "data/icassp-2026-semantic-reviewed-batch-088.json",
    "data/icassp-2026-semantic-reviewed-batch-089.json",
    "data/icassp-2026-paper-evidence.jsonl",
    "data/interspeech-2025-semantic-review-queue.json",
    "data/interspeech-2025-semantic-assignments.jsonl",
    "data/icassp-2026-semantic-assignments.jsonl",
    "data/speech-semantic-review-gaps.json",
    "data/interspeech-2025-semantic-reviewed-batch-001.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-001.json",
    "data/interspeech-2025-sixteenth-d3-papers.json",
    "data/interspeech-2025-sixteenth-d3-notes.json",
    "data/interspeech-2025-sixteenth-claim-ledger.json",
    "data/interspeech-2025-seventeenth-d3-papers.json",
    "data/interspeech-2025-seventeenth-d3-notes.json",
    "data/interspeech-2025-seventeenth-claim-ledger.json",
    "data/interspeech-2025-eighteenth-d3-papers.json",
    "data/interspeech-2025-eighteenth-d3-notes.json",
    "data/interspeech-2025-eighteenth-claim-ledger.json",
    "data/interspeech-2025-nineteenth-d3-papers.json",
    "data/interspeech-2025-nineteenth-d3-notes.json",
    "data/interspeech-2025-nineteenth-claim-ledger.json",
    "data/interspeech-2025-twentieth-d3-papers.json",
    "data/interspeech-2025-twentieth-d3-notes.json",
    "data/interspeech-2025-twentieth-claim-ledger.json",
    "data/interspeech-2025-twentyfirst-d3-papers.json",
    "data/interspeech-2025-twentyfirst-d3-notes.json",
    "data/interspeech-2025-twentyfirst-claim-ledger.json",
    "data/interspeech-2025-twentisecond-d3-papers.json",
    "data/interspeech-2025-twentisecond-d3-notes.json",
    "data/interspeech-2025-twentisecond-claim-ledger.json",
    "data/interspeech-2025-twentythird-d3-papers.json",
    "data/interspeech-2025-twentythird-d3-notes.json",
    "data/interspeech-2025-twentythird-claim-ledger.json",
    "data/interspeech-2025-twentyfourth-d3-papers.json",
    "data/interspeech-2025-twentyfourth-d3-notes.json",
    "data/interspeech-2025-twentyfourth-claim-ledger.json",
    "data/interspeech-2025-twentyfifth-d3-papers.json",
    "data/interspeech-2025-twentyfifth-d3-notes.json",
    "data/interspeech-2025-twentyfifth-claim-ledger.json",
    "data/interspeech-2025-twentysixth-d3-papers.json",
    "data/interspeech-2025-twentysixth-d3-notes.json",
    "data/interspeech-2025-twentysixth-claim-ledger.json",
    "data/interspeech-2025-twentyseventh-d3-papers.json",
    "data/interspeech-2025-twentyseventh-d3-notes.json",
    "data/interspeech-2025-twentyseventh-claim-ledger.json",
    "data/interspeech-2025-twentyeighth-d3-papers.json",
    "data/interspeech-2025-twentyeighth-d3-notes.json",
    "data/interspeech-2025-twentyeighth-claim-ledger.json",
    "data/interspeech-2025-twentyninth-d3-papers.json",
    "data/interspeech-2025-twentyninth-d3-notes.json",
    "data/interspeech-2025-twentyninth-claim-ledger.json",
    "data/interspeech-2025-thirtieth-d3-papers.json",
    "data/interspeech-2025-thirtieth-d3-notes.json",
    "data/interspeech-2025-thirtieth-claim-ledger.json",
    "data/interspeech-2025-thirtyfirst-d3-papers.json",
    "data/interspeech-2025-thirtyfirst-d3-notes.json",
    "data/interspeech-2025-thirtyfirst-claim-ledger.json",
    "data/interspeech-2025-thirtysecond-d3-papers.json",
    "data/interspeech-2025-thirtysecond-d3-notes.json",
    "data/interspeech-2025-thirtysecond-claim-ledger.json",
    "data/interspeech-2025-thirtythird-d3-papers.json",
    "data/interspeech-2025-thirtythird-d3-notes.json",
    "data/interspeech-2025-thirtythird-claim-ledger.json",
    "data/interspeech-2025-thirtyfourth-d3-papers.json",
    "data/interspeech-2025-thirtyfourth-d3-notes.json",
    "data/interspeech-2025-thirtyfourth-claim-ledger.json",
    "data/interspeech-2025-thirtyfifth-d3-papers.json",
    "data/interspeech-2025-thirtyfifth-d3-notes.json",
    "data/interspeech-2025-thirtyfifth-claim-ledger.json",
    "data/interspeech-2025-thirtysixth-d3-papers.json",
    "data/interspeech-2025-thirtysixth-d3-notes.json",
    "data/interspeech-2025-thirtysixth-claim-ledger.json",
    "data/interspeech-2025-thirtyseventh-d3-papers.json",
    "data/interspeech-2025-thirtyseventh-d3-notes.json",
    "data/interspeech-2025-thirtyseventh-claim-ledger.json",
    "data/interspeech-2025-thirtyeighth-d3-papers.json",
    "data/interspeech-2025-thirtyeighth-d3-notes.json",
    "data/interspeech-2025-thirtyeighth-claim-ledger.json",
    "data/interspeech-2025-thirtyninth-d3-papers.json",
    "data/interspeech-2025-thirtyninth-d3-notes.json",
    "data/interspeech-2025-thirtyninth-claim-ledger.json",
    "data/interspeech-2025-fortieth-d3-papers.json",
    "data/interspeech-2025-fortieth-d3-notes.json",
    "data/interspeech-2025-fortieth-claim-ledger.json",
    "data/interspeech-2025-fortyfirst-d3-papers.json",
    "data/interspeech-2025-fortyfirst-d3-notes.json",
    "data/interspeech-2025-fortyfirst-claim-ledger.json",
    "data/interspeech-2025-fortysecond-d3-papers.json",
    "data/interspeech-2025-fortysecond-d3-notes.json",
    "data/interspeech-2025-fortysecond-claim-ledger.json",
    "data/interspeech-2025-fortythird-d3-papers.json",
    "data/interspeech-2025-fortythird-d3-notes.json",
    "data/interspeech-2025-fortythird-claim-ledger.json",
    "data/interspeech-2025-fortyfourth-d3-papers.json",
    "data/interspeech-2025-fortyfourth-d3-notes.json",
    "data/interspeech-2025-fortyfourth-claim-ledger.json",
    "data/interspeech-2025-fortyfifth-d3-papers.json",
    "data/interspeech-2025-fortyfifth-d3-notes.json",
    "data/interspeech-2025-fortyfifth-claim-ledger.json",
    "data/interspeech-2025-fortysixth-d3-papers.json",
    "data/interspeech-2025-fortysixth-d3-notes.json",
    "data/interspeech-2025-fortysixth-claim-ledger.json",
    "data/interspeech-2025-semantic-reviewed-d3-batch-015.json",
    "data/interspeech-2025-semantic-reviewed-d3-batch-015.json",
    "data/interspeech-2025-semantic-reviewed-d3-batch-014.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-015.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-016.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-017.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-018.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-019.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-020.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-021.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-022.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-023.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-024.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-025.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-026.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-027.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-028.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-029.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-030.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-031.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-032.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-033.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-034.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-035.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-036.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-037.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-038.json",
    "data/interspeech-2025-semantic-reviewed-batch-026.json",
    "data/interspeech-2025-semantic-reviewed-out-of-scope-batch-038.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-039.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-040.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-041.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-042.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-043.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-044.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-045.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-046.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-047.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-048.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-049.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-050.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-051.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-052.json",
    "data/interspeech-2025-semantic-reviewed-provisional-d2-batch-053.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-002.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-003.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-004.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-005.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-006.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-007.json", "data/interspeech-2025-semantic-reviewed-d2-batch-008.json", "data/interspeech-2025-semantic-reviewed-d2-batch-009.json", "data/interspeech-2025-semantic-reviewed-d2-batch-010.json", "data/interspeech-2025-semantic-reviewed-d2-batch-011.json", "data/interspeech-2025-semantic-reviewed-d2-batch-012.json",
    "data/speech-first-principles-seed-synthesis.json",
    "data/speech-subtheme-syntheses.json",
    "data/speech-concept-family-crosswalk.json",
    "data/speech-concept-evidence-gaps.json",
    "data/speech-first-principles-writeup-audit.json",
    "data/speech-paper-analysis-quality-audit.json",
    "data/speech-taxonomy-adjudication-queue.json",
    "data/interspeech-2025-deep-paper-analyses.jsonl",
    "data/interspeech-2025-evaluation-audit.jsonl",
    "data/interspeech-2025-third-d3-papers.json", "data/interspeech-2025-third-d3-notes.json", "data/interspeech-2025-third-claim-ledger.json",
    "data/interspeech-2025-fourth-d3-papers.json", "data/interspeech-2025-fourth-d3-notes.json", "data/interspeech-2025-fourth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-002.json",
    "data/interspeech-2025-fifth-d3-papers.json", "data/interspeech-2025-fifth-d3-notes.json", "data/interspeech-2025-fifth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-003.json",
    "data/interspeech-2025-sixth-d3-papers.json", "data/interspeech-2025-sixth-d3-notes.json", "data/interspeech-2025-sixth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-004.json",
    "data/interspeech-2025-seventh-d3-papers.json", "data/interspeech-2025-seventh-d3-notes.json", "data/interspeech-2025-seventh-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-005.json",
    "data/interspeech-2025-eighth-d3-papers.json", "data/interspeech-2025-eighth-d3-notes.json", "data/interspeech-2025-eighth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-006.json",
    "data/interspeech-2025-ninth-d3-papers.json", "data/interspeech-2025-ninth-d3-notes.json", "data/interspeech-2025-ninth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-007.json",
    "data/interspeech-2025-tenth-d3-papers.json", "data/interspeech-2025-tenth-d3-notes.json", "data/interspeech-2025-tenth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-008.json",
    "data/interspeech-2025-eleventh-d3-papers.json", "data/interspeech-2025-eleventh-d3-notes.json", "data/interspeech-2025-eleventh-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-009.json",
    "data/interspeech-2025-twelfth-d3-papers.json", "data/interspeech-2025-twelfth-d3-notes.json", "data/interspeech-2025-twelfth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-010.json",
    "data/interspeech-2025-thirteenth-d3-papers.json", "data/interspeech-2025-thirteenth-d3-notes.json", "data/interspeech-2025-thirteenth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-011.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-013.json",
    "data/interspeech-2025-semantic-reviewed-d2-batch-014.json",
    "data/interspeech-2025-fourteenth-d3-papers.json", "data/interspeech-2025-fourteenth-d3-notes.json", "data/interspeech-2025-fourteenth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-012.json",
    "data/interspeech-2025-fifteenth-d3-papers.json", "data/interspeech-2025-fifteenth-d3-notes.json", "data/interspeech-2025-fifteenth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-013.json",
    "data/interspeech-2025-sixteenth-d3-papers.json", "data/interspeech-2025-sixteenth-d3-notes.json", "data/interspeech-2025-sixteenth-claim-ledger.json", "data/interspeech-2025-semantic-reviewed-d3-batch-014.json",
    "data/interspeech-2025-representative-papers.json",
    "data/interspeech-2025-d3-notes.json",
    "data/interspeech-2025-claim-ledger.json",
    "data/interspeech-2025-second-d3-papers.json",
    "data/interspeech-2025-second-d3-notes.json",
    "data/interspeech-2025-second-claim-ledger.json",
    "data/interspeech-2025-paper-evidence.jsonl",
    "data/interspeech-2025-artifact-ledger.json",
    "data/interspeech-2025-artifact-access-audit.json",
    "data/speech-artifact-execution-attempts.json",
    "data/interspeech-2025-review-queue.json",
    "data/interspeech-2025-execution-audit.json",
    "data/icassp-interspeech-crosswalk.json",
    "reports/INTERSPEECH_2025_FIRST_PASS.md",
    "reports/INTERSPEECH_2025_SEMANTIC_REVIEW_QUEUE.md",
    "reports/SPEECH_CORPUS_SEMANTIC_ASSIGNMENTS.md",
    "reports/SPEECH_SEMANTIC_REVIEW_GAPS.md",
    "reports/SPEECH_ATLAS_INDEX.md",
    "reports/SPEECH_BASELINE_FIRST_PRINCIPLES.md",
    "reports/SPEECH_FIRST_PRINCIPLES_TAXONOMY.md",
    "reports/SPEECH_ORGANIC_TAXONOMY_PROPOSAL.md",
    "reports/SPEECH_FIRST_PRINCIPLES_WRITEUP_AUDIT.md",
    "reports/SPEECH_PAPER_ANALYSIS_QUALITY_AUDIT.md",
    "reports/SPEECH_TAXONOMY_READJUDICATION_QUEUE.md",
    "reports/SPEECH_FIRST_PRINCIPLES_THEME_WRITEUPS.md",
    "reports/ICASSP_2026_SEMANTIC_REVIEW_QUEUE.md",
    "reports/ICASSP_2026_PAPER_EVIDENCE.md",
    "reports/SPEECH_FIRST_PRINCIPLES_SEED_SYNTHESIS.md",
    "reports/SPEECH_SUBTHEME_SYNTHESES.md",
    "reports/SPEECH_CONCEPT_FAMILY_CROSSWALK.md",
    "reports/SPEECH_CONCEPT_EVIDENCE_GAPS.md",
    "reports/SPEECH_FIRST_PRINCIPLES_READING_PATHS.md",
    "reports/INTERSPEECH_2025_DEEP_PAPER_ANALYSES.md",
    "reports/INTERSPEECH_2025_EVALUATION_AUDIT.md",
    "reports/INTERSPEECH_2025_THIRD_D3_NOTES.md",
    "reports/INTERSPEECH_2025_FOURTH_D3_NOTES.md",
    "reports/INTERSPEECH_2025_FIFTH_D3_NOTES.md",
    "reports/INTERSPEECH_2025_SEVENTH_D3_NOTES.md",
    "reports/INTERSPEECH_2025_REPRESENTATIVE_NOTES.md",
    "reports/ICASSP_2026_INTERSPEECH_2025_CROSSWALK.md",
    "reports/INTERSPEECH_2025_EXECUTION_AUDIT.md",
    "reports/INTERSPEECH_2025_SECOND_D3_NOTES.md",
    "reports/INTERSPEECH_2025_SEVENTEENTH_D3_NOTES.md",
    "reports/INTERSPEECH_2025_EIGHTEENTH_D3_NOTES.md",
    "reports/INTERSPEECH_2025_NINETEENTH_D3_NOTES.md",
    "reports/INTERSPEECH_2025_TWELFTH_D3_NOTES.md",
    "data/speech-atlas-completion-audit.json",
    "reports/SPEECH_ATLAS_COMPLETION_AUDIT.md",
]
FILES += [
    str(path.relative_to(HERE))
    for directory in (HERE / "data/interspeech-2025-pdfs", HERE / "data/interspeech-2025-text")
    for path in sorted(directory.glob("*"))
]
FILES += [
    name for name in (
        "ingest_icassp.py", "build_icassp_source_manifest.py", "ingest_interspeech.py", "mine_interspeech.py", "build_interspeech_report.py",
        "build_representative_papers.py", "build_d3_notes_report.py", "build_claim_ledger.py", "build_second_d3_set.py", "build_second_d3_reports.py", "build_paper_evidence.py",
        "build_artifact_ledger.py", "build_execution_audit_report.py", "build_cross_venue_synthesis.py",
        "build_review_queue.py", "build_completion_audit.py", "build_release_manifest.py", "rebuild_speech_atlas.py", "verify_speech_atlas.py",
    ) if (HERE / name).exists()
]

rows = []
for name in FILES:
    path = HERE / name
    raw = path.read_bytes()
    rows.append({"path": name, "bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest()})

payload = {"release_id": "speech-icasp-interspeech-2025-r1", "artifact_count": len(rows), "artifacts": rows}
out = HERE / "data/speech-atlas-release-manifest.json"
out.write_text(json.dumps(payload, indent=2) + "\n")
print(json.dumps({"release_id": payload["release_id"], "artifact_count": len(rows), "output": str(out)}))
