"""Write notes for D3 batch 060."""
import json
from pathlib import Path
HERE=Path(__file__).resolve().parent; DATA=HERE/"data"; REPORTS=HERE/"reports"
C={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-sixtieth-d3-papers.json").read_text())["papers"]}; P={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-papers.json").read_text())["papers"]}
N={
"itani25_interspeech":("listening-and-separation","source-separation-and-spatial-listening","target-conditioned-separation","A listener should extract a desired speech source from a mixture when ordinary separation assumptions are insufficient.","Target identity, mixture variability, and human preference can disagree with signal-level objectives.","Use an unconditioned separator and assume the loudest or most separable source is the desired one.","Use human feedback to guide neural speech extraction toward the target source.","Human preference supplies a target-selection signal alongside acoustic separation; the model is evaluated on extraction behavior.","Separation is not only signal recovery: the system must specify which source counts as useful to a listener.","The paper reports neural speech extraction with human feedback.","Feedback population, mixture construction, target definition, signal metrics, and model scope bound transfer."),
"kamper25_interspeech":("voice-generation-and-control","voice-identity-and-conversion","voice-conversion","Voice conversion should transform a speaker's voice while preserving linguistic content and remain useful with limited target data.","Self-supervised features encode both content and identity, so a simple transform can leak source traits or distort words.","Copy nearest target embeddings or train a separate waveform model per speaker.","Study linear transformations of self-supervised features as a controlled voice-conversion mechanism.","A learned transformation maps representation distributions toward a target voice while retaining content-related structure.","Conversion is a representation-space mapping: content preservation and target identity are competing constraints.","The paper reports LinearVC results through the lens of self-supervised feature transformations.","Feature model, languages, target data, similarity/content metrics, and transform assumptions bound transfer."),
"gao25f_interspeech":("languages-accents-and-resources","accent-and-cultural-boundaries","accent-robustness","A multilingual ASR system should handle accents and varieties without treating one pronunciation norm as universal.","Accent variation changes acoustic-to-word evidence and can interact with language and speaker identity.","Train or evaluate only on standard speech and report one pooled error rate.","Analyze accent robustness under multilingual conditions and identify where recognition errors reflect a narrow training norm.","Subgroup and accent-conditioned evaluation separates intended-word performance across varieties rather than hiding failures in an aggregate.","Robustness is a boundary measurement: the system's norm becomes visible only when varieties are evaluated separately.","The paper reports a study of multilingual/accent robustness and its implications for ASR evaluation.","Accent labels, languages, speakers, test design, and subgroup denominators bound transfer."),
}
FIELDS=[("bp","Ordinary problem"),("wh","Why hard"),("naive","Naive attempt"),("ap","Central move"),("mech","Mechanism"),("math","Mathematical/conceptual structure"),("ww","What paper reports"),("limits","Limits")]
def main():
 notes=[]; claims=[]; md=["# INTERSPEECH 2025 sixtieth-pass full-paper notes","","Three genuinely uncaptured readings raise the remaining source-separation, voice-conversion, and accent-boundary families.",""]
 for i,(pid,v) in enumerate(N.items(),1):
  theme,sub,concept,*vals=v; p,c=P[pid],C[pid]; bp,wh,naive,ap,mech,math,ww,limits=vals
  n={"paper_id":pid,"title":p["title"],"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"eval":math,"ww":ww,"limits":limits,"dots":{"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"sibling_family":"batch-060"},"source":{"kind":"official-isca-archive-paper-page-plus-captured-pdf-text","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"pdf_path":f"data/interspeech-2025-pdfs/{pid}.pdf","text_path":c["full_text_path"]},"depth":"D3","evidence_boundary":"D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}; notes.append(n); claims.append({"claim_id":f"IS25-D3C60-{i:02d}","paper_id":pid,"subtheme":sub,"claim":ww,"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":limits}); md += [f"## {i}. {sub}","",f"**Paper:** [{p['title']}]({p['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]+[f"- **{label}:** {n[key]}" for key,label in FIELDS]+[""]
 (DATA/"interspeech-2025-sixtieth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n"); (DATA/"interspeech-2025-sixtieth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n"); REPORTS.mkdir(exist_ok=True); (REPORTS/"INTERSPEECH_2025_SIXTIETH_D3_NOTES.md").write_text("\n".join(md)+"\n"); print(json.dumps({"notes":len(notes),"claims":len(claims)}))
if __name__=="__main__": main()
