#!/usr/bin/env python3
"""Write bounded, first-principles notes for the seventeenth D3 pass."""
import json
from pathlib import Path
H=Path(__file__).resolve().parent; D=H/"data"; R=H/"reports"
C={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-seventeenth-d3-papers.json").read_text())["papers"]}
P={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-papers.json").read_text())["papers"]}
N={
"dai25b_interspeech":("A separator should isolate the speaker a user describes, even when the enrollment recording or direction cue is unavailable.","Fixed categories such as male/female or high/low pitch lose information and do not expand cleanly across languages and rooms.","Treat every attribute as a fixed class or use only one cue such as gender.","Describe the target relative to the interfering speaker, then combine relative cues and pretrained speech representations in a text-conditioned extractor.","Two-speaker mixtures are built across five languages with cues for language, gender, emotion, order, age, rate, duration, pitch, loudness, and distance; prompts identify the target by those relations.","The central object is not a speaker label but a relation between two signals. Extraction quality is measured after the text selects one member of the mixture.","The paper reports that all relative cues beat random subsets, with gender and temporal order especially robust across languages and reverberation; WavLM/CNN initialization improves the baseline.","The claim is bounded to the constructed mixtures, cue templates, languages, and author-reported tests; real conversational mixtures and privacy effects remain open."),
"fujita25_interspeech":("Zero-shot TTS can imitate a voice while failing to control the subtle qualities listeners perceive as bright, dark, tense, or warm.","Speaker identity and impression are entangled, and a text description alone is too coarse for fine control.","Add a style token or manually search a latent vector for every speaker.","Represent impression as a small vector of antonym-pair intensities, remove it from the speaker representation, and reinsert the requested values at synthesis time.","The method trains a control module around FastSpeech2, uses subjective ratings to estimate impression vectors, and uses a language model to turn descriptions into those vectors.","A generated utterance is judged on two axes: whether it preserves the reference speaker and whether the requested impression moves in the intended direction. The dimensions are correlated, so independent sliders are an approximation.","Objective and subjective tests report effective single-dimension impression control and language-generated vectors that avoid manual optimization.","The evidence is limited to the selected impression dimensions, speakers, ratings, and TTS model; listener consistency and cross-language control are not established."),
"hannan25_interspeech":("A system should decide whether a face and a voice belong together when the person or video is unfamiliar, without relying on hand-tuned negative examples.","Face and voice embeddings live in different spaces; margins and mined negatives can make association depend on arbitrary training choices.","Use a contrastive or triplet loss with a fixed distance margin and assume the two modalities align after ordinary fusion.","Align the modalities with orthogonality constraints and gated feature fusion in a joint hyperbolic space, where hierarchy-like distances can represent identity similarity.","The two branches extract pretrained face and voice features, fuse them, and optimize a combination of association, orthogonality, and hyperbolic objectives on VoxCeleb1.","Verification asks whether a pair matches, while AUC and EER expose different threshold behavior. Seen-heard and unseen-unheard splits test whether the association survives new videos and people.","On the reported VoxCeleb1 splits, PAEFF improves the best listed baseline on unseen-unheard EER and reaches the highest or near-highest AUC in the table.","The result is author-reported and tied to VoxCeleb1, its split protocol, pretrained encoders, and hyperparameters; it does not establish robustness to dubbing, adversarial pairing, or other cultures."),
"makishima25b_interspeech":("In an overlapping conversation, understanding requires assigning each word and time interval to the correct face, not merely producing a bag of words.","A pipeline that separately separates speech, detects active speakers, and recognizes speech accumulates interfaces and errors.","Run single-talker ASR or chain independent separation, lip-motion detection, and transcription modules.","Train one encoder-decoder to emit a serialized sequence containing speaker tags, timing structure, and words from overlapped audio plus all visible faces.","The model combines speech and video encoders with Transformer decoding; evaluation compares it with single-talker, multi-talker, and modular audio-visual baselines on LRS3-derived mixtures.","WER measures words, TER measures which face spoke when, and VWER charges a word error when the speaker tag is wrong even if another transcript is correct. This makes attribution part of recognition.","The proposed model reports lower or competitive WER/VWER and strong VTER as the number of overlapping speakers rises, with tags placed before or after each transcription tested explicitly.","The evidence is bounded to constructed LRS3 mixtures, visible faces, tested overlap counts, and author-reported metrics; natural meetings, missed faces, and long-range turn structure remain open."),
}
keys=["bp","wh","naive","ap","mech","math","ww","limits"]; notes=[]; claims=[]; md=["# INTERSPEECH 2025 seventeenth-pass full-paper notes","","Four additional official-PDF readings deepen separation, expressive synthesis, cross-modal grounding, and overlapping-speech attribution. Results are author-reported and not independently reproduced.",""]
for i,(pid,vals) in enumerate(N.items(),1):
 d=dict(zip(keys,vals)); d.update({"paper_id":pid,"title":P[pid]["title"],"subtheme":C[pid]["subtheme"]}); notes.append(d)
 md += [f"## {i}. {d['subtheme']}","",f"**Paper:** [{d['title']}]({P[pid]['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{C[pid]['pdf_sha256']}`; {C[pid]['page_count']} pages.",""]
 for key,label in zip(keys,["Ordinary problem","Why hard","Naive attempt","Central move","Mechanism","Conceptual structure","What paper reports","Limits"]): md += [f"- **{label}:** {d[key]}"]
 md += [""]; claims.append({"claim_id":f"IS25-D3C17-{i:02d}","paper_id":pid,"subtheme":d["subtheme"],"claim":d["ww"],"evidence_depth":"D3","pdf_sha256":C[pid]["pdf_sha256"],"full_text_sha256":C[pid]["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":d["limits"]})
(D/"interspeech-2025-seventeenth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(D/"interspeech-2025-seventeenth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
R.mkdir(exist_ok=True); (R/"INTERSPEECH_2025_SEVENTEENTH_D3_NOTES.md").write_text("\n".join(md)+"\n")
print(json.dumps({"notes":len(notes),"claims":len(claims)}))
