"""Write first-principles notes for D3 batch 050."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPORTS = HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftieth-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

N = {
"schouwenaars25_interspeech": ("people-variation-and-health", "human-centered-evaluation", "accessibility-fit", "A listener using a cochlear implant or a simulated cochlear implant must recover grammatical structure from a spectrally degraded speech signal.", "The signal degradation can remove cues that distinguish subject, object, and passive questions, while working memory and grammatical case interact with what the listener can use.", "Assume that good performance on normal speech transfers unchanged to the simulated implant condition.", "Compare normal and CI-simulated speech with eye-tracking, accuracy, and working-memory measures so evaluation reflects both the answer and the listener's processing path.", "German adults answer subject, object, and passive which-questions. Eye movements and response accuracy expose whether case and subject-verb agreement cues survive the simulation; mixed-effects analyses relate performance to working memory.", "Accuracy and gaze behavior are behavioral proxies for comprehension; the comparison is between normal and CI-simulated acoustic conditions rather than between two recognition models.", "Only object-question accuracy was affected by the simulation, with weaker interpretation preferences in gaze patterns; higher working memory was associated with better accuracy and faster reorientation.", "The simulation is not an actual implant, the German grammatical system and question types are narrow, and listener behavior does not establish clinical device benefit or general speech recognition performance."),
"merzougui25_interspeech": ("people-variation-and-health", "human-centered-evaluation", "accessibility-fit", "A blind or visually impaired reader needs to skim a structured web document without relying on a visual page layout.", "Transposing headings, roles, and relationships into sound can overload serial listening; the interface must preserve structure while allowing rapid selective attention.", "Read the page linearly from top to bottom or emit every element with equal salience.", "Represent document semantics as an interactive auditory tag cloud, using concurrent speech and spatial/continuous auditory guidance to let the listener scan and select structure.", "TagThunder extracts morpho-dispositional semantics and maps tags to concurrent speech streams and guiding stimuli; discrete and continuous interaction conditions test structured information scanning.", "The system treats auditory channels as a limited display: timing, concurrency, and user selection determine which semantic items are attended rather than merely transcribed.", "The paper presents the experimental framework and reports feasibility for non-visual web skimming through auditory tag-cloud interaction.", "The evaluation is interaction-specific, auditory clutter and learning effects matter, and accessibility promise is not equivalent to demonstrated performance across blind users, browsers, languages, or real browsing tasks."),
"duraisamy25_interspeech": ("sound-and-production", "time-frequency-measurement", "multi-resolution-signal", "A brain-computer interface may need to distinguish imagined or covert speech when no acoustic waveform is available.", "EEG varies across trials, words, affective states, and people; phase and connectivity information can be lost when the signal is reduced to a single amplitude feature.", "Train one subject-specific classifier on raw EEG and assume its spectral pattern transfers to another speaker.", "Represent covert speech with Hilbert envelopes, instantaneous phase, and functional connectivity across frequency bands, then train a subject-independent sequence classifier.", "Phase Locking Value and coherence summarize coordination among EEG channels. Band-specific Hilbert features feed a BiLSTM, while inter-trial, inter-class, and inter-subject analyses separate stable structure from variability.", "The features are functions of analytic-signal phase and amplitude; classification accuracy measures whether the learned representation separates five speech-command categories across subjects.", "The reported subject-independent model reaches 59.14% accuracy across five covert-speech categories and reveals both shared and class-specific connectivity patterns.", "Covert speech EEG is not ordinary spoken audio, sample and subject variability constrain the result, class accuracy is not communicative utility, and no independent execution was performed."),
"fan25_interspeech": ("sound-and-production", "time-frequency-measurement", "multi-resolution-signal", "Infant-worn recordings contain long, varied home soundscapes in which infant vocalizations and caregiver interaction must be recognized with little labeled data.", "Events occupy different frequency bands and time scales, recordings are noisy and weakly annotated, and a single full-band representation can waste capacity on irrelevant variation.", "Learn one monolithic audio embedding or train a supervised model only on the small labeled set.", "Split the spectrum into bands, learn band-specific projections, and let a band-agnostic Mamba encoder model temporal relations while self-supervised pretraining uses unlabeled in-domain audio.", "Band-specific features preserve local spectral evidence while the state-space sequence model carries information over time; self-supervised and supervised objectives share the representation before downstream classification.", "The system compares classification and representation-learning performance under limited labels, with band ablations testing whether multi-resolution structure matters.", "BS-SSAMBA improves infant-centered audio analysis in the reported experiments and benefits from combining unlabeled in-domain audio with limited annotations.", "Infant audio is adjacent to, not identical with, human speech; task labels, home environments, class balance, and domain-specific data bound transfer to adult speech systems."),
"khanday25_interspeech": ("sound-and-production", "room-channel-and-sensing", "non-airborne-sensing", "Neural recordings during speech production contain information about linguistic and acoustic planning before or alongside the sound that reaches a microphone.", "High-gamma activity is spatially and temporally structured, while model embeddings compress speech and language differently; a useful embedding must preserve the neural dynamics rather than just correlate with a label.", "Predict neural activity from word IDs or a generic acoustic feature and ignore timing, cortical location, and representational level.", "Use pretrained language and speech-model embeddings as regressors for high-gamma activity, then compare how linguistic and acoustic representations reconstruct spatio-temporal neural signals.", "Embedding vectors are aligned to neural time windows and mapped to high-gamma responses; reconstruction quality is evaluated across electrodes, time, and representational sources.", "The paper treats a learned embedding as a hypothesis about what information is available to the brain, and reconstruction error/correlation as a test of that information's neural correspondence.", "Language and speech embeddings reconstruct measurable neural activity characteristics, with differences across model type and brain locations reported as evidence about linguistic versus acoustic information.", "Neural recordings, participant count, electrode coverage, alignment choices, and correlational reconstruction limit causal interpretation; a good reconstruction is not a speech decoder or clinical interface."),
"gupta25_interspeech": ("sound-and-production", "room-channel-and-sensing", "microphone-channel", "An earbud should make outside speech, horns, and alarms sound as if the ear were open, despite passive attenuation and changing fit or source direction.", "The filter must compensate a user- and direction-dependent acoustic path with low delay, while adaptive IIR filters can become unstable and FIR filters can be expensive.", "Use one fixed equalizer or a high-order adaptive FIR and accept mismatch, computation, or latency.", "Estimate a virtual sensing path and adapt a low-complexity IIR hear-through filter with stability-aware updates for different earbud fittings and directions.", "The virtual sensor models the sound pressure at the eardrum; an adaptive IIR filter updates the feedforward path, while constraints on poles/coefficients prevent unstable compensation. Indoor and outdoor acoustic simulations test convergence and delay.", "Mean-square error, SNR, filter complexity, and processing delay expose the trade-off between matching the open-ear response and maintaining real-time stability.", "The proposed low-complexity IIR method reports improved hear-through performance under practical constraints and reduced complexity relative to larger adaptive alternatives.", "The evidence is simulation-heavy and depends on acoustic-path and fitting assumptions; user listening, hardware latency, and individualized hearing benefit are not established."),
"han25_interspeech": ("listening-and-separation", "source-separation-and-spatial-listening", "speaker-separation", "A diarization system must assign speech segments to speakers in far-field meetings while fitting on hardware with limited memory and compute.", "Self-supervised encoders contain redundant parameters, but pruning too aggressively can destroy the representations needed when speakers overlap, reverberation is present, or microphones differ.", "Prune the pretrained encoder immediately and hope a small model preserves the full model's speaker boundaries.", "Fine-tune the self-supervised WavLM model on diarization before structured pruning, and use knowledge distillation to preserve the task behavior while removing redundant structure.", "The teacher supplies representations or logits for the student; structured channel/layer removal creates a compact model, and diarization error rate on far-field meeting corpora measures the retained segmentation and attribution ability.", "The central object is a constrained compression path: task adaptation changes which parameters matter before pruning, while distillation penalizes deviation from the adapted teacher.", "On AMI, AISHELL-4, and AliMeeting, the paper reports that fine-tuning before pruning improves the accuracy/size trade-off over pruning without that order.", "Dataset microphone layouts, pruning ratios, teacher/student settings, and DER's treatment of overlap bound the claim; compact diarization is not universal robustness or real-device validation."),
"mori25b_interspeech": ("meaning-and-interaction", "dialogue-and-turn-taking", "dialogue-state", "A spoken dialogue system can prepare a response before the user finishes, but a wrong early prediction can waste computation or create a visibly incorrect reply.", "The partial utterance is incomplete and ambiguous; latency savings matter only when the predicted completion is semantically close enough to the final utterance.", "Always prefetch from the current partial transcript or never prefetch until the user stops speaking.", "Predict the complete utterance early, estimate semantic similarity and confidence between the prediction and eventual utterance, and prefetch only when the confidence threshold makes the latency/rollback trade-off worthwhile.", "A prediction-confidence model compares embeddings or semantic representations of the predicted and completed user utterances; response latency and prediction correctness quantify when prefetching is safe.", "The decision is selective rather than binary: the system estimates expected utility under uncertainty, trading saved user-perceived latency against wrong-response risk.", "The paper reports that semantic-similarity confidence can reduce user-perceived latency while limiting unsafe prefetches in the tested spoken-dialogue setting.", "The language model, dialogue domain, confidence calibration, and endpointing assumptions constrain generalization; lower latency is not the same as better conversation or human trust."),
}

theme_for = {"sound-and-production": "sound-and-production", "people-variation-and-health": "people-variation-and-health", "listening-and-separation": "listening-and-separation", "meaning-and-interaction": "meaning-and-interaction"}
notes = []; claims = []; md = ["# INTERSPEECH 2025 fiftieth-pass full-paper notes", "", "Eight official-PDF readings deepen human-centered evaluation, time-frequency measurement, room/channel sensing, source separation, and dialogue latency.", ""]
for i, (paper_id, fields) in enumerate(N.items(), 1):
    theme, subtheme, concept, bp, wh, naive, ap, mech, math, ww, limits = fields
    p = papers[paper_id]; c = captured[paper_id]
    note = {"paper_id": paper_id, "title": p["title"], "theme_id": theme, "subtheme_id": subtheme, "concept_id": concept, "bp": bp, "wh": wh, "naive": naive, "ap": ap, "mech": mech, "math": math, "eval": math, "ww": ww, "limits": limits, "dots": {"theme_id": theme, "subtheme_id": subtheme, "concept_id": concept, "sibling_family": "batch-050"}, "source": {"kind": "official-isca-archive-paper-page-plus-captured-pdf-text", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "pdf_path": f"data/interspeech-2025-pdfs/{paper_id}.pdf", "text_path": c["full_text_path"]}, "depth": "D3", "evidence_boundary": "D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}
    notes.append(note)
    claims.append({"claim_id": f"IS25-D3C50-{i:02d}", "paper_id": paper_id, "subtheme": subtheme, "claim": ww, "evidence_depth": "D3", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "support_status": "paper-reported-not-independently-verified", "independent_support_status": "not-established", "limitations": limits})
    md += [f"## {i}. {subtheme}", "", f"**Paper:** [{p['title']}]({p['paper_url']})", f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.", ""]
    md += [f"- **{label}:** {note[key]}" for label, key in zip(["Ordinary problem", "Why hard", "Naive attempt", "Central move", "Mechanism", "Mathematical/conceptual structure", "What paper reports", "Limits"], ["bp", "wh", "naive", "ap", "mech", "math", "ww", "limits"])] + [""]
(DATA / "interspeech-2025-fiftieth-d3-notes.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "evidence_depth": "D3", "notes": notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-fiftieth-claim-ledger.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "claim_count": len(claims), "claims": claims}, indent=2, ensure_ascii=False) + "\n")
REPORTS.mkdir(exist_ok=True); (REPORTS / "INTERSPEECH_2025_FIFTIETH_D3_NOTES.md").write_text("\n".join(md) + "\n")
print(json.dumps({"notes": len(notes), "claims": len(claims)}))
