"""Write first-principles notes and claims for D3 batch 058."""
import hashlib, json
from pathlib import Path

HERE = Path(__file__).resolve().parent; DATA, REPORTS = HERE / "data", HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftyeighth-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}
N = {
 "yong25_interspeech": ("languages-accents-and-resources","adaptation-and-open-vocabulary","speaker-adaptation","Low-resource ASR should generalize to accents not represented in training data.","Speaker count, hours per speaker, and accent diversity are confounded when the total training budget is fixed.","Add hours from a few speakers and assume more accent labels alone will guarantee unseen-accent robustness.","Factor the training-data budget by speaker count, per-speaker duration, and accent diversity, then test zero-shot accents.","Controlled data-composition experiments compare ASR performance across unseen accents and languages.","Generalization is constrained by which speakers and accents supply the training evidence, not only by total audio hours.","The paper reports that more speakers help more than more hours per speaker, while accent-diversity gains are minimal under controlled speaker count.","Languages, accent labels, low-resource budgets, model/training choices, and zero-shot evaluation bound transfer; this is not a universal data-collection law."),
 "wepner25_interspeech": ("recognition-and-alignment","boundaries-and-sequence-structure","disfluency-preservation","Conversational ASR and human transcription should account for syntactic disfluencies and filler particles.","Pauses, repairs, pronunciation, and articulation rate interact, so a global WER can hide which local structures cause errors.","Collapse all disfluencies into fluent text or treat filler presence as the sole explanatory variable.","Present the same disfluent utterances to human listeners and multiple ASR systems, and compare error patterns across structure and acoustic factors.","The matched transcription experiment uses participant recall and ASR WER to compare shared difficulty patterns.","Disfluency is sequence evidence: preserving its position and type lets recognition error be related to conversational structure.","The paper reports similar difficulty characteristics for humans and ASR and no WER effect from filler presence alone.","54 listeners, nine systems, utterance design, languages, and WER/recall definitions bound transfer; matched error patterns do not establish cognitive equivalence."),
 "zhang25e_interspeech": ("sound-and-production","room-channel-and-sensing","reverberant-mixture","Spatial sound reproduction should reproduce speech perception measured in real rooms.","Measured room impulse responses contain a noise floor that can create artificial late energy and alter intelligibility in reverberant spaces.","Use any measured RIR or truncate it mechanically and assume the rendered room remains perceptually faithful.","Vary RIR noise floor and compare speech-in-noise listening in spherical-harmonic reproduction against the rooms where the RIRs were measured.","The RIR encodes direct and reflected paths; its residual floor changes the rendered reverberant tail, which is tested through intelligibility comparisons.","Room reproduction is a channel-matching problem: the measurement’s noise floor is part of the rendered evidence unless controlled.","The paper reports better reproducibility with low-noise-floor RIRs in highly reverberant rooms and at 5 m, while truncation usually did not help.","Rooms, source distances, RIR measurement, listening protocol, and speech-in-noise task bound transfer; perceptual reproducibility is not exact physical localization."),
 "shi25h_interspeech": ("people-variation-and-health","speaker-characteristics","age-and-development","ASR should adapt to individual child speakers at test time without requiring transcript annotations.","Children differ acoustically and linguistically from adult pretraining data and from one another, making a single child-domain correction insufficient.","Fine-tune once on a pooled child corpus or use an unadapted adult model for every child.","Apply unsupervised SUTA and SGEM test-time adaptation to off-the-shelf and child-fine-tuned ASR models and compare per-child results.","The adaptation updates model behavior from incoming child speech at inference time, without target transcripts, and is evaluated against unadapted baselines.","Personalization is an online evidence problem: each child supplies a changing acoustic distribution rather than a fixed domain label.","The paper reports average and per-child gains for both model types, with remaining limitations on non-linguistic child speech.","Child corpus, adaptation methods, update stability, model family, and evaluation conditions bound transfer; average WER gains are not proof of safe continual deployment."),
 "zhang25l_interspeech": ("sound-and-production","time-frequency-measurement","multi-resolution-signal","A 1.2 kbps speech codec should preserve intelligibility and quality under resource constraints.","Very-low-rate coding must preserve spectral envelope and waveform detail while avoiding the complexity of large end-to-end decoders.","Quantize conventional parameters more aggressively or use a high-quality neural codec whose compute and bitrate exceed the deployment budget.","Combine LSP-based parametric coding, direct neural sample prediction, and joint STFT/cross-entropy training in a hybrid LPCNet-style codec.","LSPs stabilize spectral-envelope quantization; the neural predictor models sample distributions; time-frequency losses jointly constrain local waveform and spectral behavior.","Codec design is a rate-distortion allocation across representations and resolutions, with complexity treated as a deployment constraint.","The paper reports high speech quality at 1.2 kbps and lower complexity than compared end-to-end codecs.","Datasets, bitrate, codec baselines, quality metrics, hardware, and real-time implementation bound transfer; reported quality is not proof for every channel or listener."),
 "nakagome25_interspeech": ("recognition-and-alignment","adaptation-and-open-vocabulary","domain-and-context-biasing","ASR should recognize rare contextual keywords without retraining whenever application vocabulary changes.","A fixed bias list can over-bias decoding, while conventional contextual biasing may miss keywords with variable or wildcard forms.","Retrain the recognizer for every keyword list or inject a static phrase list and accept false substitutions.","Use wildcard CTC keyword spotting and inter-layer biasing to add contextual evidence at inference time without retraining.","CTC keyword scores detect flexible keyword evidence; inter-layer bias signals steer decoding while retaining the base acoustic model.","Contextual biasing changes the prior over candidate words, so it must raise relevant rare words without overruling acoustic evidence.","The paper reports retraining-free contextual recognition improvements using WCTC-Biasing.","Keyword lists, wildcard design, domains, decoder thresholds, and test distributions bound transfer; contextual gains do not guarantee lower errors on arbitrary speech."),
 "oh25c_interspeech": ("recognition-and-alignment","boundaries-and-sequence-structure","long-context-decoding","Long-form ASR should use positional context without losing local acoustic alignment.","Cross-attention can attend to misplaced encoder positions, especially as utterances grow, causing errors that a generic language prior cannot diagnose.","Use unmodified cross-attention or force a hard monotonic alignment that cannot accommodate timing variation.","Add positional alignment to cross-attention at inference so attention scores favor acoustically corresponding positions during long-form decoding.","Position-aware attention reshapes the correspondence between decoder states and encoder frames without changing the recognized content target.","Long-context decoding is a soft alignment problem: context helps only when its evidence remains tied to the relevant time region.","The paper reports improved robust long-form recognition from inference-time positional alignment.","Model, long-form segmentation, positional formulation, decoding settings, and evaluation corpora bound transfer; reported robustness is not universal streaming reliability."),
 "ryu25b_interspeech": ("sound-and-production","room-channel-and-sensing","microphone-channel","A recognizer should tolerate microphone/device changes without collecting paired recordings for every device pair.","Device responses alter spectral evidence, and many-to-many conversion must preserve speech content while changing channel coloration.","Duplicate channels, apply generic stereo equalization, or train one converter separately for every source-target pair.","Learn a unified many-to-many microphone conversion model using feature-wise linear modulation to condition conversion on source and target devices.","FiLM parameters modulate intermediate features according to device identities, allowing one model to represent multiple channel mappings.","Device conversion is a conditional channel transformation: content is shared while microphone response is the variable being controlled.","The paper reports unified microphone conversion results across device mappings without paired examples for every target pair.","Device inventory, pairing protocol, training coverage, content preservation metrics, and acoustic conditions bound transfer; channel conversion is not the same as recognizer invariance."),
}
labels = [("Ordinary problem","bp"),("Why hard","wh"),("Naive attempt","naive"),("Central move","ap"),("Mechanism","mech"),("Mathematical/conceptual structure","math"),("What paper reports","ww"),("Limits","limits")]
notes=[]; claims=[]; md=["# INTERSPEECH 2025 fifty-eighth-pass full-paper notes","","Eight official-PDF readings deepen five previously lowest-coverage subthemes: adaptation, sequence boundaries, room/channel evidence, speaker variation, and time-frequency coding.",""]
for i,(pid,v) in enumerate(N.items(),1):
 theme,sub,concept,*vals=v; p,c=papers[pid],captured[pid]; bp,wh,naive,ap,mech,math,ww,limits=vals
 note={"paper_id":pid,"title":p["title"],"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"eval":math,"ww":ww,"limits":limits,"dots":{"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"sibling_family":"batch-058"},"source":{"kind":"official-isca-archive-paper-page-plus-captured-pdf-text","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"pdf_path":f"data/interspeech-2025-pdfs/{pid}.pdf","text_path":c["full_text_path"]},"depth":"D3","evidence_boundary":"D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}; notes.append(note)
 claims.append({"claim_id":f"IS25-D3C58-{i:02d}","paper_id":pid,"subtheme":sub,"claim":ww,"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":limits})
 md += [f"## {i}. {sub}","",f"**Paper:** [{p['title']}]({p['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]+[f"- **{a}:** {note[b]}" for a,b in labels]+[""]
(DATA/"interspeech-2025-fiftyeighth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(DATA/"interspeech-2025-fiftyeighth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
REPORTS.mkdir(exist_ok=True); (REPORTS/"INTERSPEECH_2025_FIFTYEIGHTH_D3_NOTES.md").write_text("\n".join(md)+"\n"); print(json.dumps({"notes":len(notes),"claims":len(claims)}))
