#!/usr/bin/env python3
import json
from pathlib import Path
H=Path(__file__).resolve().parent; D=H/"data"; R=H/"reports"
C={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-twelfth-d3-papers.json").read_text())["papers"]}
P={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-papers.json").read_text())["papers"]}
N=[
("sound-and-production/source-filter-production","dindart25_interspeech","Vocal-fold vibration is physical motion that a microphone observes indirectly; ultrasound may measure the motion itself.","Ultrasound has spatial and temporal limits, and frequency estimates can alias when the voice is faster than acquisition.","Treat waveform pitch as the only description of vocal-fold motion.","Use M-mode ultrasound along the larynx and compare its fundamental-frequency estimate with simultaneous voice analysis.","Spatio-temporal maps of the fundamental and second harmonic are compared with median f0 from recordings.","A linear fit gives f0-US = 0.997 f0-voice + 0.293 with correlation 0.999; differences are below 2 Hz in 92% of recordings.","The source/filter question becomes a sensing question: the vocal source can be observed through a different physical projection.","The paper reports close agreement and reveals temporal drift; four high-pitched recordings expose aliasing.","The 500-Hz rate, probe placement, healthy participants, and excluded aliased cases limit clinical and high-pitch claims."),
("listening-and-separation/echo-and-reconstruction","cohen25_interspeech","When speech is inpainted, several completions may fit the observed context, so uncertainty is part of the missing-sound problem.","A single plausible waveform hides whether the missing content was determined by the evidence.","Return one deterministic reconstruction and treat residual error as the only uncertainty signal.","Use Neural Principal Probability Components to represent the posterior over possible inpaintings and compare it with dropout sampling.","NPPC predicts principal components of the conditional output distribution; traversing components produces alternative spectrograms and transcripts.","NPPC is reported as 50x faster than 50-sample MC Dropout with slightly better reconstruction error.","The output is a distribution over repairs, not a single answer; uncertainty changes both sound and what ASR hears.","Principal directions change word identity and pitch; NPPC captures diverse outputs while matching or improving dropout error.","The data, posterior approximation, audio examples, and benchmark define the result; calibration and user decision rules remain unresolved."),
("recognition-and-alignment/acoustic-unit-mapping","deheerkloots25_interspeech","A speech representation can encode phonetic and word information differently across languages and speaking styles.","Probe accuracy, downstream ASR, and corpus match can disagree, so one score cannot establish what a representation knows.","Use a multilingual representation as language-neutral and judge it by one WER.","Compare English, multilingual, and Dutch self-supervised models with linguistic probes and downstream Dutch ASR across read and conversational speech.","Hidden layers are probed for phonetic and lexical structure, then models are fine-tuned and evaluated on five Dutch test sets.","The Dutch model WERs are 10.4 CGN-o, 65.6 IFADV, 15.4 MLS, 21.0 CV, and 25.2 N-Best; English is consistently worse.","Representation quality depends on language and pretraining domain: conversation-trained data helps conversational structure and recognition.","Language-specific pretraining yields lower WER, while probe and fine-tuning rankings need not coincide.","Models, Dutch corpora, probes, and fine-tuning limit generalization; decodability is not causal proof of ASR behavior."),
("meaning-and-interaction/dialogue-and-turn-taking","cavalcanti25_interspeech","Turn timing is jointly produced by two people; one speaker can wait differently with different partners and topics.","A model that sees only preceding words misses dyad-specific habits, common ground, and social coordination.","Predict a boundary from current-speaker features and treat talkers as independent.","Measure transition-floor offset across dyads and model individual, demographic, topic, and pair-specific effects hierarchically.","Spontaneous English dyads are analyzed by mixed models separating individual idiosyncrasy from dyad-specific interaction.","Marginal R2 and random-effects comparisons show dyadic effects dominate the reported variation.","Turn-taking is interactional state, not merely a local acoustic event; the pair is a meaningful unit.","Sex and age have smaller effects while dyad variation most strongly shapes timing; TFO decreases across sampled lifespan.","English strangers, sparse older data, topic mix, and TFO limit familiar-relationship and full-dialogue claims."),
("voice-generation-and-control/text-to-speech-and-content","zalkow25_interspeech","Low-resource TTS can have correct content but unnatural acoustic detail, so postprocessing must improve naturalness without changing speech.","The target has little data, objective distances are listening proxies, and a postprocessor can improve one aspect while harming prosody.","Train a large TTS model directly on the small speaker set or add noise and assume naturalness follows.","Generate training examples from high-resource speakers and train GAN or consistency-flow postprocessors selected for low-resource targets.","Forward Tacotron features are refined by GAN and CFM postprocessors, then compared with listening and ranking tests.","Proposed CFM reaches objective distance 0.27; listener scores are 79.8 proposed CFM and 74.8 proposed GAN versus reference 98.3.","Postprocessing separates generation from naturalness repair, but the metric must still be checked against listeners.","Both proposed postprocessors improve reported naturalness; the CFM gain over its standard version is not significant.","Two speakers, ground-truth prosody in part of evaluation, selected data, and reported tests limit arbitrary-voice claims."),
("people-variation-and-health/speaker-characteristics","griot25_interspeech","Speaker verification must decide identity while content may be the same or different, without confusing lexical matching with speaker evidence.","Text-independent and text-dependent trials expose different shortcuts; a representation helping one can fail when phrase content changes.","Train separate systems for every language and treat verification as one undifferentiated score.","Use a unified self-supervised student for text validation and speaker verification, then evaluate tandem decisions across multilingual trials.","The student preserves lexical information for text validation while a speaker backend supplies identity evidence; DeepMine and VoxCeleb1 test both modes.","English DeepMine TD-SV tandem EER is 3.46% versus 4.28% baseline; VoxCeleb1 TI-SV is 1.29% versus 0.49%, exposing a tradeoff.","Identity evidence is entangled with lexical content unless trial design forces separation.","The student improves reported text-dependent and DeepMine results but degrades VoxCeleb1 text-independent results relative to ReDimNet.","Datasets, languages, content, thresholds, and reported EERs bound the conclusion; open-set deployment is unestablished."),
("languages-accents-and-resources/multilingual-and-crosslingual","yan25c_interspeech","Code-switched speech alternates languages within an utterance, so recognition must switch language and script expectations without losing context.","Whisper behavior differs sharply on code-switched speech, especially across scripts; synthetic speech may add artifacts.","Train on monolingual data and expect multilingual modeling to interpolate automatically.","Build CS-FLEURS across 52 languages and 113 pairs, compare real and synthetic controls, and add synthetic code-switched training data.","The corpus controls pair and switching conditions; experiments compare CER, direct translation, script pairs, and augmented training.","Distinct-script CER is about 3x same-script CER; synthetic training lowers reported seen CER 14.38 to 12.67 and unseen 29.62 to 27.77.","Cross-lingual recognition is a switching problem in language and writing system; data design determines the failure measured.","Code-switched ASR is over twice as errorful as monolingual speech, while synthetic training improves seen and unseen pairs.","Language pairs, synthetic voices, Whisper, CER, and controlled read speech limit natural-conversation claims."),
("evaluation-deployment-and-consequence/metrics-and-targets","phukon25_interspeech","A transcript can differ from reference words yet remain understandable, especially for disordered speech; evaluation must measure recoverable meaning.","WER and CER penalize harmless substitutions and can reward exact but unintelligible text.","Use WER as the universal speech-quality measure because it is easy to compute.","Fit a metric combining natural-language inference, semantic similarity, and phonetic similarity to human ratings of ASR outputs.","Five-fold regression learns weights from 100 transcript pairs rated by six annotators, then tests the combined score against held-out judgments.","The combined metric correlates 0.890 with human judgments; weights are 0.40 NLI, 0.28 semantic, and 0.32 phonetic, with MSE 0.237.","A metric is a model of the human target: choosing the target changes which errors count as failures.","The integrated measure outperforms individual and traditional error measures in the reported SAP evaluation.","One dataset, six annotators, regression assumptions, and reported correlation limit other listeners, languages, and clinical decisions.")]
F=[("bp","Big picture"),("wh","Why hard"),("naive","Naive attempt"),("ap","Central move"),("mech","Mechanism"),("math","Mathematical idea"),("dots","Connections"),("ww","What paper reports"),("limits","Limits")]
notes=[]; out=["# INTERSPEECH 2025 twelfth-pass full-paper notes","","Eight official-PDF analyses target concepts with thin full-paper coverage. Results remain author-reported and were not independently reproduced.",""]; claims=[]
for row in N:
 d=dict(zip(["subtheme","paper_id","bp","wh","naive","ap","mech","math","dots","ww","limits"],row)); notes.append(d); p,cap=P[d["paper_id"]],C[d["paper_id"]]
 out += [f"## {len(notes)}. {d['subtheme']}","",f"**Paper:** [{p['title']}]({p['paper_url']})  ",f"**Evidence:** D3; PDF SHA-256 {cap['pdf_sha256']}; {cap['page_count']} pages.",""]+[f"- **{lab}:** {d[key]}" for key,lab in F]+[""]
 claims.append({"claim_id":f"IS25-D3C12-{len(notes):02d}","paper_id":d["paper_id"],"subtheme":d["subtheme"],"claim":d["ww"],"evidence_depth":"D3","pdf_sha256":cap["pdf_sha256"],"full_text_sha256":cap["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":d["limits"]})
(D/"interspeech-2025-twelfth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(D/"interspeech-2025-twelfth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
(R/"INTERSPEECH_2025_TWELFTH_D3_NOTES.md").write_text("\n".join(out)+"\n")
print(json.dumps({"notes":len(notes),"report":"reports/INTERSPEECH_2025_TWELFTH_D3_NOTES.md"}))
