"""Write notes for the nine genuinely uncaptured papers in D3 batch 059."""
import json
from pathlib import Path
HERE=Path(__file__).resolve().parent; DATA=HERE/"data"; REPORTS=HERE/"reports"
CAP={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-fiftyninth-d3-papers.json").read_text())["papers"]}
PAP={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-papers.json").read_text())["papers"]}
N={
"grinberg25_interspeech":("sound-and-production","time-frequency-measurement","windowed-spectrum","Audio deepfake explanations should show which changing acoustic evidence led to a detector's decision.","A global score hides local spectral events and can appear interpretable without exposing evidence.","Point to an arbitrary waveform segment or global saliency map and call it an explanation.","Relate detector decisions to localized time-frequency structure with a data-driven explanation model.","A spectro-temporal explanation connects model output to changing acoustic regions.","The paper reports a diffusion approach for explaining neural audio deepfake decisions.","Deepfake types, explanation faithfulness, model family, and listener interpretation bound transfer."),
"dong25_interspeech":("listening-and-separation","noise-enhancement","speech-prior-denoising","Speech-perception training should expose listeners to realistic multitalker babble with a measurable learning target.","Babble masks cues differently from stationary noise, so SNR alone may not represent daily listening.","Train with clean speech or one stationary noise and assume transfer to conversation.","Compare human vowel-perception training with multitalker babble against neural-model responses.","Babble context is manipulated and perceptual/model error patterns are compared.","The paper reports a comparison of human and neural-model responses in multitalker babble.","Listeners, babble construction, vowel contrasts, training duration, and model architecture bound transfer."),
"alcalapadilla25_interspeech":("listening-and-separation","source-separation-and-spatial-listening","spatial-filtering","A hearing-aid listener should extract a desired talker using where the sound comes from.","Target and interferer overlap in frequency and may move while hearing aids provide limited spatial evidence.","Use a fixed beamformer or spectral mask without conditioning on target location.","Make target location explicit in a location-aware target-speaker extraction model.","Spatial features condition separation toward the selected direction.","The paper reports location-aware target-speaker extraction for hearing-aid scenarios.","Array geometry, motion, layout, processing, and intelligibility metric bound transfer."),
"elkheir25b_interspeech":("recognition-and-alignment","acoustic-unit-mapping","acoustic-to-token","Qur'anic-recitation pronunciation assessment needs labels that map acoustic deviations to meaningful learner errors.","Specialized phonology and pronunciation norms make generic ASR labels insufficient.","Apply a general ASR benchmark or one pronunciation distance without task-specific labels.","Construct a unified Arabic pronunciation-assessment benchmark around Qur'anic recitation.","Audio, pronunciation targets, and assessment labels are aligned for model comparison.","The paper presents a benchmark and case study for Arabic pronunciation assessment.","Recitation tradition, annotation, coverage, and metrics bound transfer; automatic scores are not teacher judgment."),
"akti25_interspeech":("voice-generation-and-control","voice-identity-and-conversion","voice-conversion","Zero-shot expressive voice conversion should change style while preserving content and identity for unseen voices.","Content, identity, and style are entangled, and known-speaker training encourages shortcuts.","Use one entangled vector or train a separate converter for every target speaker.","Improve disentanglement in non-autoregressive zero-shot expressive voice conversion.","Content, speaker, and expressive factors are separated in a non-autoregressive generation path.","The paper reports improved disentanglement for zero-shot expressive conversion.","Enrollment, labels, languages, metrics, and unseen-speaker protocol bound transfer."),
"goebiowska25_interspeech":("people-variation-and-health","speaker-characteristics","speaker-verification","Speaker verification should remain reliable when emotional state changes the same person's voice.","Emotion changes pitch, timing, energy, and voice quality and can cross identity thresholds.","Enroll and test only neutral speech or treat emotional recordings as different identities.","Build emotion-aware speaker verification and test identity evidence across affective states.","The verifier separates speaker-consistent structure from emotion-dependent variation.","The paper presents EmoSpeechAuth and evaluates emotion-aware speaker verification.","Emotion labels, speakers, channel, enrollment, thresholds, and demographics bound transfer."),
"du25b_interspeech":("people-variation-and-health","human-centered-evaluation","listener-effort","An emotion-aware speech model should combine audio and context without confusing fluent output with reliable affect recognition.","Emotion is ambiguous and context-dependent; language models can generate plausible unsupported explanations.","Use one label stream or infer emotion from transcripts alone.","Use dual cross-attention and context-aware instruction tuning for emotion-aware audio-language modeling.","Cross-attention aligns acoustic and conversational representations.","The paper reports EAA results for emotion-aware audio large language modeling.","Labels, prompts, audio quality, model, and human agreement bound transfer."),
"amoniyan25_interspeech":("languages-accents-and-resources","accent-and-cultural-boundaries","accent-robustness","Multilingual speech analysis should distinguish pronunciation patterns from racialized assumptions about speakers.","The same segment can be interpreted differently across languages and communities.","Assign one standard target or explain variation through race as a direct cause.","Cross-examine /s/ production in a multilingual Nigerian context using linguistic and social context.","Acoustic realization is interpreted alongside multilingual context rather than one norm.","The paper reports a contextual analysis of /s/ in a multilingual Nigerian setting.","Community, language, sampling, annotation, and interpretation bound transfer."),
"fang25c_interspeech":("evaluation-and-deployment-and-consequence","robustness-and-system-boundary","latency-and-resource","Generative text-to-audio retrieval should preserve multiscale audio structure without excessive cost.","Fine representations improve detail but make tokenization and retrieval slow or memory-heavy.","Use one resolution or maximize fidelity without measuring retrieval cost.","Use a multi-scale tokenizer and generative retrieval architecture with explicit resource tradeoffs.","Coarse and fine audio tokens represent different temporal resolutions for retrieval.","The paper reports GTA results for generative text-to-audio retrieval.","Audio, prompts, token rates, metrics, hardware, and generation budget bound transfer."),
}
FIELDS=[("bp","Ordinary problem"),("wh","Why hard"),("naive","Naive attempt"),("ap","Central move"),("mech","Mechanism"),("math","Mathematical/conceptual structure"),("ww","What paper reports"),("limits","Limits")]
def main():
    notes=[]; claims=[]; md=["# INTERSPEECH 2025 fifty-ninth-pass full-paper notes","","Nine genuinely uncaptured official-PDF readings extend the lowest-coverage D3 families.",""]
    for i,(pid,v) in enumerate(N.items(),1):
        theme,sub,concept,*vals=v; p,c=PAP[pid],CAP[pid]; bp,wh,naive,ap,mech,ww,limits=vals; math=f"The relevant object is the {concept} evidence described by the paper's mechanism: {mech}"
        n={"paper_id":pid,"title":p["title"],"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"eval":math,"ww":ww,"limits":limits,"dots":{"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"sibling_family":"batch-059"},"source":{"kind":"official-isca-archive-paper-page-plus-captured-pdf-text","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"pdf_path":f"data/interspeech-2025-pdfs/{pid}.pdf","text_path":c["full_text_path"]},"depth":"D3","evidence_boundary":"D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}; notes.append(n)
        claims.append({"claim_id":f"IS25-D3C59-{i:02d}","paper_id":pid,"subtheme":sub,"claim":ww,"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":limits})
        md += [f"## {i}. {sub}","",f"**Paper:** [{p['title']}]({p['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]+[f"- **{label}:** {n[key]}" for key,label in FIELDS]+[""]
    (DATA/"interspeech-2025-fiftyninth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
    (DATA/"interspeech-2025-fiftyninth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
    REPORTS.mkdir(exist_ok=True); (REPORTS/"INTERSPEECH_2025_FIFTYNINTH_D3_NOTES.md").write_text("\n".join(md)+"\n"); print(json.dumps({"notes":len(notes),"claims":len(claims)}))
if __name__=="__main__": main()
