#!/usr/bin/env python3
"""Write first-principles notes for the eighth captured D3 set."""
from __future__ import annotations
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPORTS = HERE / "reports"
capture = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-eighth-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

def n(subtheme, paper_id, bp, wh, naive, ap, mech, math, dots, ww, limits):
    return {"subtheme":subtheme,"paper_id":paper_id,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"dots":dots,"ww":ww,"limits":limits}

notes = [
n("listening-and-separation/source-separation-and-spatial-listening","alizadeh25_interspeech","A recording may contain an unknown number of people speaking at once, but a useful separator must decide how many voices to return.","A fixed two- or three-speaker model fails when more people are present, while a separate model for each count grows expensive.","Tell the model the speaker count in advance, or select a decoder built for that count.","Separate one stream at a time and let a lightweight authorization block decide when recursion should stop.","ReSepNet applies a dual-path transformer repeatedly; each iteration estimates one source and cross-correlation decides whether another iteration is needed. It trains on two/three-speaker mixtures and tests on four/five.","Permutation-invariant loss ignores output order. SI-SNR improvement is 21.16 dB on WSJ0-2mix, 19.19 on 3mix, 14.91 on 4mix, and 12.03 on 5mix; the 2.8M-parameter model estimates count with 96.6% accuracy.","The stopping rule becomes part of separation rather than an external assumption, connecting source separation to a real deployment interface.","The paper reports higher SI-SNR improvement than listed baselines and generalization from two/three-speaker training to four/five-speaker tests.","The evidence is synthetic WSJ0 mixtures, 8-kHz four-second windows, and a bounded count range; real rooms and end-to-end recognition are not tested. Results are author-reported."),
n("sound-and-production/source-filter-production","arai25_interspeech","A physical vocal-tract model should either hold a known shape still for teaching or change shape over time to demonstrate articulation.","A static model is repeatable but cannot show movement; a dynamic machine is expressive but harder to build and interpret.","Use one simplified tube model for every purpose and ignore the missing detail or motion.","Show the two ends of the design space: a fixed one-vowel dummy head and a cam-driven model whose blocks change shape in real time.","The static model fixes one tract configuration and radiates a repeatable vowel; the dynamic model uses blocks and cams to change simulated articulators and tract shape.","The relevant object is tract geometry, which determines resonances and radiation; this demonstration has no common benchmark score.","It makes the production-side source/filter relationship visible instead of hiding it in a learned representation.","The paper demonstrates both models and argues that static and dynamic versions serve different education, phonetics, pathology, and technology purposes.","This is a two-page demonstration with no shared quantitative evaluation or claim of human-speech equivalence."),
n("languages-accents-and-resources/accent-and-cultural-boundaries","bafna25_interspeech","A language-identification system should identify the language, not the speaker's accent or first language.","Short phonetic patterns associated with a speaker's native language can make a model confuse accent with language; overall accuracy hides minority failure.","Train a classifier on whole-utterance labels and assume longer audio automatically supplies enough language evidence.","Add phoneme-sequence or discretized-unit views and test the shortcut by permuting short speech chunks.","The study compares ECAPA-TDNN, MMS, and GEO systems on several corpora, measures accent-language confusion, reverses chunks, and fuses acoustic and sequence representations.","ECAPA-TDNN falls from 87.6% to 55.8% on CommonVoice and 73% to 57% on EdAcc for mainstream versus L2 accents; many models remain stable down to roughly 0.25-second chunks.","Accent robustness is a representation problem: retain language-level sequence structure while discarding the shortcut correlating accent with language.","Dutch-accented English is called Dutch in 82.6% of errors in one setting; sequence-aware systems reduce this confusion while retaining mainstream performance.","Datasets, accent categories, chunking, and aggregation define the result; it diagnoses a shortcut but does not prove cultural neutrality or universal transfer."),
n("people-variation-and-health/clinical-and-assistive-speech","baumann25_interspeech","A recognizer trained on typical speech must understand speech altered by different medical conditions despite scarce labels.","Articulation, phonation, and prosody change differently by etiology; indiscriminate data may teach the wrong invariances, while synthetic data adds artifacts.","Fine-tune a general encoder on the small clinical corpus, or add as much unrelated speech as possible.","Continue self-supervised pre-training on pathological speech, use etiology-specific codebooks, and select external examples by semantic similarity.","A BEST-RQ Conformer is continued on pathological speech; fine-tuning compares synthetic, out-of-domain, and transcript-embedding-selected data, with similarity losses.","Overall WER is 19.73 versus 22.73 for the BEST-RQ baseline; 150% OOD augmentation reaches 17.32 and similarity-weighted pairing 17.81, while Down syndrome does not benefit from augmentation.","Variation is structured rather than noise: useful extra data resemble the production differences the recognizer must serve.","The authors report 13.2% relative WER improvement from pathology-aware pre-training, up to 8.7% from synthetic data, 12.2% from OOD data, and 9.7% from semantic selection.","Etiologies, corpora, similarity model, and ratios bound the claim; improvements differ by condition and synthetic speech may not preserve clinical variation."),
n("voice-generation-and-control/prosody-and-interactive-control","chen25b_interspeech","TTS must sound natural and intelligible while responding quickly enough for real use; diffusion refinement makes that balance difficult.","Maximizing a learned naturalness reward can move the generator away from the distribution learned during diffusion training.","Maximize perceptual reward alone, or keep the original loss and accept the quality-speed tradeoff.","Use the diffusion loss as a regularizer inside policy optimization so naturalness improvement remains tied to learned speech structure.","DLPO fine-tunes WaveGrad 2 with a reward combining UTMOS naturalness and the original diffusion loss, comparing DPOK, KLinR, and diffusion-only optimization.","DLPO reports UTMOS 3.65, NISQA 4.02, WER 1.0%, and 67% pairwise preference; these are different proxies, not one quality axis.","The control problem is preserving content while changing delivery; here stability comes from constraining the generator's own probability structure.","The paper reports gains over the baseline and competing reward objectives, with listeners preferring samples 67% of the time.","The evidence uses WaveGrad 2 and selected reward predictors; predicted metrics and pairwise preference do not establish broad real-time deployment."),
n("meaning-and-interaction/grounding-and-action","fujita25b_interspeech","An audio-language system should answer different questions about the same sound, not memorize one caption wording.","Several captions can describe one sound, and direct reference-sentence training can reward surface wording rather than scene meaning.","Train directly to reproduce the dataset caption and assume fluency implies instruction following.","Train the model to continue a dialogue after an audio-triggered caption, making the target a conversational response.","An audio encoder feeds an adapter and language model; interleaved audio/text examples use token cross-entropy, with LoRA tested on AudioCaps, WavCaps, and Clotho.","The loss is token-level cross-entropy. The best reported average AQA accuracy is 47.70%, judged by Llama-3-70B-Instruct; the judge is itself a proxy.","The move is from naming an event to grounding an answer in it, connecting caption variation to useful interaction.","Dialogue-continuation training enables zero-shot instruction following and improves reported AQA, while AAC gains are mixed.","Generated captions, benchmarks, and an LLM judge define the evidence; human usefulness for deaf or hard-of-hearing users is not established."),
n("evaluation-deployment-and-consequence/privacy-security-and-accountability","chandra25b_interspeech","A fake-speech detector must recognize manipulation it has not seen, including changed codec, attack, and language.","A detector can learn a generator or recording fingerprint instead of the genuine/fake property, so in-domain scores collapse under shift.","Train on known attacks and treat high test accuracy as general spoofing ability.","Remove attack-specific information with an attack-invariant encoder-decoder and common-subspace decomposition before classification.","A frozen wav2vec2 front-end and AASIST backend produce embeddings; AIED suppresses attack variation and CSD projects into a shared subspace, tested on ASVspoof and IndicTTS.","EER changes from 6.14 to 5.84 on LA, 12.33 to 10.90 on DF, and 59.82 to 39.51 on IndicTTS; the large cross-language gap remains.","Security claims require invariance to attack and language shortcuts while retaining the genuine/fake distinction.","The paper reports 4%, 12%, and 34% relative EER improvements on LA, DF, and IndicTTS, with ablations separating AIED and CSD.","Datasets, attacks, frozen front-end, and language coverage bound the result; IndicTTS EER remains high and no independent adversarial evaluation was performed."),
n("recognition-and-alignment/acoustic-unit-mapping","ahadzi25_interspeech","A child-focused ASR service may receive speech over time, but updating it can make it forget earlier speakers and require centralized storage.","Children's speech changes with development, data are scarce, and sequential speakers create drift; ordinary fine-tuning overwrites useful parameters.","Fine-tune the latest model on each new batch and keep only the newest checkpoint.","Protect parameters important for earlier batches with EWC or SI, and compare online checkpoint-selection policies.","Whisper-small trains on ten sequential MyST batches. EWC adds an importance-weighted quadratic penalty; SI accumulates importance from parameter movement and loss reduction; models use no selection, rolling-window, or best-so-far selection.","MyST has 145.54 training hours, 23.09 development hours, and 25.05 test hours. EWC and SI report relative WER reductions of 5.21% and 4.36% against sequential fine-tuning; bootstrap intervals quantify uncertainty.","Adaptation becomes a memory-allocation problem: retain old acoustic-to-word mappings while making room for new children and privacy-conscious data arrival.","EWC and SI keep WER more stable across ten batches and improve over ordinary sequential fine-tuning under the protocol.","The protocol is simulated from MyST, uses English child speech and Whisper-small, and treats parameter importance as a proxy rather than a privacy guarantee."),
]

fields = [("bp","Big picture"),("wh","Why hard"),("naive","Naive attempt"),("ap","Central move"),("mech","Mechanism"),("math","Mathematical idea"),("dots","Connections"),("ww","What paper reports"),("limits","Limits")]
out = ["# INTERSPEECH 2025 eighth-pass full-paper notes", "", "Eight additional official-PDF notes extend D3 coverage across separation, production, accents, clinical speech, generation, grounding, spoofing, and continual recognition. Results remain author-reported and were not independently reproduced.", ""]
claims = []
for i, note in enumerate(notes, 1):
    p, c = papers[note["paper_id"]], capture[note["paper_id"]]
    out += [f"## {i}. {note['subtheme']}", "", f"**Paper:** [{p['title']}]({p['paper_url']})  ", f"**Evidence:** D3; PDF SHA-256 {c['pdf_sha256']}; {c['page_count']} pages.", ""]
    out += [f"- **{label}:** {note[key]}" for key, label in fields] + [""]
    claims.append({"claim_id":f"IS25-D3C8-{i:02d}","paper_id":note["paper_id"],"subtheme":note["subtheme"],"claim":note["ww"],"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":note["limits"]})
(DATA / "interspeech-2025-eighth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-eighth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims}, indent=2, ensure_ascii=False) + "\n")
(REPORTS / "INTERSPEECH_2025_EIGHTH_D3_NOTES.md").write_text("\n".join(out) + "\n")
print(json.dumps({"notes":len(notes),"report":"reports/INTERSPEECH_2025_EIGHTH_D3_NOTES.md"}))
