#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
HERE=Path(__file__).resolve().parent; DATA=HERE/'data'
A={
'batchelderschwab25_interspeech':('meaning-and-interaction','prosody-and-intent','prosodic-meaning','Whistled and spoken Greek test whether stress and vowel identity survive when the acoustic channel changes.'),
'battula25_interspeech':('meaning-and-interaction','prosody-and-intent','paralinguistic-state','The proposed speech-derived heart-rate proxy treats confidence as a bodily state inferred from voice-related physiology.'),
'choi25g_interspeech':('recognition-and-alignment','boundaries-and-sequence-structure','long-context-decoding','Spoken and written forms require a controlled conversion boundary after recognition; the paper addresses that normalization step.'),
'chuang25_interspeech':('languages-accents-and-resources','accent-and-cultural-boundaries','cultural-meaning','Taiwanese tone realization changes with word meaning, so phonetic variation cannot be interpreted without linguistic context.'),
'chung25_interspeech':('listening-and-separation','echo-and-reconstruction','perceptual-enhancement','Speech restoration must infer which distortion is present before repairing it; acoustic context is used to condition the repair.'),
'cui25_interspeech':('recognition-and-alignment','boundaries-and-sequence-structure','long-context-decoding','Contextual ASR tests whether preceding, current, and future utterances improve the mapping from sound to words.'),
'du25_interspeech':('languages-accents-and-resources','accent-and-cultural-boundaries','dialect-and-variety','A complex Mienic tone system shows that language-specific pitch and duration cues define what counts as a contrast.'),
'ersoy25_interspeech':('meaning-and-interaction','grounding-and-action','referential-grounding','Comparing speech and text models asks whether a speech representation carries abstract concepts rather than only acoustic form.'),
'fathan25_interspeech':('people-variation-and-health','speaker-characteristics','speaker-verification','Speaker verification exposes whether optimization changes identity evidence and generalization across speakers.'),
'feng25b_interspeech':('people-variation-and-health','speaker-characteristics','speaker-verification','Egocentric sensing changes the acoustic viewpoint, so speaker classification must separate who is speaking from where the microphone is worn.'),
'gaudrain25_interspeech':('people-variation-and-health','human-centered-evaluation','accessibility-fit','Controlled speech stimuli test how hearing-related neural limitations affect access to fine temporal speech information.'),
'gebauer25_interspeech':('people-variation-and-health','clinical-and-assistive-speech','clinical-speech-marker','Grammatical errors in spontaneous child speech are treated as a possible marker of developmental language disorder, with label ambiguity made explicit.'),
'gu25_interspeech':('voice-generation-and-control','voice-identity-and-conversion','voice-conversion','Pitch manipulation must change the intended musical attribute while preserving the singer identity.'),
'gu25b_interspeech':('evaluation-deployment-and-consequence','robustness-and-system-boundary','latency-and-resource','Quantizing a large speech model changes its memory and computation boundary, so deployment requires measuring the accuracy-cost tradeoff.'),
'gulzar25_interspeech':('meaning-and-interaction','dialogue-and-turn-taking','dialogue-state','Spoken dialogue state tracking must survive disfluencies and recognition errors rather than assume clean written turns.'),
'gupta25b_interspeech':('sound-and-production','room-channel-and-sensing','microphone-channel','Hear-through equalization must compensate for direction-dependent acoustic transmission while remaining stable and low-latency.'),
'hamann25_interspeech':('languages-accents-and-resources','accent-and-cultural-boundaries','cultural-meaning','Listeners’ native phonotactics and language experience change how unfamiliar speech sequences are discriminated.'),
'hannan25_interspeech':('people-variation-and-health','speaker-characteristics','speaker-verification','Face-voice association aligns two identity-bearing signals, making identity evidence a cross-modal representation problem.'),
'harrington25_interspeech':('people-variation-and-health','speaker-characteristics','speaker-verification','Speaker-recognition averages conceal persistent hard speakers; the paper separates system generation effects from person-level variation.'),
'havard25_interspeech':('languages-accents-and-resources','multilingual-and-crosslingual','crosslingual-transfer','Haitian Creole recognition compares monolingual and multilingual pretraining to test when transfer helps a lower-resource language.'),
'higuchi25_interspeech':('recognition-and-alignment','boundaries-and-sequence-structure','long-context-decoding','Speech translation couples an acoustic hypothesis with a language model so context can repair recognition errors before translation.'),
'hilmes25_interspeech':('recognition-and-alignment','acoustic-unit-mapping','self-supervised-speech-units','CTC blank handling determines which frame-level structure a compact recognizer inherits during distillation.'),
'hiruta25_interspeech':('languages-accents-and-resources','low-resource-and-data-creation','speech-data-collection','Selecting acoustically diverse and uncertain utterances treats annotation budget as a design problem for speech data.'),
'ho25_interspeech':('recognition-and-alignment','boundaries-and-sequence-structure','long-context-decoding','Streaming inverse text normalization must use limited context and latency constraints while converting spoken output into written form.'),
'hojo25_interspeech':('people-variation-and-health','clinical-and-assistive-speech','dysarthria-and-atypical-speech','Organic speech disorders require adaptation that uses scarce patient speech without discarding pronunciation and language structure.'),
'holler25_interspeech':('meaning-and-interaction','grounding-and-action','interactional-feedback','Face-to-face meaning is jointly carried by speech, gesture, face, and head movement, with timing affecting comprehension and response.')}
REJECT={'chien25_interspeech':'LLM prompt refinement is text-only and supplies no speech signal, listener, or spoken interaction evidence.','cr25_interspeech':'Polyphonic music instrument recognition is not a speech problem; the acoustic task and target are instruments.','dai25_interspeech':'Sound-event detection is non-speech environmental audio and does not establish a speech concept.','dong25c_interspeech':'Music-to-finger-dance generation is a motion-generation task, not speech research.','hai25_interspeech':'Text-to-audio generation targets general sound effects rather than speech production, perception, or interaction.','hartmann25_interspeech':'The dataset is text-only Reddit discourse; it has no speech or spoken-language evidence.'}
papers={p['paper_id']:p for p in json.loads((DATA/'interspeech-2025-papers.json').read_text())['papers']}; rows=[]
for pid,reason in REJECT.items():
 p=papers[pid]; a=p.get('abstract',''); rows.append({'paper_id':pid,'title':p['title'],'decision':'unsupported','confidence':'analyst-reviewed-D2','theme_id':None,'subtheme_id':None,'concept_id':None,'semantic_reasoning':reason,'evidence_fields':['title','abstract'],'evidence_excerpt':a[:1400],'source_location':p['paper_url'],'source_sha256':hashlib.sha256(a.encode()).hexdigest(),'evidence_depth':'D2','review_state':'analyst-reviewed','claim_boundary':'Official abstract was sufficient to establish that the paper is outside the speech taxonomy; no speech concept is assigned.'})
for pid,a in A.items():
 p=papers[pid]; abstract=p.get('abstract','')
 if not abstract: raise SystemExit('missing abstract: '+pid)
 rows.append({'paper_id':pid,'title':p['title'],'decision':'supported','confidence':'analyst-reviewed-D2','theme_id':a[0],'subtheme_id':a[1],'concept_id':a[2],'semantic_reasoning':a[3],'evidence_fields':['problem','mechanism','evaluation','boundary'],'evidence_excerpt':abstract[:1400],'source_location':p['paper_url'],'source_sha256':hashlib.sha256(abstract.encode()).hexdigest(),'evidence_depth':'D2','review_state':'analyst-reviewed','claim_boundary':'Abstract supports the problem and proposed move; full-paper mechanism, tables, ablations, and limitations remain unreviewed.'})
payload={'schema_version':1,'batch_id':'interspeech-2025-semantic-d2-batch-013','status':'analyst-reviewed-D2-batch','claim_boundary':'These 32 assignments are analyst readings bounded by official abstracts; six are explicit out-of-scope decisions and the supported rows do not establish full-paper mechanisms or results.','reviewed_count':len(rows),'rows':rows}
(DATA/'interspeech-2025-semantic-reviewed-d2-batch-013.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False)+'\n'); print(json.dumps({'batch_id':payload['batch_id'],'reviewed_count':len(rows),'supported':len(A),'unsupported':len(REJECT)}))
