#!/usr/bin/env python3
import json
from pathlib import Path
H=Path(__file__).resolve().parent; D=H/'data'; R=H/'reports'
C={x['paper_id']:x for x in json.loads((D/'interspeech-2025-fourteenth-d3-papers.json').read_text())['papers']}; P={x['paper_id']:x for x in json.loads((D/'interspeech-2025-papers.json').read_text())['papers']}
N=[('recognition-and-alignment/boundaries-and-sequence-structure','ho25_interspeech','Speech arrives incrementally, but written formatting often needs context that has not arrived yet.','Streaming ITN must balance incomplete context, accuracy, adaptation, and latency.','Run a full-context normalizer after the utterance is complete, or use fixed chunks that ignore right context.','Use a pretrained language model with dynamic chunk sizes and controlled right-context during training and inference.','The model changes its available context as speech arrives, using right-context information without abandoning the streaming budget.','Sequence decoding maps spoken-form tokens to written-form tokens; latency and accuracy form the deployment tradeoff.','Normalization is a boundary between recognition and usable text, not a cosmetic postprocessing detail.','The paper reports accuracy comparable to non-streaming ITN and better than prior streaming models on Vietnamese data while maintaining low latency.','Vietnamese data, benchmark, and author-reported latency/results limit cross-language and independent deployment claims.'),('listening-and-separation/source-separation-and-spatial-listening','huang25k_interspeech','Meeting speech contains overlapping speakers, and diarization and recognition must make decisions from the same mixed observations.','Overlap changes which speaker evidence is reliable; guided source separation can fail at low signal-to-noise ratio.','Use one diarization model and assume separated observations are equally useful for ASR.','Combine overlap-adaptive diarization with ASR-aware observation addition and a cascaded meeting-recognition system.','A hybrid segmentation/clustering diarizer selects its model by overlap, while ASR-aware observations compensate for weak guided separation before recognition.','Diarization assigns speaker-time regions; CER and concatenated minimum-permutation CER measure the downstream meeting transcript.','Separation is not an isolated front end: errors in overlap decisions change recognition evidence and speaker attribution together.','The system reports 9.48% CER and 11.56% cpCER and first place in both MISP tracks.','Challenge tracks, meeting conditions, and author-reported ranking limit generalization and independent reproduction.')]
F=[('bp','Big picture'),('wh','Why hard'),('naive','Naive attempt'),('ap','Central move'),('mech','Mechanism'),('math','Mathematical idea'),('dots','Connections'),('ww','What paper reports'),('limits','Limits')]
notes=[]; claims=[]; out=['# INTERSPEECH 2025 fourteenth-pass full-paper notes','','Two official-PDF analyses deepen the two remaining thin D3 families: sequence boundaries and spatial source separation. Results remain author-reported and were not independently reproduced.','']
for i,row in enumerate(N,1):
    d=dict(zip(['subtheme','paper_id','bp','wh','naive','ap','mech','math','dots','ww','limits'],row)); notes.append(d); p,cap=P[d['paper_id']],C[d['paper_id']]
    out += [f'## {i}. {d["subtheme"]}','',f'**Paper:** [{p["title"]}]({p["paper_url"]})  ',f'**Evidence:** D3; PDF SHA-256 {cap["pdf_sha256"]}; {cap["page_count"]} pages.','']+[f'- **{lab}:** {d[key]}' for key,lab in F]+['']
    claims.append({'claim_id':f'IS25-D3C14-{i:02d}','paper_id':d['paper_id'],'subtheme':d['subtheme'],'claim':d['ww'],'evidence_depth':'D3','pdf_sha256':cap['pdf_sha256'],'full_text_sha256':cap['full_text_sha256'],'support_status':'paper-reported-not-independently-verified','independent_support_status':'not-established','limitations':d['limits']})
(D/'interspeech-2025-fourteenth-d3-notes.json').write_text(json.dumps({'venue':'INTERSPEECH 2025','evidence_depth':'D3','notes':notes},indent=2,ensure_ascii=False)+'\n')
(D/'interspeech-2025-fourteenth-claim-ledger.json').write_text(json.dumps({'venue':'INTERSPEECH 2025','claim_count':len(claims),'claims':claims},indent=2,ensure_ascii=False)+'\n')
(R/'INTERSPEECH_2025_FOURTEENTH_D3_NOTES.md').write_text('\n'.join(out)+'\n')
print(json.dumps({'notes':len(notes)}))
