"""Write first-principles notes for D3 batch 053."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPORTS = HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftythird-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

N = {
    "eom25_interspeech": ("recognition-and-alignment", "boundaries-and-sequence-structure", "alignment", "A speech representation should recognize the same linguistic content when the speaker talks faster or slower.", "Two views can have different frame counts, so frame-to-frame equality treats timing variation as content change.", "Align every augmented frame to its counterpart and penalize harmless shifts.", "Use CTC to learn a flexible monotonic alignment between views inside a Siamese learner.", "Two encoders produce sequences and CTC sums over valid monotonic paths while training the representations to agree at content level.", "A monotonic path preserves temporal order while allowing variable durations; it is a soft alignment over possible boundaries.", "SiamCTC improves representation robustness at diverse speaking rates in the reported experiments.", "Augmentation, language, CTC targets, downstream tasks, and rate range bound transfer; robustness is not universal recognition accuracy."),
    "jin25b_interspeech": ("recognition-and-alignment", "boundaries-and-sequence-structure", "alignment", "An avatar or speech tool needs phoneme boundaries quickly on-device, sometimes without a transcript and across languages.", "Recognition and alignment must share computation, multilingual phonetics vary, and mobile latency limits model size.", "Run a large offline aligner or require text and a separate recognizer before placing boundaries.", "Train an end-to-end model for phoneme recognition and text-independent forced alignment, with optional text conditioning.", "VoiceNet predicts phoneme evidence and timing on-device; text adds a constraint when available, and device tests expose latency.", "Alignment is ordered interval inference rather than a post-processing attachment to recognition.", "The paper reports competitive multilingual alignment and 6 ms average CPU phoneme inference on Galaxy devices.", "Device, language, phoneme inventory, transcript availability, and splits bound transfer; latency is not alignment quality."),
    "chou25_interspeech": ("voice-generation-and-control", "voice-identity-and-conversion", "zero-shot-voice", "Convert emotional expression for an unseen speaker while preserving words and recognizable identity.", "Emotion and identity share acoustic cues, so changing one can distort content or impose training-speaker assumptions.", "Train a speaker-specific converter or change prosody heuristically and accept identity leakage.", "Use zero-shot diffusion with disentangled content, identity, and expressive guidance, testing unseen speakers in and out of domain.", "Diffusion denoising reconstructs speech from a noisy latent while separate conditions guide emotion and speaker/content.", "Disentanglement asks emotion to move while content and identity remain stable enough for a listener.", "The paper reports improved emotional accuracy and naturalness for unseen speakers across evaluated datasets.", "Labels, speaker coverage, out-of-domain definition, protocol, and identity metrics bound transfer; conversion does not establish consent."),
    "franzreb25_interspeech": ("voice-generation-and-control", "voice-identity-and-conversion", "zero-shot-voice", "An anonymizer should hide who spoke while keeping words and useful prosody, and evaluation should reveal what still identifies the person.", "Prosody can leak identity after spectral conversion, while speaker recognition is only a privacy proxy.", "Convert timbre alone and assume duration and pitch variation carry no identity information.", "Add interpretable kNN-VC components that anonymize phone duration and variation, then vary target-speaker selection.", "The anonymizer changes duration and prosodic variation around phones; a recognition attack tests whether those factors predict identity.", "Privacy is decomposed into leakage channels instead of one opaque score.", "The added components increase privacy in the tested attack, and target selection changes measured privacy.", "Attack, target pool, language, utility metric, and prosody definitions bound the result; attack reduction is not anonymity."),
    "kwok25c_interspeech": ("recognition-and-alignment", "adaptation-and-open-vocabulary", "open-vocabulary-recognition", "Rare names and terms should be recognized when they are not common in the vocabulary.", "Trie biasing rewards a partial word before knowing whether the full word completes, then revokes rewards during beam search.", "Add a fixed bonus to every matching prefix and pay the cost of undoing it when the hypothesis fails.", "Train a K-step predictor to look ahead and estimate whether a rare word will complete, avoiding score revocation.", "The decoder predicts future steps from a prefix; synthetic data fine-tunes Whisper so contextual biasing becomes learned look-ahead.", "The method replaces delayed correction with an approximate future-value estimate, trading learned prediction for simpler decoding.", "On NSC Part 2, reported WER falls from 30.86% to 12.19% after 10 hours of synthetic-data fine-tuning.", "Synthetic realism, rare-word list, decoder, beam settings, and WER denominator bound the claim."),
    "r25_interspeech": ("recognition-and-alignment", "adaptation-and-open-vocabulary", "open-vocabulary-recognition", "Query-by-example search should find a spoken term across Indian languages without one language-specific phoneme inventory.", "Phoneme symbols and pronunciation conventions differ, while query and target need comparable representations.", "Use one shared phoneme dictionary and assume posteriors mean the same thing across languages.", "Use multilingual ASR character logits in a shared Devanagari transliteration space for query and target audio.", "The ASR maps ten languages to transliterated characters; posterior sequences become retrieval features.", "Transliteration changes the shared unit from language-specific phonemes to a common script-level sequence representation.", "The method raises reported MTWV from 0.015 to 0.504 on IndicSUPERB and exceeds the Marathi baseline.", "Language, script, ASR errors, query duration, and splits constrain transfer; script unification is not translation."),
    "alexos25_interspeech": ("evaluation-and-deployment", "robustness-and-system-boundary", "end-to-end-recovery", "A speech-enabled LLM should refuse harmful requests even when an attacker uses the speech channel.", "Speech adds transcription, acoustic, and modality-transfer attack surfaces, while harmful data are scarce.", "Apply text-only safety tuning or assume speech inherits the text safety boundary.", "Adversarially train with synthesized harmful and benign speech, then test strong white-box attacks and data ablations.", "Speech-domain harmful examples change the model; training configurations vary and safety is measured under attacks.", "Robustness is response behavior under a threat model, not ordinary accuracy.", "Four hours of harmful plus 150 hours of benign speech yields reported relative safety gains of 45–300% over baseline.", "Attack family, harm taxonomy, model, synthesis, and rubric bound the claim; refusal is not complete security."),
    "li25v_interspeech": ("evaluation-and-deployment", "robustness-and-system-boundary", "latency-and-resource", "A speech model should fit memory and storage limits without losing larger-model behavior at different deployment depths.", "Depth-specific models duplicate parameters, while compression can reduce capacity or make one operating point brittle.", "Store a separate full model for each depth, or prune once and accept a fixed quality/resource tradeoff.", "Train a compact seed and unfold it through shared structures, using KL self-distillation between largest and seed paths.", "Logical depth changes through repeated blocks sharing a seed; distillation aligns small and large outputs across paths.", "Unfolding trades parameter storage for repeated computation, while KL divergence keeps paths behaviorally close.", "The models report comparable ASR with 35% Conformer and 30% wav2vec2/HuBERT parameter reductions.", "Hardware latency, unfolding cost, family, task, and benchmark coverage bound transfer; fewer parameters is not automatically less energy."),
}

notes = []
claims = []
md = ["# INTERSPEECH 2025 fifty-third-pass full-paper notes", "", "Eight official-PDF readings deepen alignment, voice identity/conversion, open-vocabulary recognition, safety, and resource boundaries.", ""]
for i, (pid, f) in enumerate(N.items(), 1):
    theme, sub, concept, bp, wh, naive, ap, mech, math, ww, limits = f
    p = papers[pid]; c = captured[pid]
    note = {"paper_id": pid, "title": p["title"], "theme_id": theme, "subtheme_id": sub, "concept_id": concept, "bp": bp, "wh": wh, "naive": naive, "ap": ap, "mech": mech, "math": math, "eval": math, "ww": ww, "limits": limits, "dots": {"theme_id": theme, "subtheme_id": sub, "concept_id": concept, "sibling_family": "batch-053"}, "source": {"kind": "official-isca-archive-paper-page-plus-captured-pdf-text", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "pdf_path": f"data/interspeech-2025-pdfs/{pid}.pdf", "text_path": c["full_text_path"]}, "depth": "D3", "evidence_boundary": "D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}
    notes.append(note)
    claims.append({"claim_id": f"IS25-D3C53-{i:02d}", "paper_id": pid, "subtheme": sub, "claim": ww, "evidence_depth": "D3", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "support_status": "paper-reported-not-independently-verified", "independent_support_status": "not-established", "limitations": limits})
    md += [f"## {i}. {sub}", "", f"**Paper:** [{p['title']}]({p['paper_url']})", f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.", ""]
    md += [f"- **{label}:** {note[key]}" for label, key in zip(["Ordinary problem", "Why hard", "Naive attempt", "Central move", "Mechanism", "Mathematical/conceptual structure", "What paper reports", "Limits"], ["bp", "wh", "naive", "ap", "mech", "math", "ww", "limits"])] + [""]
(DATA / "interspeech-2025-fiftythird-d3-notes.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "evidence_depth": "D3", "notes": notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-fiftythird-claim-ledger.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "claim_count": len(claims), "claims": claims}, indent=2, ensure_ascii=False) + "\n")
REPORTS.mkdir(exist_ok=True)
(REPORTS / "INTERSPEECH_2025_FIFTYTHIRD_D3_NOTES.md").write_text("\n".join(md) + "\n")
print(json.dumps({"notes": len(notes), "claims": len(claims)}))
