import json
from pathlib import Path
HERE=Path(__file__).resolve().parent; DATA=HERE/"data"; REPORTS=HERE/"reports"
C={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-sixtyfirst-d3-papers.json").read_text())["papers"]}; P={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-papers.json").read_text())["papers"]}
N={
"du25_interspeech":("languages-and-people","accent-and-cultural-boundaries","dialect-and-variety","A speech system should describe and recognize a language variety without erasing the contrast that makes the variety meaningful.","Small phonetic inventories and limited documentation make variation easy to mistake for noise or a universal norm.","Collapse the variety into a standard-language model and report only pooled accuracy.","Measure tonal contrasts in the Malipo variety as an object of speech description and evaluation.","Contrastive measurements expose which acoustic distinctions carry linguistic information.","The paper reports an empirical study of tonal contrasts in a Mienic variety.","Speaker sample, elicitation design, tonal context, and language-specific scope bound transfer."),
"wen25b_interspeech":("people-and-health","human-centered-evaluation","accessibility-fit","Speech enhancement should improve access for a particular hearing-impaired listener, not merely optimize an average signal metric.","Hearing loss profiles differ, and a global enhancer can preserve the wrong cues.","Optimize one pooled enhancement objective and assume its score represents every listener.","Individualize enhancement around the listener's hearing profile and evaluate the resulting speech access.","Listener-specific constraints become the target of enhancement rather than the average waveform.","The paper reports individualized speech enhancement for hearing-impaired listeners.","Hearing profiles, listener numbers, fitting procedure, materials, and subjective protocol bound transfer."),
"gao25c_interspeech":("recognition-and-transcription","acoustic-unit-mapping","pronunciation-variation","Child speech recognition and reading-mistake detection should connect variable child acoustics to intended linguistic units and learning outcomes.","Children differ in articulation, age, reading skill, and pronunciation, so adult-trained acoustic boundaries are unreliable.","Apply an adult ASR model and treat every mismatch as an ordinary recognition error.","Use prompts to condition recognition and mistake detection on the child's intended reading task.","Prompt information narrows the hypothesis space: acoustic evidence is interpreted with task and expected linguistic content.","The paper reports improving child speech recognition and reading-mistake detection using prompts.","Child age, language, prompt design, annotation policy, and error definitions bound transfer."),
}
FIELDS=[("bp","Ordinary problem"),("wh","Why hard"),("naive","Naive attempt"),("ap","Central move"),("mech","Mechanism"),("math","Mathematical/conceptual structure"),("ww","What paper reports"),("limits","Limits")]
def main():
 notes=[]; claims=[]; md=["# INTERSPEECH 2025 sixty-first-pass full-paper notes","","Three additional readings extend comparison across dialect description, individualized accessibility, and child-speech recognition.",""]
 for i,(pid,v) in enumerate(N.items(),1):
  theme,sub,concept,*vals=v; theme={"du25_interspeech":"languages-accents-and-resources","wen25b_interspeech":"people-variation-and-health","gao25c_interspeech":"recognition-and-alignment"}[pid]; p,c=P[pid],C[pid]; bp,wh,naive,ap,mech,ww,limits=vals; math=f"The paper treats {concept} as a structured evidence-to-decision problem: {mech}"
  n={"paper_id":pid,"title":p["title"],"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"eval":ww,"ww":ww,"po":f"The paper's payoff is a more population- or task-specific account of {concept}; the measured benefit remains author-reported.","limits":limits,"dots":{"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"sibling_family":"batch-061"},"source":{"kind":"official-isca-archive-paper-page-plus-captured-pdf-text","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"pdf_path":f"data/interspeech-2025-pdfs/{pid}.pdf","text_path":c["full_text_path"]},"depth":"D3","evidence_boundary":"D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}
  notes.append(n); claims.append({"claim_id":f"IS25-D3C61-{i:02d}","paper_id":pid,"subtheme":sub,"claim":ww,"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":limits}); md += [f"## {i}. {sub}","",f"**Paper:** [{p['title']}]({p['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]+[f"- **{label}:** {n[key]}" for key,label in FIELDS]+[""]
 (DATA/"interspeech-2025-sixtyfirst-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n"); (DATA/"interspeech-2025-sixtyfirst-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n"); REPORTS.mkdir(exist_ok=True); (REPORTS/"INTERSPEECH_2025_SIXTYFIRST_D3_NOTES.md").write_text("\n".join(md)+"\n"); print(json.dumps({"notes":len(notes),"claims":len(claims)}))
if __name__=="__main__": main()
