"""Write first-principles notes and claims for D3 batch 056."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA, REPORTS = HERE / "data", HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftysixth-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

N = {
"wang25_interspeech": ("languages-accents-and-resources", "accent-and-cultural-boundaries", "dialect-variation", "An Arabic ASR system should work across dialects rather than appear strong on one convenient corpus.", "Dialect, recording, vocabulary, and corpus composition vary together, so a single benchmark can hide generalization failures.", "Report one WER on one dialect and treat it as universal Arabic performance.", "Build a public multi-dataset leaderboard that compares models across dialects and also exposes robustness, adaptation, efficiency, and memory dimensions.", "The benchmark fixes model/data/evaluation axes across six test corpora and records WER plus resource and adaptation measurements.", "A leaderboard is a measurement design: the set of dialects and denominators determines which kind of generalization is visible.", "The paper reports broad comparative results and identifies differences in dialect robustness, speaker adaptation, inference efficiency, and memory use.", "Corpus selection, language variety, transcription conventions, model versions, and leaderboard maintenance bound the conclusion; rankings are not a causal explanation of dialect performance."),
"narain25_interspeech": ("evaluation-and-deployment-and-consequence", "metrics-and-targets", "quality-and-naturalness", "A speech system needs interpretable estimates of atypical voice qualities such as breathiness, monopitch, or imprecise consonants.", "A single embedding score compresses distinct perceptual failures and may not generalize across speakers, elicitation tasks, languages, or disorders.", "Train one opaque quality regressor and call its correlation with a rating a complete account of speech accessibility.", "Train separate probes for seven voice-quality dimensions on frozen speech representations, then test cross-category and zero-shot transfer.", "The frozen representation supplies a common acoustic space while lightweight probes map it to interpretable dimensions; held-out speakers and out-of-domain datasets test transfer.", "Factorizing a human judgment into named dimensions makes the target inspectable, but each probe still inherits annotation and distribution assumptions.", "The paper reports strong probe performance and generalization on SAP categories, with zero-shot tests on additional languages, tasks, and affect data.", "Proxy labels, speaker/sample overlap, limited out-of-domain sets, frozen-encoder choice, and correlation metrics bound transfer; dimensional prediction is not a clinical or listener-outcome validation."),
"wang25s_interspeech": ("listening-and-separation", "noise-enhancement", "speech-prior-denoising", "Enhancement should remove noise while retaining the speaker and intelligibility without making real-time use impractical.", "Noise removal is a conditional distribution problem: aggressive suppression can erase speech detail, while generative samplers can be slow.", "Use a deterministic mask or a many-step diffusion sampler and accept either artifacts or latency.", "Use flow matching to learn a continuous transport from noisy to clean speech and combine it with efficient architecture and multi-resolution objectives.", "A neural velocity field maps a noisy waveform toward the clean distribution; consistency of the trajectory permits few-step integration while spectral and waveform losses preserve detail.", "Flow matching replaces repeated stochastic denoising with an ODE-like path whose learned vector field can be sampled in fewer evaluations.", "The paper reports improved enhancement quality against generative baselines in both its evaluated scenarios with lower inference cost.", "Training data, noise conditions, step count, real-time hardware, perceptual metrics, and speaker preservation tests bound the claim; enhancement scores do not establish conversational benefit."),
"wang25b_interspeech": ("evaluation-and-deployment", "robustness-and-system-boundary", "abstention-and-hallucination", "An ASR system should remain silent or abstain when the input contains non-speech instead of inventing a transcript.", "A sequence decoder is rewarded for plausible language, and non-speech segments lack lexical evidence while still activating learned decoder patterns.", "Add a VAD or post-filter around the model and assume the decoder itself has no identifiable source of hallucination.", "Diagnose decoder self-attention heads with head-wise masking, identify a small set responsible for most non-speech hallucinations, and fine-tune those heads on non-speech data.", "Ablation assigns causal responsibility at the head level; targeted fine-tuning changes the decoder’s response to acoustic absence while monitoring speech WER.", "The method creates an evidence boundary inside generation: silence should not be converted into a high-probability language continuation.", "The paper reports that three of twenty decoder heads account for most hallucinations on UrbanSound and that targeted training reduces them with limited LibriSpeech WER degradation.", "Non-speech corpus, head attribution, fine-tuning regime, language/model version, and WER tradeoff bound transfer; reduced hallucination is not perfect abstention or factual reliability."),
"pan25_interspeech": ("listening-and-separation", "source-separation-and-spatial-listening", "target-conditioned-separation", "A streaming listener should extract the person being watched even when speakers overlap and attention later switches.", "The visual cue is noisy and delayed, the mixture changes over time, and an offline separator can use future context that a live system lacks.", "Process each frame independently or optimize only the audio branch while ignoring the extracted signal’s history.", "Use a lightweight visual front end and an autoregressive acoustic encoder that feeds past separated speech back into the online model, then test target-switching scenes.", "Visual embeddings select the target, while the recurrent acoustic path summarizes prior separated audio; the mask is updated causally under a compute budget.", "Streaming separation is causal state estimation: the system must preserve target identity while updating its estimate from current visual and acoustic evidence.", "On LRS3, the paper reports competitive separation quality with about 0.1M visual parameters and 2.1 MACs/s, and evaluates switching attention.", "LRS3 faces, switching schedule, audiovisual synchronization, causal latency, and separation metrics bound transfer; benchmark separation is not a full human-attention study."),
"park25b_interspeech": ("voice-generation-and-control", "text-to-speech-and-content", "fast-speech-generation", "A TTS system should produce natural speech quickly enough for interactive use without quality collapsing when sampling steps are reduced.", "ODE-based flow generation follows a continuous path but normally needs many numerical steps; shortcutting the path can break consistency and introduce artifacts.", "Use a many-step sampler or distill it without constraining the velocity field along the path.", "Train RapFlow-TTS with velocity consistency along a straightened flow-matching trajectory, plus time scheduling and adversarial refinement.", "The model learns that velocity predictions at different time points agree along the transport path; consistency allows few-step integration while adversarial and acoustic losses protect waveform quality.", "Consistency regularization turns a generation trajectory into a reusable shortcut: nearby time intervals should imply compatible updates.", "The paper reports high-fidelity synthesis with fewer generation steps than compared flow/diffusion systems.", "Text/speaker data, subjective protocol, step counts, vocoder and hardware, and adversarial stability bound the speed-quality claim; fewer steps do not guarantee lower end-to-end latency."),
"murata25b_interspeech": ("voice-generation-and-control", "voice-identity-and-conversion", "voice-generation", "Generate a plausible unseen speaker voice without requiring a reference utterance from that speaker.", "Speaker identity is high-dimensional and entangled with linguistic content; sampling a voice representation can leave the valid speaker manifold.", "Interpolate stored speaker embeddings or clone a speaker from a reference sample, which cannot create a genuinely unseen identity without reference audio.", "Define an eigenvoice space directly in the parameter space of a DNN TTS model and sample edited model parameters to synthesize new speaker traits.", "Model-difference directions act as speaker basis vectors; adding sampled combinations to a base model changes identity while retaining the learned text-to-speech mapping.", "The speaker manifold can be represented by low-dimensional directions in parameter space rather than only by an input speaker vector.", "The paper reports diverse generated voices and compares parameter-space eigenvoice synthesis with prior speaker-generation approaches.", "Validity of sampled parameters, diversity and naturalness criteria, speaker-identification protocol, base model, and absence of reference audio bound the claim; generated identity is not evidence of a real person."),
"shepardson25_interspeech": ("voice-generation-and-control", "text-to-speech-and-content", "interactive-speech-generation", "A performer needs text-conditioned voice generation that responds in real time, can be trained from a small bespoke corpus, and remains musically controllable.", "Performance demands low worst-case latency and expressive interaction, while ordinary TTS assumes large data, fixed text, and offline generation.", "Use a conventional TTS stack and optimize average throughput, even if buffering and model assumptions make live interaction brittle.", "Define interactive artistic text-to-voice around a reduced-phonetic-alphabet dataset, streaming vocoder, bounded look-ahead, and a GUI that exposes live controls.", "The system separates alignment/generation into streaming components, buffers a small number of frames to trade latency for stability, and keeps the interface in a separate process.", "Deployment constraints become part of the speech representation and evaluation: latency, controllability, and small-data adaptation matter alongside audio quality.", "The demonstration reports real-time inference with worst-case latency below 100 ms and a bespoke performance dataset/application.", "Demonstration scope, artist-specific data, reduced phonetic alphabet, hardware, subjective quality, and no controlled comparison bound generalization; live usability is not a standard TTS benchmark."),
}

notes, claims = [], []
md = ["# INTERSPEECH 2025 fifty-sixth-pass full-paper notes", "", "Eight new official-PDF readings extend the lowest-coverage families with benchmark design, interpretable atypical-speech evaluation, flow enhancement, hallucination control, causal audiovisual extraction, fast TTS, parameter-space speaker generation, and interactive artistic voice generation.", ""]
labels = [("Ordinary problem", "bp"), ("Why hard", "wh"), ("Naive attempt", "naive"), ("Central move", "ap"), ("Mechanism", "mech"), ("Mathematical/conceptual structure", "math"), ("What paper reports", "ww"), ("Limits", "limits")]
for i, (pid, vals) in enumerate(N.items(), 1):
    theme, sub, concept, bp, wh, naive, ap, mech, math, ww, limits = vals
    p, c = papers[pid], captured[pid]
    note = {"paper_id": pid, "title": p["title"], "theme_id": theme, "subtheme_id": sub, "concept_id": concept,
            "bp": bp, "wh": wh, "naive": naive, "ap": ap, "mech": mech, "math": math, "eval": math,
            "ww": ww, "limits": limits, "dots": {"theme_id": theme, "subtheme_id": sub, "concept_id": concept, "sibling_family": "batch-056"},
            "source": {"kind": "official-isca-archive-paper-page-plus-captured-pdf-text", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "pdf_path": f"data/interspeech-2025-pdfs/{pid}.pdf", "text_path": c["full_text_path"]},
            "depth": "D3", "evidence_boundary": "D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}
    notes.append(note)
    claims.append({"claim_id": f"IS25-D3C56-{i:02d}", "paper_id": pid, "subtheme": sub, "claim": ww, "evidence_depth": "D3", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "support_status": "paper-reported-not-independently-verified", "independent_support_status": "not-established", "limitations": limits})
    md += [f"## {i}. {sub}", "", f"**Paper:** [{p['title']}]({p['paper_url']})", f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.", ""]
    md += [f"- **{label}:** {note[key]}" for label, key in labels] + [""]
(DATA / "interspeech-2025-fiftysixth-d3-notes.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "evidence_depth": "D3", "notes": notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-fiftysixth-claim-ledger.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "claim_count": len(claims), "claims": claims}, indent=2, ensure_ascii=False) + "\n")
REPORTS.mkdir(exist_ok=True)
(REPORTS / "INTERSPEECH_2025_FIFTYSIXTH_D3_NOTES.md").write_text("\n".join(md) + "\n")
print(json.dumps({"notes": len(notes), "claims": len(claims)}))
