"""Write first-principles notes and claims for D3 batch 059."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent; DATA, REPORTS = HERE / "data", HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftyninth-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}
N = {
 "choi25d_interspeech": ("sound-and-production","time-frequency-measurement","sampling-and-quantization","A low-bitrate codec should reconstruct useful high-frequency sound without transmitting every sample.","Conventional spectral-band replication uses coarse copies of low bands and cannot adapt well to varied acoustic signals.","Replicate subbands with a fixed rule and treat perceptual plausibility as guaranteed by the core codec.","Transmit compact high-frequency side information and generate the missing band conditioned on that information and decoded core-band audio.","An encoder-decoder quantizes high-band side information; a generative decoder reconstructs high-frequency content and adversarial criteria encourage perceptually plausible detail.","Bandwidth allocation becomes a conditional reconstruction problem: quantized evidence controls what the generator may add above the decoded core band.","With AAC as the core codec, the paper reports better perceptual quality than HE-AAC-v1 with less side information.","Core codec, side-information rate, listening metric, training data, and tested signals bound transfer; perceptual quality is not bit-exact recovery."),
 "chen25m_interspeech": ("people-variation-and-health","clinical-and-assistive-speech","dysarthria-and-atypical-speech","Dysarthric speech reconstruction should improve intelligibility while retaining the original speaker's identity.","A reconstruction can make words clearer by changing the very cues that identify the speaker, and dysarthric phonetic evidence is itself difficult to restore.","Enhance the waveform generically or optimize intelligibility alone and assume identity will survive.","Restore phoneme-level content with a self-supervised encoder, encode speaker identity separately, and condition latent diffusion generation on both.","Content and identity encoders provide complementary conditioning; the diffusion generator fills in a fluent acoustic realization constrained by the restored phoneme and speaker representations.","Assistive reconstruction is a constrained generation problem with two targets that can conflict: linguistic recoverability and person continuity.","On UASpeech, the paper reports gains in speech intelligibility and speaker similarity.","Corpus, dysarthria severity, identity metric, diffusion configuration, and listener/task definition bound transfer; benchmark gains are not clinical validation."),
 "chen25l_interspeech": ("listening-and-separation","source-separation-and-spatial-listening","spatial-filtering","A listener should extract a target sound from an ambisonic mixture when other sources overlap spatially.","Direction alone can fail when an interferer is nearby, while semantic cues may be noisy or mismatched to the acoustic target.","Use a spatial beamformer alone or condition on a text label without preserving the recorded sound field.","Condition an ambisonic-in/ambisonic-out network on target direction and semantic embeddings so spatial and scene evidence jointly guide extraction.","The model maps multichannel spherical-harmonic signals to a target field; pointing direction and image/text-derived semantics supply target conditions.","Target extraction combines geometric evidence with a prior about what the target is, especially when spatial separation is weak.","The paper reports gains over signal-processing baselines and additional benefit from combining spatial and semantic conditioning for nearby interferers.","Synthetic/real mixtures, ambisonic order, semantic embedding source, pointing accuracy, and signal metrics bound transfer; extraction quality is not scene understanding."),
 "attia25_interspeech": ("recognition-and-alignment","acoustic-unit-mapping","self-supervised-speech-units","Classroom ASR should exploit abundant noisy transcripts when only a small amount of accurate text is affordable.","Weak transcript errors can teach the recognizer systematic wrong mappings, while discarding them wastes the only scalable data source.","Train only on gold transcripts or treat every weak transcript as equally reliable ground truth.","Pretrain with weak transcripts, then fine-tune on a small accurate corpus so the final model corrects the broad noisy initialization.","Weakly supervised pretraining uses the inexpensive paired data first; supervised fine-tuning shifts the acoustic-to-token mapping toward accurate labels.","Data quality is staged rather than binary: noisy labels supply coverage, and scarce gold labels supply correction.","The paper reports that WSP outperforms alternatives on synthetic and real weak classroom transcripts.","Weak-noise process, classroom conditions, gold-data size, model family, and transcript conventions bound transfer; improvement does not establish universal weak-label safety."),
 "chou25_interspeech": ("voice-generation-and-control","voice-identity-and-conversion","voice-conversion","Emotional voice conversion should change expressive state while preserving words and speaker identity, including for unseen speakers.","Emotion, identity, and content are entangled in acoustics, so changing one can distort the others; zero-shot speakers add a distribution shift.","Train a speaker-specific converter or condition on one entangled embedding and assume emotion will change independently.","Use a zero-shot diffusion converter with disentangled content/identity mechanisms and expressive guidance for the target emotion.","Diffusion generation produces the target acoustic realization while separate conditioning paths constrain linguistic content, identity, and emotional expression.","Voice conversion is a factor-control problem: the desired change must move one latent dimension while holding other evidence stable.","The paper reports expressive speech with emotional accuracy, naturalness, and quality on unseen speakers across in- and out-of-domain data.","Emotion labels, speaker enrollment, datasets, listener protocol, and disentanglement metrics bound transfer; expressive similarity is not identity authentication."),
 "chen25_interspeech": ("people-variation-and-health","speaker-characteristics","style-and-state-variation","Speaker recognition should remain reliable when the same person ages or speaks in different emotional states.","Intrinsic state variation can be mistaken for a different identity, while synthetic augmentation can add unrealistic style cues or outliers.","Enroll one fixed speaker embedding or synthesize arbitrary variations without testing whether unknown speakers are rejected.","Tune a foundation model with few enrollment examples and use style-rich zero-shot TTS to augment time-varying and emotional speaker evidence, with outlier-aware open-set losses.","Few-shot enrollment adapts a general representation; synthetic style variation broadens within-speaker support; open-set objectives separate genuine variation from unknown identities.","Verification is a distributional decision: identity must remain stable across state changes while the rejection boundary remains open to unseen speakers.","The paper reports improved robustness across aging/emotion benchmarks and resilience to unknown outliers.","Enrollment, synthetic TTS fidelity, benchmark populations, open-set thresholds, and state coverage bound transfer; robustness is not identity proof under arbitrary conditions."),
 "chowdhury25_interspeech": ("people-variation-and-health","human-centered-evaluation","clinical-speech-marker","Behavioral speech models need features that remain reliable across tools, contexts, and demographic groups.","Open-source extractors may disagree or encode context-specific artifacts, so a downstream model can appear predictive while measuring tool behavior rather than speech behavior.","Use feature vectors from a popular tool without domain validation and interpret model performance as fair behavioral evidence.","Compare OpenSMILE and Praat feature reliability in adolescent autism recordings and test how tool variation changes models across context and demographics.","The analysis treats feature extraction as a measurement instrument: tool outputs are compared before their influence is absorbed by classifiers.","A feature is evidence only relative to its extraction instrument and population; reproducibility requires checking the measurement chain, not just the classifier.","The paper reports considerable cross-tool feature variation that changes model performance across contexts and demographic groups.","Population, clinical labels, recording conditions, tool versions, feature settings, and fairness criteria bound transfer; reliability analysis is not clinical diagnosis."),
 "chen25h_interspeech": ("languages-accents-and-resources","accent-and-cultural-boundaries","accent-robustness","Multilingual ASR evaluation should reveal failures across languages, accents, and dialects rather than hiding them in an aggregate score.","High-resource language averages can mask severe errors in varieties with little training data or different pronunciation and vocabulary norms.","Evaluate on one general multilingual test set and treat its average as inclusive coverage.","Build a 200-plus-language/variety test suite and an online challenge that exposes model design to language and dialect-specific evidence.","The benchmark separates language identification and transcription outcomes across languages, accents, and dialects, making subgroup performance visible.","Evaluation is a sampling design problem: the test suite determines which communities become measurable and which failures can be seen.","The paper reports challenge submissions improving LID and CER over baselines, including gains on accented and dialectal data.","Challenge participation, language/variety coverage, task definitions, baseline selection, and online-server protocol bound transfer; leaderboard gains are not equal service quality for every community."),
 "alexos25_interspeech": ("evaluation-and-deployment-and-consequence","robustness-and-system-boundary","security-and-misuse","Speech-enabled LLMs should resist adversarial spoken instructions that attempt to bypass safety behavior.","The speech modality adds transcription and acoustic pathways for harmful prompts, while adversarial data and compute are scarce.","Apply text-only safety fine-tuning or assume benign speech augmentation transfers to white-box attacks.","Adversarially train speech LLMs with synthesized harmful and benign speech queries, varying data configurations and testing strong white-box attacks.","The training set defines harmful/benign speech perturbations; ablations measure how attack-conditioned updates alter safety under adversarial evaluation.","Safety is a system-boundary property: the model must preserve useful speech interaction while refusing harmful content under an attacker-selected input distribution.","The paper reports relative safety improvements of 45%-300% with four hours of harmful speech plus 150 hours of benign speech in its tested models.","Attack family, synthesized speech quality, model, safety rubric, data mix, and white-box setup bound transfer; safety scores are not proof against unknown attacks."),
}
labels=[("Ordinary problem","bp"),("Why hard","wh"),("Naive attempt","naive"),("Central move","ap"),("Mechanism","mech"),("Mathematical/conceptual structure","math"),("What paper reports","ww"),("Limits","limits")]
notes=[]; claims=[]; md=["# INTERSPEECH 2025 fifty-ninth-pass full-paper notes","","Nine official-PDF readings deepen the nine subthemes that currently have the smallest D3 seed: measurement, enhancement, separation, acoustic mapping, voice conversion, speaker variation, human-centered evaluation, accent boundaries, and deployment security.",""]
for i,(pid,v) in enumerate(N.items(),1):
 theme,sub,concept,*vals=v; bp,wh,naive,ap,mech,math,ww,limits=vals; p,c=papers[pid],captured[pid]
 note={"paper_id":pid,"title":p["title"],"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"bp":bp,"wh":wh,"naive":naive,"ap":ap,"mech":mech,"math":math,"eval":math,"ww":ww,"limits":limits,"dots":{"theme_id":theme,"subtheme_id":sub,"concept_id":concept,"sibling_family":"batch-059"},"source":{"kind":"official-isca-archive-paper-page-plus-captured-pdf-text","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"pdf_path":f"data/interspeech-2025-pdfs/{pid}.pdf","text_path":c["full_text_path"]},"depth":"D3","evidence_boundary":"D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}; notes.append(note)
 claims.append({"claim_id":f"IS25-D3C59-{i:02d}","paper_id":pid,"subtheme":sub,"claim":ww,"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":limits})
 md += [f"## {i}. {sub}","",f"**Paper:** [{p['title']}]({p['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]+[f"- **{a}:** {note[b]}" for a,b in labels]+[""]
(DATA/"interspeech-2025-fiftyninth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(DATA/"interspeech-2025-fiftyninth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
REPORTS.mkdir(exist_ok=True); (REPORTS/"INTERSPEECH_2025_FIFTYNINTH_D3_NOTES.md").write_text("\n".join(md)+"\n"); print(json.dumps({"notes":len(notes),"claims":len(claims)}))
