"""Write plain-language notes and a bounded claim ledger for D3 batch 020."""
import json
from pathlib import Path

H = Path(__file__).resolve().parent; D = H / "data"; R = H / "reports"
C = {x["paper_id"]: x for x in json.loads((D / "interspeech-2025-twentieth-d3-papers.json").read_text())["papers"]}
P = {x["paper_id"]: x for x in json.loads((D / "interspeech-2025-papers.json").read_text())["papers"]}
N = {
"chang25_interspeech": {"bp":"A spoken-language model needs compact speech units that preserve phonetic content while ignoring who spoke and small recording changes.","wh":"Raw waveforms contain speaker, channel, and linguistic variation at the same time; a token that keeps all of it is hard for a language model to reuse.","naive":"Cluster acoustic frames directly and assume the most frequent clusters are good linguistic units.","ap":"Use double-codebook speaker-invariant clustering to retain phonetic structure while suppressing speaker variation, then test whether the resulting tokens are easy to model and resynthesize.","mech":"SpinHuBERT supplies the speech representation and DC-Spin separates speaker-invariant and phonetic information into codebooks; the tokens are tested in zero-shot spoken-language tasks and resynthesis.","math":"Clustering assigns nearby representation vectors to discrete symbols; speaker-invariance changes the training objective so distance caused by identity matters less than distance caused by phonetic content.","ww":"The paper reports that tokens with phoneme alignment or simple language-model structure are useful downstream and improve the tested zero-shot and resynthesis proxies.","limits":"The tokenizers, languages, proxy tasks, and resynthesis setup bound the result; token usefulness is not the same as complete spoken meaning."},
"gong25_interspeech": {"bp":"An ASR system should recognize a rare name or domain word when the user supplies a large list of likely terms.","wh":"A list of 200,000 candidates can help one word but also create homophone confusion and unacceptable search cost.","naive":"Insert the entire bias list into decoding or fine-tune the recognizer for each new list.","ap":"Retrieve a small relevant candidate set from speech and bias text, train against homophone confusion, and inject only the retrieved candidates without retraining the recognizer.","mech":"Speech-and-bias contrastive learning ranks relevant entries; a dynamic curriculum trains the system on increasingly difficult homophones; pruning then supplies a compact list to the ASR decoder.","math":"Contrastive learning pulls matching speech/list pairs together and pushes distractors apart; retrieval converts a huge candidate set into a small conditional search problem.","ww":"The paper reports 2.8%/7.1% biased WER with 2,000 words, only 0.3/2.9% absolute degradation at 200,000 entries, 99.99% pruning, and 20 ms query latency on the tested split.","limits":"The reported latency, languages, bias lists, and ASR systems define the boundary; rare names outside the retrieval distribution and interactive user correction remain open."},
"gao25g_interspeech": {"bp":"Meeting transcription must determine both what was said and which person said it when cameras, microphones, overlap, and devices disagree.","wh":"Recognition and speaker assignment fail together under overlap, and a separate audio-only pipeline cannot use visible mouth and body evidence.","naive":"Transcribe the mixed audio first and attach speaker labels afterward.","ap":"Fuse audio and video across diarization, recognition, and joint diarization-recognition tasks, then compare systems under a shared challenge protocol.","mech":"MISP 2025 defines AVSD, AVSR, and AVDR tasks with multi-device meeting data; systems combine acoustic and visual streams and are scored on speaker attribution and transcription.","math":"Diarization error counts missed, false, and incorrectly attributed speech; character error measures transcript edits; concatenated minimum-permutation error resolves arbitrary speaker-label names.","ww":"The challenge reports DER 8.09%, CER 9.48%, and cpCER 11.56% for its top systems, with the largest gain in the joint task.","limits":"Challenge data, camera placement, meeting types, language, and leaderboard protocols define the claim; deployment in unseen rooms or privacy-constrained camera settings remains open."},
"chen25o_interspeech": {"bp":"A screening system should use speech to flag possible adolescent suicide risk when interviews and expert time are limited.","wh":"Risk is continuous and multidimensional, while speech carries both acoustic behavior and what the person says; one feature family can miss the other.","naive":"Train one binary classifier on a single acoustic summary and treat its score as a clinical decision.","ap":"Combine acoustic and semantic features across several task models, then use a nested voting ensemble to stabilize the prediction.","mech":"OpenSmile and Emotion2Vec supply acoustic representations, a fine-tuned Chinese BERT supplies semantic features, and XGBoost/SVM-style base models are combined after Bayesian hyperparameter search.","math":"An ensemble votes across partially different predictors; recall and F1 expose the cost of missing risk more directly than accuracy alone.","ww":"On 600 Chinese adolescents, the paper reports test accuracy .63, recall .74, and F1 about .67.","limits":"This is a screening model on one challenge dataset, not a diagnosis or safety-tested intervention; age, language, labels, privacy, calibration, and external validation constrain the claim."},
"chang25c_interspeech": {"bp":"A videoconference system should detect moments when a group conversation becomes awkward or stops feeling enjoyable.","wh":"The moments are rare and expensive to label, and the signal is distributed across voice, face, and words.","naive":"Train a fully supervised multimodal model and label every clip.","ap":"Use a small labeled set to teach a model from a larger targeted unlabeled set through semi-supervised co-training.","mech":"Audio, facial-action, and text features are fused; modality-specific learners exchange pseudo-label information while the model is tested on held-out sessions.","math":"Co-training uses agreement between views to expand supervision; ROC-AUC measures ranking of rare events while F1 measures the chosen decision threshold.","ww":"The paper reports ROC-AUC .90 and F1 .60, and says 8% labeled data reaches 96% of the full supervised model's performance.","limits":"The labels, videoconference setting, participant population, and definition of negative experience bound the result; detection is not a causal explanation of why a conversation deteriorated."},
"ding25_interspeech": {"bp":"A cochlear-implant listener may understand speech in competing talkers differently when the target and masker use different languages.","wh":"The useful target and competing voices overlap, and the listener's hearing device changes which acoustic cues survive.","naive":"Measure speech in quiet or use one same-language masker and assume the result transfers.","ap":"Compare electric-acoustic stimulation with implant-only simulation under Mandarin, Cantonese, and English two-talker maskers.","mech":"Mandarin sentences are mixed with language-controlled babble, processed by noise vocoders simulating CI or EAS hearing, and scored through sentence recognition.","math":"Release from masking is the difference in recognition between a target with and without a linguistic advantage; comparing those differences separates hearing mode from masker language.","ww":"The study reports a combined-stimulation advantage across all three masker languages and language-specific differences in release from masking.","limits":"Normal-hearing listeners, vocoder simulations, Mandarin targets, and the selected masker languages limit direct claims about real CI users and everyday rooms."},
"ishikawa25_interspeech": {"bp":"An audio-visual model should connect what an event sounds like, what it looks like, and what language describes it without requiring every video to be manually labeled.","wh":"Unlabeled videos contain weak and sometimes misleading cross-modal matches, so training on arbitrary audio-caption pairs can teach the wrong correspondence.","naive":"Use one modality pair or trust automatically generated captions without filtering them.","ap":"Generate frame captions, filter audio-caption pairs with a CLAP similarity check, and train a text-guided contrastive masked autoencoder over audio, video, and text.","mech":"A pretrained text encoder guides masked audio-visual reconstruction and contrastive learning; automatically formed triplets are used for retrieval and classification tests.","math":"Contrastive loss pulls matching modalities together and separates mismatches; masking forces the remaining views to predict missing information rather than copy it.","ww":"The paper reports up to 5.6% recall@10 improvement for retrieval and 3.2% for classification.","limits":"The video domains, caption generator, CLAP filter, and downstream tasks define the result; spoken conversation and human annotation quality outside those videos remain open."},
"gohider25_interspeech": {"bp":"ASR should transcribe disordered and dysarthric speech rather than silently serving only speakers whose voices match ordinary training data.","wh":"Impaired speech is variable and scarce, and disfluencies can be mistaken for recognition errors or erased by a system tuned for fluent speech.","naive":"Apply a high-performing typical-speech recognizer and compare only its overall WER.","ap":"Evaluate strong contextual ASR architectures on a dedicated impaired-speech corpus and inspect whether their different context mechanisms help.","mech":"ContextNet and Parakeet are tested on Speech Accessibility Project challenge subsets; WER is compared across the challenge conditions.","math":"Word error rate counts substitutions, insertions, and deletions; it turns a listener's transcription burden into a measurable but incomplete quantity.","ww":"The paper reports WER 10.06% and 11.8% on the two test subsets, with Parakeet slightly ahead of ContextNet.","limits":"Challenge data, speaker impairment profiles, transcripts, and WER define the boundary; fairness across disorders, user control, and clinical usefulness remain unestablished."},
}
fields=["bp","wh","naive","ap","mech","math","ww","limits"]; notes=[]; claims=[]; md=["# INTERSPEECH 2025 twentieth-pass full-paper notes","","Eight additional official-PDF readings deepen distinct conceptual families. Results remain author-reported and were not independently reproduced.",""]
for i,(pid,n) in enumerate(N.items(),1):
    c=C[pid]; row=dict(n); row.update({"paper_id":pid,"title":P[pid]["title"],"subtheme":c["subtheme"]}); notes.append(row)
    md += [f"## {i}. {row['subtheme']}","",f"**Paper:** [{row['title']}]({P[pid]['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]
    labels=["Ordinary problem","Why hard","Naive attempt","Central move","Mechanism","Conceptual structure","What paper reports","Limits"]
    md += [f"- **{label}:** {row[key]}" for label,key in zip(labels,fields)] + [""]
    claims.append({"claim_id":f"IS25-D3C20-{i:02d}","paper_id":pid,"subtheme":row["subtheme"],"claim":row["ww"],"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":row["limits"]})
(D/"interspeech-2025-twentieth-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(D/"interspeech-2025-twentieth-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
R.mkdir(exist_ok=True); (R/"INTERSPEECH_2025_TWENTIETH_D3_NOTES.md").write_text("\n".join(md)+"\n")
print(json.dumps({"notes":len(notes),"claims":len(claims)}))
