#!/usr/bin/env python3
import json
from pathlib import Path

HERE=Path(__file__).resolve().parent
DATA=HERE/"data"; REPORTS=HERE/"reports"
capture={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-eleventh-d3-papers.json").read_text())["papers"]}
papers={x["paper_id"]:x for x in json.loads((DATA/"interspeech-2025-papers.json").read_text())["papers"]}
def n(s,p,b,w,na,a,m,ma,d,r,l): return {"subtheme":s,"paper_id":p,"bp":b,"wh":w,"naive":na,"ap":a,"mech":m,"math":ma,"dots":d,"ww":r,"limits":l}
notes=[
n("sound-and-production/time-frequency-measurement","bao25_interspeech","Bandwidth extension must recreate missing high-frequency speech without inventing spectral detail that listeners hear as distortion.","The missing band is not directly supervised by the degraded input; spectral errors can raise objective quality scores while changing consonant detail.","Copy low-frequency structure upward with a generic network and judge it by one waveform metric.","Use frequency-domain enhancement with an ICCRN-style recurrent representation to preserve global spectral structure while reconstructing the absent band.","The model operates on frequency representations, combines local and global context, and is compared against EBEN and other bandwidth-extension baselines.","PESQ, SI-SDR, STOI, and MUSHRA separate signal fidelity, intelligibility, and listener preference.","Bandwidth extension is an inverse problem: plausible high frequencies are constrained by the observed band and perceptual targets, not uniquely recovered.","The tests show gains over the original EBEN, including a 40-person MUSHRA comparison; the authors report clearer high-frequency detail and less distortion.","French LibriSpeech, sampling setup, listeners, and author-reported metrics bound the result; other languages remain open."),
n("listening-and-separation/echo-and-reconstruction","alradhi25_interspeech","Brain recordings may contain enough motor or auditory information to reconstruct intelligible speech for people who cannot produce it normally.","Neural signals are indirect, data are limited, and a reconstruction can be spectrally plausible yet unintelligible or unnatural.","Map neural features directly to a waveform and let a generic vocoder repair phase and prosody.","Separate linguistic/prosodic prediction from neural phase reconstruction, then use a neural vocoder and a learned MOSA evaluator.","MiSTR uses a multimodal iEEG encoder, Transformer spectrogram/prosody prediction, and a neural phase vocoder with adaptive spectral correction.","Mel-spectrogram correlation, intelligibility, naturalness, and MOSA expose different reconstruction failures; MOSA is reported at 3.38.","The system is a chain of constrained reconstructions: neural evidence determines content and prosody while the vocoder supplies waveform detail.","The paper reports higher fidelity and naturalness than listed baselines and MOSA 3.38.","Dataset, subjects, protocol, learned evaluator, and paper-reported comparisons limit clinical claims."),
n("recognition-and-alignment/adaptation-and-open-vocabulary","acevedo25_interspeech","Audio-text classifiers fail when the acoustic domain changes even if the label vocabulary stays fixed.","The text embedding can remain stable while the audio embedding moves with background and SNR.","Tune only text prompts or assume a frozen audio-text embedding is domain invariant.","Adapt the audio side using representative target-domain sound examples and test transfer across environments.","The method aligns audio representations to the target domain and compares audio-based with text-based adaptation.","Top-1 accuracy across environments and SNRs measures whether adaptation closes the modality/domain gap; the zero-shot reference is 32.4%.","Domain adaptation changes which acoustic evidence the shared representation treats as invariant while preserving the open label interface.","Audio-based adaptation gives the largest reported gains across tested conditions.","Sound set, target examples, class construction, and reported accuracy limit open-world claims."),
n("meaning-and-interaction/prosody-and-intent","ariga25_interspeech","Listeners combine segmental sounds and lexical pitch accent when recognizing Japanese words, even when the cues disagree.","The cues arrive together, priming can mask later effects, and response time does not by itself identify the updated representation.","Treat phonemes as the only lexical evidence or assume prosody simply overrides segments.","Create controlled incongruent words and use repetition priming and response timing to test each cue.","Experiments isolate cue type, delay, and lexical repetition; mixed-effects models compare segmental and prosodic conditions.","Response-time models compare conditions; the paper reports prosodic inhibition at a 750 ms interval.","Prosody is part of lexical recognition, not only an expression-layer signal.","Results suggest prosodic mispronunciation inhibits recognition at the tested delay.","Japanese materials, pitch-accent system, participants, and laboratory task limit cross-language generalization."),
n("voice-generation-and-control/text-to-speech-and-content","jeon25_interspeech","Personalized TTS for dysarthric speakers must preserve identity while producing intelligible speech from scarce and errorful recordings.","A model can improve intelligibility by erasing the speaker traits personalization is meant to retain.","Fine-tune directly on all target audio and accept overfitting or poor pronunciation.","Anchor the target speaker to a teacher model and use curriculum learning before specializing to dysarthric articulation.","A teacher-student knowledge-anchoring framework is evaluated across speaker groups with shortened audio.","PER measures intelligibility and speaker similarity measures identity; reported PER reaches 15.579 and similarity rises from 0.586 to 0.708.","Personalization is constrained transfer: move toward the target voice without transferring articulation errors as content errors.","Curriculum and anchoring lower PER and improve speaker similarity across reported groups.","Groups, language, recording conditions, and reported metrics limit clinical claims."),
n("people-variation-and-health/human-centered-evaluation","hoffner25_interspeech","ASR and humans should be compared on the same speech-in-noise task rather than assuming low WER means human-like hearing.","Human recognition depends on thresholds, spatial cues, rooms, and masking; model size changes errors without modeling those mechanisms.","Report ASR WER in clean speech as a proxy for hearing performance.","Estimate speech-reception thresholds from controlled sentences in noise for ASR models and humans.","Whisper models are tested on anechoic and spatial signals; thresholds come from WER curves at 50% error.","SRT and psychometric slope make the human-machine gap explicit rather than hiding it in average WER.","Hearing is an operating boundary shaped by scene geometry and noise, not one recognition score.","Model size improves ASR thresholds, but the gap changes with language, room, and spatial signals.","Whisper versions, German/English material, steady noise, and laboratory setup limit claims."),
n("languages-accents-and-resources/multilingual-and-crosslingual","alumae25_interspeech","A multilingual recognizer must allocate limited capacity across languages with different data sizes and acoustic demands.","Average scores hide low-resource failures; language-ID errors and subword choices can contaminate recognition.","Train one pooled recognizer and optimize aggregate CER, letting high-resource languages dominate.","Use hybrid language identification, multilingual and language-specific models, and targeted decoding resources.","The system combines language identification with multilingual ASR and customized models, then evaluates language ID and CER.","Language-ID accuracy and mean CER expose routing and transcription separately; reported values are 86.8% and 27.4%.","Multilinguality is resource allocation: the front end decides the linguistic regime before recognition specializes.","The system is competitive with challenge baselines and identifies languages needing targeted work.","Challenge data, language mix, averaging, and tuning limit all-multilingual claims."),
n("evaluation-deployment-and-consequence/robustness-and-system-boundary","alderete25_interspeech","ASR robustness should be tested on errors people actually produce, not only clean speech or synthetic noise.","Speech errors differ by type and position; aggregate WER hides which deviation caused failure.","Report one WER on spontaneous speech and treat all deviations as equivalent noise.","Use annotated SFUSED speech errors to stratify WhisperX performance by error type and word position.","The study evaluates sound and word errors with controlled classification variables and compares initial, medial, and final positions.","Accuracy by error class and position reveals interactions; sound errors are reported as easier than word errors.","Robustness is a boundary map: which linguistic deviations cross the recognizer's failure boundary, and where.","Sound errors have higher transcription accuracy than word errors, with position-dependent differences.","Database, annotations, WhisperX, language, and task design limit generalization.")]
fields=[("bp","Big picture"),("wh","Why hard"),("naive","Naive attempt"),("ap","Central move"),("mech","Mechanism"),("math","Mathematical idea"),("dots","Connections"),("ww","What paper reports"),("limits","Limits")]
out=["# INTERSPEECH 2025 eleventh-pass full-paper notes","","Eight additional official-PDF analyses deepen one first-principles branch in each major theme. Results remain author-reported and were not independently reproduced.",""]; claims=[]
for i,row in enumerate(notes,1):
 p,cap=papers[row["paper_id"]],capture[row["paper_id"]]
 out += [f"## {i}. {row['subtheme']}","",f"**Paper:** [{p['title']}]({p['paper_url']})  ",f"**Evidence:** D3; PDF SHA-256 {cap['pdf_sha256']}; {cap['page_count']} pages.",""]
 out += [f"- **{label}:** {row[key]}" for key,label in fields]+[""]
 claims.append({"claim_id":f"IS25-D3C11-{i:02d}","paper_id":row["paper_id"],"subtheme":row["subtheme"],"claim":row["ww"],"evidence_depth":"D3","pdf_sha256":cap["pdf_sha256"],"full_text_sha256":cap["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":row["limits"]})
(DATA/"interspeech-2025-eleventh-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(DATA/"interspeech-2025-eleventh-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
(REPORTS/"INTERSPEECH_2025_ELEVENTH_D3_NOTES.md").write_text("\n".join(out)+"\n")
print(json.dumps({"notes":len(notes),"report":"reports/INTERSPEECH_2025_ELEVENTH_D3_NOTES.md"}))
