#!/usr/bin/env python3
"""Record a fourth analyst-reviewed D2 batch: four abstract readings per theme."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
HERE=Path(__file__).resolve().parent; DATA=HERE/"data"
ASSIGNMENTS={
 "eads25_interspeech":("sound-and-production","source-filter-production","articulatory-coordination","The corpus pairs child speech with ultrasound articulation and is about observing how physical movement produces the acoustic error."),
 "ferrofilho25_interspeech":("sound-and-production","time-frequency-measurement","sampling-and-quantization","The paper tests how sampling rate, codecs, and far-field/noisy channels alter speaker embeddings, making the recording representation the boundary."),
 "fu25_interspeech":("sound-and-production","room-channel-and-sensing","microphone-channel","The system estimates overlapping sound locations from binaural spatial cues; microphone geometry changes the available evidence."),
 "cordlandwehr25_interspeech":("sound-and-production","room-channel-and-sensing","reverberant-mixture","The paper uses time-difference cues and microphone-array structure to segment meeting mixtures before clustering speakers."),
 "degroot25_interspeech":("listening-and-separation","noise-enhancement","speech-prior-denoising","The paper asks whether diffusion enhancement can make dysarthric speech more intelligible without erasing atypical cues needed by recognition."),
 "dong25_interspeech":("listening-and-separation","noise-enhancement","nonstationary-noise","Multitalker babble is a changing competing-speech field; the study compares human and neural listeners rather than treating it as stationary noise."),
 "cappellazzo25_interspeech":("listening-and-separation","noise-enhancement","speech-prior-denoising","Audio-visual recognition uses visual speech evidence to compensate for acoustic noise, while sparse projectors address multimodal cost."),
 "chiang25_interspeech":("listening-and-separation","echo-and-reconstruction","perceptual-enhancement","Dereverberation repairs temporal smearing especially harmful to cochlear-implant listeners; the target is intelligible speech, not merely a cleaner spectrum."),
 "bataev25_interspeech":("recognition-and-alignment","adaptation-and-open-vocabulary","domain-and-context-biasing","The contribution makes rare/context words usable in greedy ASR by changing the language-model data structure and inference cost."),
 "cai25_interspeech":("recognition-and-alignment","boundaries-and-sequence-structure","alignment","The paper evaluates whether automatic segment boundaries transfer from adult assumptions to child vowels."),
 "choi25b_interspeech":("recognition-and-alignment","acoustic-unit-mapping","self-supervised-speech-units","The paper makes discrete speech units streamable on-device by reducing full-context and extractor cost while preserving phonetic information."),
 "carta25_interspeech":("recognition-and-alignment","acoustic-unit-mapping","pronunciation-variation","A Sardinian speech-recognition corpus addresses the mapping problem when language varieties are fragmented and resources scarce."),
 "fang25b_interspeech":("meaning-and-interaction","prosody-and-intent","paralinguistic-state","Emotion labels differ by listener; the method models listener-specific interpretation rather than treating one aggregate label as universal meaning."),
 "dong25b_interspeech":("meaning-and-interaction","prosody-and-intent","prosodic-meaning","Accentedness and comprehensibility are human judgments with acoustic and recognition correlates, so the paper tests objective cues against perceived usefulness."),
 "puhach25_interspeech":("meaning-and-interaction","grounding-and-action","interactional-feedback","Speaker assignment is an explicit generated action of a speech model; gendered choices reveal how perceived voice characteristics affect behavior."),
 "heo25_interspeech":("meaning-and-interaction","dialogue-and-turn-taking","turn-boundary","The model uses gaze and speaker localization to predict who will take the next turn in triadic interaction."),
 "chen25d_interspeech":("voice-generation-and-control","voice-identity-and-conversion","voice-conversion","Singing voice conversion must change timbre while preserving melody and lyrics; dual attention and flow matching target that separation."),
 "chen25p_interspeech":("voice-generation-and-control","text-to-speech-and-content","neural-vocoder","A speech codec must compress a waveform into usable tokens and reconstruct it; mirror/non-mirror training targets reconstruction quality for TTS."),
 "fujita25_interspeech":("voice-generation-and-control","prosody-and-interactive-control","style-and-emotion-control","The paper controls subtle perceived voice impressions in zero-shot TTS, making non-linguistic style controllable rather than accidental."),
 "kim25b_interspeech":("voice-generation-and-control","text-to-speech-and-content","text-to-speech-planning","The system maps face and natural-language controls into speech while addressing low-quality audio-visual training data."),
 "cheng25d_interspeech":("people-variation-and-health","speaker-characteristics","speaker-verification","Speech unlearning treats private speaker information as something a trained model may need to remove, evaluated through membership inference."),
 "dai25b_interspeech":("people-variation-and-health","speaker-characteristics","style-and-state-variation","Target extraction conditions on relative age, pitch, language, gender, and emotion cues, treating speaker characteristics as relational evidence."),
 "chen25f_interspeech":("people-variation-and-health","speaker-characteristics","speaker-verification","The paper addresses collapse and score calibration in speaker representations without speaker labels."),
 "martinek25_interspeech":("people-variation-and-health","speaker-characteristics","style-and-state-variation","Read versus spontaneous speech changes delivery while identity remains, so the paper tests whether verification mistakes style for speaker change."),
 "carofilis25_interspeech":("languages-accents-and-resources","low-resource-and-data-creation","self-training-and-pseudo-labels","The pipeline uses small labeled in-domain data, related-domain data, and filtered pseudo-labels to adapt ASR when transcripts are scarce."),
 "chen25h_interspeech":("languages-accents-and-resources","accent-and-cultural-boundaries","accent-robustness","The benchmark includes 200+ languages, accents, and dialects so multilingual ASR claims are tested across varieties."),
 "deheerkloots25_interspeech":("languages-accents-and-resources","multilingual-and-crosslingual","crosslingual-transfer","The study asks what Dutch-specific phonetic and lexical information is present in representations trained on Dutch versus other speech."),
 "dey25_interspeech":("languages-accents-and-resources","multilingual-and-crosslingual","language-identification","Short utterances contain non-speech, names, fillers, and overlaps that make language identification ambiguous; label smoothing targets that uncertainty."),
 "hoq25_interspeech":("evaluation-deployment-and-consequence","metrics-and-targets","quality-and-naturalness","The paper predicts a distribution over listener MOS from waveform and spectrogram representations, making uncertainty part of quality evaluation."),
 "mahapatra25_interspeech":("evaluation-deployment-and-consequence","privacy-security-and-accountability","spoofing-and-deepfake","The paper tests whether emotion changes the attack surface of anti-spoofing systems, exposing a boundary hidden by neutral-only benchmarks."),
 "nguyen25e_interspeech":("evaluation-deployment-and-consequence","privacy-security-and-accountability","spoofing-and-deepfake","The study probes linguistic sensitivity of deepfake detectors, asking whether judgments survive content changes rather than only acoustic perturbations."),
 "sanders25_interspeech":("evaluation-deployment-and-consequence","metrics-and-targets","calibration-and-selective-use","The paper evaluates what compressed speech codes preserve or discard about prosody and paralinguistic state, making representation metrics answerable to human-relevant properties."),
}
source=json.loads((DATA/"interspeech-2025-papers.json").read_text())["papers"]; by={p["paper_id"]:p for p in source}; rows=[]
for pid,a in ASSIGNMENTS.items():
 p=by[pid]; abstract=p.get("abstract","")
 rows.append({"paper_id":pid,"title":p["title"],"decision":"supported","confidence":"analyst-reviewed-D2","theme_id":a[0],"subtheme_id":a[1],"concept_id":a[2],"semantic_reasoning":a[3],"evidence_fields":["bp","wh","naive","ap","mech","math","eval","ww","limits"],"evidence_excerpt":abstract[:1200],"source_location":p["paper_url"],"source_sha256":hashlib.sha256(abstract.encode()).hexdigest(),"evidence_depth":"D2","review_state":"analyst-reviewed","claim_boundary":"Abstract supports the problem and proposed conceptual move; full-paper mechanism, tables, ablations, and limitations remain unreviewed."})
payload={"schema_version":1,"batch_id":"interspeech-2025-semantic-d2-batch-003","status":"analyst-reviewed-D2-batch","claim_boundary":"These 32 assignments are analyst readings bounded by official abstracts; they do not establish full-paper mechanisms or results.","reviewed_count":len(rows),"rows":rows}
(DATA/"interspeech-2025-semantic-reviewed-d2-batch-003.json").write_text(json.dumps(payload,indent=2,ensure_ascii=False)+"\n")
print(json.dumps({"batch_id":payload["batch_id"],"reviewed_count":len(rows)}))
