#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
HERE=Path(__file__).resolve().parent; DATA=HERE/'data'
RULES={'Personal Sound Zones with Flexible Bright Zone Control':('supported','listening-and-separation','source-separation-and-spatial-listening','spatial-filtering','Personal sound zones use spatial filtering to control what a listener hears at different positions.'),'DGSDNet: Dual-Graph Spectral Diffusion Network for Incomplete Multimodal Emotion Recognition in Conversations':('supported','meaning-and-interaction','prosody-and-intent','paralinguistic-state','Emotion recognition in conversation must interpret affect when one modality is missing.'),'EEG and Eye-Tracking Driven Dynamic Target Speaker Extraction with Spontaneous Attention Switching':('supported','listening-and-separation','source-separation-and-spatial-listening','target-conditioned-separation','Target-speaker extraction uses changing attention signals to select one voice from a mixture.'),'Context-Aware Dynamic Graph Learning for Multimodal Emotion Recognition with Missing Modalities':('supported','meaning-and-interaction','prosody-and-intent','paralinguistic-state','Emotion recognition must remain meaningful when conversational modalities are incomplete.'),'Multi-Task Learning For Speech Quality Assessment Using ASR-Derived Entropy Features':('supported','evaluation-deployment-and-consequence','metrics-and-targets','quality-and-naturalness','ASR uncertainty is tested as a measurable proxy for perceived speech quality.'),'Ensemble for Reducing Target Speech Extraction Errors':('supported','listening-and-separation','source-separation-and-spatial-listening','target-conditioned-separation','An ensemble addresses failures that arise when extracting a requested speaker from a mixture.'),'Attention-Guided Audio Compression for Multimodal LLMs':('unsupported',None,None,None,'Generic audio compression does not establish a speech task from title evidence.'),'Attentive Masked Self-Distillation for Respiratory Sound Classification':('unsupported',None,None,None,'Respiratory sound classification is non-speech physiological acoustics.'),'Song-Level Audio & User-Listening Data Neural Alignment':('unsupported',None,None,None,'Song listening alignment is music rather than ordinary speech.'),'DebiasHSD: Failure-Guided Debiasing for Cross-Domain Hate Speech Detection':('unsupported',None,None,None,'Text hate-speech detection is not a speech-signal or spoken-language task.')}
papers={p['title']:p for p in json.loads((DATA/'icassp-2026-papers.json').read_text())['papers']}; rows=[]
for title,rule in RULES.items():
    if title == 'Song-Level Audio & User-Listening Data Neural Alignment': title = 'SAUNA: '+title
    p=papers.get(title)
    if not p: raise SystemExit('missing title: '+title)
    a=p.get('abstract') or ''; depth='D2' if a else 'D1'; decision,theme,subtheme,concept,reason=rule
    rows.append({'paper_id':p['paperId'],'title':title,'decision':decision,'confidence':f'analyst-reviewed-{depth}','theme_id':theme,'subtheme_id':subtheme,'concept_id':concept,'semantic_reasoning':reason,'evidence_excerpt':a[:1000] if a else title,'source_location':p.get('url'),'source_sha256':hashlib.sha256(a.encode()).hexdigest(),'evidence_depth':depth,'review_state':'analyst-reviewed','claim_boundary':'ICASSP title/abstract evidence supports only broad membership or bounded rejection; full-paper mechanism and results are not captured.'})
payload={'schema_version':1,'batch_id':'icassp-2026-semantic-batch-017','status':'analyst-reviewed-title-bounded-mixed-batch','claim_boundary':'Ten records are analyst-reviewed from ICASSP title/abstract evidence; assignments are not full-paper analyses.','reviewed_count':len(rows),'rows':rows}
(DATA/'icassp-2026-semantic-reviewed-batch-017.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False)+'\n'); print(json.dumps({'batch_id':payload['batch_id'],'reviewed_count':len(rows),'supported':sum(x['decision']=='supported' for x in rows),'unsupported':sum(x['decision']=='unsupported' for x in rows)}))
