"""Write first-principles notes and claims for D3 batch 057."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA, REPORTS = HERE / "data", HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftyseventh-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}
N = {
"zezario25_interspeech": ("people-variation-and-health", "human-centered-evaluation", "accessibility-fit", "A hearing-aid system needs an intelligibility estimate without asking a listener to score every noisy utterance.", "Human scores are expensive, while acoustic features, learned representations, and hearing-aid conditions expose different parts of the perceptual problem.", "Feed one feature family into a regressor and treat its error as a complete measure of intelligibility.", "Estimate frame-level importance across spectral, temporal, and Whisper latent features, project each domain through those weights, and fuse them in an assessment model.", "FiDo produces domain-specific weighted representations before concatenation and regression; RMSE on intelligibility targets evaluates whether the weighting preserves listener-relevant evidence.", "Feature selection is moved inside the representation: the model learns which moments and domains matter before the final proxy prediction.", "The paper reports that FiDo reduces MBI-Net+ RMSE from 26.10 to 24.11 and improves over the best 2023 Clarity Prediction Challenge system.", "Weakly supervised targets, hearing-aid/noise conditions, challenge split, proxy RMSE, and absence of a new listener study bound the claim; prediction is not equivalent to real-world access improvement."),
"onda25b_interspeech": ("languages-accents-and-resources", "accent-and-cultural-boundaries", "accent-robustness", "Training and listening materials should expose learners and recognizers to foreign accents that are scarce in native-speech corpora.", "Accent changes segmental realization and rhythm; a system that changes only discrete phonetic tokens can miss duration patterns characteristic of the speaker’s first language.", "Use native speech unchanged or resynthesize token content without modeling timing, then call the result an accent simulation.", "Add explicit duration modification to discrete-token resynthesis so native speech can approximate durational foreign-accent cues without accented training data.", "Self-supervised discrete units preserve linguistic content, while duration controls alter timing before the units are rendered by a decoder; real L2 speech supplies the comparison target.", "Accent simulation is a structured transformation: content units should stay stable while temporal realization changes in a language-specific way.", "The paper reports that the enhanced method reproduces durational accents observed in real L2 speech.", "Accent languages, speakers, duration estimator, perceptual validation, and native-corpus assumptions bound transfer; acoustic similarity is not proof of improved ASR or pedagogy."),
"lay25_interspeech": ("listening-and-separation", "noise-enhancement", "online-enhancement", "Live communication needs speech enhancement while the signal is still arriving, with latency small enough for interaction.", "Diffusion models can restore complex distributions but normally require many iterative steps and future context, conflicting with streaming constraints.", "Run an offline diffusion enhancer or use a fast deterministic model that sacrifices generative restoration quality.", "Use a sliding buffer whose corruption schedule gives more noise to frames near the present, then denoise older frames with a controlled delay.", "The buffer defines a causal-to-delayed window; diffusion steps operate on that window and output frames once their future context is sufficient.", "Latency becomes a tunable information budget: a larger buffer gives the score-based model more context while increasing input-output delay.", "The paper reports better results than standard diffusion baselines and GPU input-output latency around 0.3–1 seconds.", "GPU/hardware assumptions, buffer size, noise mixtures, real-time scheduling, and perceptual metrics bound the result; a reported latency range is not a full conversational user study."),
"okabe25_interspeech": ("evaluation-and-deployment-and-consequence", "robustness-and-system-boundary", "latency-and-resource", "An ASR decoder should approach autoregressive accuracy without paying for every sequential token decision.", "Non-autoregressive guesses are fast but can lose accuracy, while autoregressive search repeatedly computes scores for hypotheses that are already predictable.", "Choose either full autoregressive beam search or a non-autoregressive decoder and accept the speed-accuracy tradeoff.", "Combine simultaneous masked/unmasked decoding with speculative masking so confidently predictable hypotheses skip unnecessary decoder computation.", "Preliminary masked decisions identify positions whose score computation can be omitted; the remaining positions retain the autoregressive search path and its result.", "The method exploits conditional redundancy in sequence search: computation is spent where uncertainty remains rather than uniformly at every token.", "On TED-LIUM2, the paper reports WER 7.3% for both the proposed and autoregressive systems, with RTF 0.41 versus 0.59.", "One corpus/model, beam and hardware settings, confidence thresholds, and real-time measurement protocol bound transfer; equal WER on one test set does not prove universal speed preservation."),
"navon25_interspeech": ("listening-and-separation", "source-separation-and-spatial-listening", "target-conditioned-separation", "A listener should extract one enrolled speaker from a mixture even when interference is severe or unseen.", "Discriminative masks can create artifacts and fail under distribution shift, while generative pipelines often require multiple pretrained components and poor phase reconstruction.", "Map the mixture directly to a mask or waveform with a large pipeline, ignoring the enrolled speaker’s distribution and phase evidence.", "Condition flow matching on enrollment and mixture mel-spectrograms, and condition a vocoder on the mixture’s complex STFT when phase matters.", "A learned flow transports a noisy conditional distribution toward target speech; complex-STFT conditioning supplies phase information that mel features discard.", "Target extraction is conditional generation under an identity constraint, with magnitude and phase treated as complementary evidence.", "The paper reports that FlowTSE matches or outperforms strong target-speaker-extraction baselines on standard benchmarks.", "Enrollment quality, speaker/noise shift, phase-vocoder design, benchmark mixtures, and signal metrics bound transfer; extraction quality is not automatically improved ASR or hearing-aid benefit."),
"lu25b_interspeech": ("voice-generation-and-control", "text-to-speech-and-content", "text-to-speech-planning", "Zero-shot TTS should preserve a speaker’s identity when the few-second audio prompt is noisy.", "Noise corrupts acoustic tokens and can cause an LLM-based TTS system to copy the environment or plan the wrong voice, while ordinary enhancement may not match token-level prompts.", "Enhance the prompt with a generic speech enhancer or trust the noisy codec tokens as if they represented clean speaker evidence.", "Denoise the first acoustic-token groups with a neural codec token predictor, refine the embedding, and use the cleaned prompt in LauraTTS.", "The token denoiser predicts clean coarse tokens; an embedding refiner and codec decoder reconstruct usable acoustic evidence before the zero-shot TTS model conditions generation.", "Denoising at the representation used for prompting aligns the cleanup objective with the generator’s actual conditioning interface.", "The paper reports that its codec denoiser outperforms speech-enhancement baselines and that noise-robust LauraTTS improves over adding an external enhancer.", "Noise types, prompt duration, speaker overlap, codec/model version, and zero-shot evaluation bound transfer; clean synthesis from a prompt is not speaker-authenticated identity preservation."),
"lobashev25_interspeech": ("voice-generation-and-control", "voice-identity-and-conversion", "voice-conversion", "Any-to-any voice conversion should change identity from a short reference while preserving the source linguistic content, including across languages.", "Nearest-neighbor replacement needs long reference recordings and can import language-specific artifacts; training a new converter per speaker defeats the any-to-any goal.", "Replace each source embedding with its closest target embedding and assume five minutes of reference speech is always available.", "Replace nearest-neighbor matching with a factorized optimal-transport map in WavLM embedding subspaces, requiring only a short reference.", "Monge–Kantorovich linear transport aligns source and target feature distributions; factorization normalizes unequal variances before the encoder-converter-vocoder reconstructs speech.", "Optimal transport matches distributions rather than individual frames, allowing sparse reference evidence to define a target voice without storing a lookup for every source sound.", "MKL-VC reports improved content preservation and short-reference robustness on LibriSpeech and FLEURS, with cross-lingual performance comparable to FACodec.", "Reference duration, WavLM space, languages, vocoder, speaker similarity metric, and implementation choices bound transfer; content preservation does not prove perfect identity conversion."),
"yazawa25_interspeech": ("people-variation-and-health", "human-centered-evaluation", "listener-effort", "Fluency ratings of second-language speech should reflect both the speaker’s temporal behavior and the listener’s linguistic background.", "Listeners disagree, and native-listener norms may not transfer to nonnative listeners; rate, pauses, and repairs are correlated rather than independent cues.", "Average all ratings or use a single syllable-rate predictor and treat the resulting score as a universal fluency scale.", "Use a Bayesian hierarchical model to separate listener variability from utterance-level fluency cues and compare syllable- versus segment-based articulation rate.", "Posterior distributions represent listener-specific leniency and cue weights; speed, breakdown, and repair features explain ratings while uncertainty remains explicit.", "Human evaluation is a multilevel measurement problem: the score is jointly produced by the speech sample and the observer’s perceptual prior.", "Using 16 listeners and 180 Japanese speakers in J-AESOP, the paper reports greater leniency among some nonnative listeners and stronger fit for segment-based articulation rate.", "Listener sample, language backgrounds, trained-rating task, corpus, feature definitions, and Bayesian priors bound transfer; fluency ratings are not a complete measure of communicative success."),
}
notes, claims = [], []
md = ["# INTERSPEECH 2025 fifty-seventh-pass full-paper notes", "", "Eight new official-PDF readings extend accessibility evaluation, accent simulation, online enhancement, efficient decoding, target extraction, noise-robust TTS, training-free conversion, and listener-aware fluency measurement.", ""]
labels = [("Ordinary problem", "bp"), ("Why hard", "wh"), ("Naive attempt", "naive"), ("Central move", "ap"), ("Mechanism", "mech"), ("Mathematical/conceptual structure", "math"), ("What paper reports", "ww"), ("Limits", "limits")]
for i, (pid, vals) in enumerate(N.items(), 1):
    theme, sub, concept, bp, wh, naive, ap, mech, math, ww, limits = vals
    p, c = papers[pid], captured[pid]
    note = {"paper_id": pid, "title": p["title"], "theme_id": theme, "subtheme_id": sub, "concept_id": concept, "bp": bp, "wh": wh, "naive": naive, "ap": ap, "mech": mech, "math": math, "eval": math, "ww": ww, "limits": limits, "dots": {"theme_id": theme, "subtheme_id": sub, "concept_id": concept, "sibling_family": "batch-057"}, "source": {"kind": "official-isca-archive-paper-page-plus-captured-pdf-text", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "pdf_path": f"data/interspeech-2025-pdfs/{pid}.pdf", "text_path": c["full_text_path"]}, "depth": "D3", "evidence_boundary": "D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}
    notes.append(note)
    claims.append({"claim_id": f"IS25-D3C57-{i:02d}", "paper_id": pid, "subtheme": sub, "claim": ww, "evidence_depth": "D3", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "support_status": "paper-reported-not-independently-verified", "independent_support_status": "not-established", "limitations": limits})
    md += [f"## {i}. {sub}", "", f"**Paper:** [{p['title']}]({p['paper_url']})", f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.", ""] + [f"- **{label}:** {note[key]}" for label, key in labels] + [""]
(DATA / "interspeech-2025-fiftyseventh-d3-notes.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "evidence_depth": "D3", "notes": notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-fiftyseventh-claim-ledger.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "claim_count": len(claims), "claims": claims}, indent=2, ensure_ascii=False) + "\n")
REPORTS.mkdir(exist_ok=True)
(REPORTS / "INTERSPEECH_2025_FIFTYSEVENTH_D3_NOTES.md").write_text("\n".join(md) + "\n")
print(json.dumps({"notes": len(notes), "claims": len(claims)}))
