"""Write no-jargon notes for D3 batch 027."""
import json
from pathlib import Path
H=Path(__file__).resolve().parent;D,R=H/"data",H/"reports"
C={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-twentyseventh-d3-papers.json").read_text())["papers"]};P={x["paper_id"]:x for x in json.loads((D/"interspeech-2025-papers.json").read_text())["papers"]}
N={
"li25v_interspeech":("A speech recognizer must fit on a device with limited memory while retaining the behavior of a much larger model.","A separately compressed model can lose accuracy, while storing many depth variants defeats the memory goal.","Train one large model and prune or distill it after the fact into one fixed size.","Train a small seed network and unfold it along multiple logical depths, using self-distillation to keep the paths consistent.","A compact Conformer or Transformer seed is repeatedly unfolded during joint training and compared with larger Conformer and wav2vec2/HuBERT systems.","Depth becomes a reusable path through shared parameters; KL divergence constrains the smallest and largest paths so compression is measured against performance, storage, and model depth.","The foldable model reduces Conformer parameters by 35% and speech-foundation parameters by 30% without reported performance loss across depth configurations.","The architectures, training data, depth choices, and compression comparisons bound the claim; parameter reduction is not the same as lower device latency or energy."),
"wan25_interspeech":("An audio codec for a streaming device must compress speech into a small code while operating with little computation and little delay.","Heavy neural codecs may compress well but require too many parameters or operations for a real-time device.","Take a large offline codec and accept its compute cost, or reduce layers without changing the representation domain.","Operate in a compressed spectral domain and combine lightweight convolutional and recurrent layers at multiple time scales.","SpecTokenizer is a streaming single-codebook codec evaluated at 4 kbps against a lightweight codec under matched computation and storage budgets.","The codec trades waveform detail for discrete codes; bitrate, reconstruction quality, computation, and parameter count expose the deployment boundary.","At 4 kbps it reports comparable or better performance with 20% of the computation and 10% of the parameters of the comparison codec.","Bitrate, audio material, hardware, streaming definition, and quality measure bound the claim; benchmark efficiency does not prove end-to-end device power or user benefit."),
"xu25c_interspeech":("An RNN-T recognizer must decide quickly when a frame contains a label, but sequentially inspecting every frame wastes time when most frames are blank.","Parallelizing blindly can change the order-dependent decoder state and harm word accuracy.","Run the original sequential decoder faster in isolation or process every frame in a large batch without respecting non-blank decisions.","Inspect a window of frames in parallel to locate non-blank predictions, then retain decoder logic around the informative positions for greedy and beam search.","WIND is evaluated on multiple datasets with greedy, batched greedy, and beam-search RNN-T decoding against sequential baselines.","The method exploits sparsity in the label stream; speedup is meaningful only when WER remains unchanged and the decoding mode is specified.","Greedy modes reach up to 2.4x speedup with identical WER, while the proposed beam search is faster and slightly more accurate than alternatives.","RNN-T models, datasets, hardware, window size, and decoding modes bound the result; reported speedup is not portable to every implementation or workload."),
"xu25e_interspeech":("A speech foundation model may be accurate but too large to deploy, so its unused capacity must be removed without damaging recognition.","Pruning after training can be expensive and can remove units that are useful only in combination with others.","Prune fixed layers with a hand rule or compress the model in a separate stage after all training is finished.","Learn a small gate for each layer during training and let the gates pinch off underused neurons while model parameters are updated at the same time.","Self-pinching gates are trained with wav2vec2.0-base and HuBERT-large and then drive fine-grained neuron pruning on LibriSpeech-100hr.","A gate is a learned resource-allocation decision; parameter count, WER, compression ratio, and compression time measure the accuracy-efficiency frontier.","The method removes 65% of wav2vec2.0-base and 60% of HuBERT-large parameters without a statistically significant test-clean WER increase, with 7.05% WER at 4.26x compression.","LibriSpeech, model variants, pruning thresholds, and test-clean evaluation bound the result; no claim follows about noisy conditions, energy, or other languages."),
"xu25i_interspeech":("An ASR model has a fixed training budget, but not every part of its architecture uses that budget equally well.","Hand-designed architectures require expertise, while neural architecture search can spend more computation searching than training the final model.","Choose one repeated block structure before training or run an expensive search over many complete models.","Grow useful parts and drop less useful parts during training, reallocating parameters while keeping the total model complexity and training resources fixed.","DMAO is evaluated with CTC on LibriSpeech, TED-LIUM-v2, and Switchboard across architectures and model sizes.","The architecture becomes a changing allocation of parameters; relative WER at matched resources tests whether reallocation, rather than extra capacity, creates the gain.","The paper reports up to roughly 6% relative WER improvement across datasets, architectures, and sizes with negligible added training overhead.","Datasets, CTC setup, compute budget, search rules, and final architecture bound the result; a benchmark gain does not establish optimality or universal resource allocation."),
"yang25i_interspeech":("A short glide between a consonant and vowel must be assigned to a syllable position, but timing can make it look like an onset, a nucleus, or a separate segment.","Abstract phonological structure is not directly visible in the waveform, and competing analyses can fit the same sequence of labels.","Choose an onset or rime analysis from spelling, phonotactics, or a single duration measurement.","Measure the timing coordination of consonant-glide-vowel sequences and use the relative movement of gestures to infer which part of the syllable the glide behaves like.","Hefei Mandarin CjV and CwV syllables are analyzed acoustically, comparing glide timing with competing onset and rime accounts.","The acoustic trajectory is evidence about an abstract structure; temporal coordination links measurable events to a phonological hypothesis without treating labels as observations.","The paper finds that both glides are more likely part of the rime, agreeing with prior evidence for [j] but differing from earlier results for [w].","The dialect, speakers, acoustic method, and competing analyses bound the inference; timing alone cannot settle every phonological representation or generalize across Mandarin varieties."),
}
keys=["bp","wh","naive","ap","mech","math","ww","limits"];notes=[];claims=[];md=["# INTERSPEECH 2025 twenty-seventh-pass full-paper notes","","Six official-PDF readings form a deployment family around shared parameters, streaming, decoding sparsity, pruning, dynamic architecture, and one acoustic-to-phonological inference. Results are author-reported and not independently reproduced.",""]
for i,(pid,values) in enumerate(N.items(),1):
 d=dict(zip(keys,values));c=C[pid];d.update({"paper_id":pid,"title":P[pid]["title"],"subtheme":c["subtheme_label"]});notes.append(d);md += [f"## {i}. {d['subtheme']}","",f"**Paper:** [{d['title']}]({P[pid]['paper_url']})",f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.",""]+[f"- **{label}:** {d[key]}" for label,key in zip(["Ordinary problem","Why hard","Naive attempt","Central move","Mechanism","Conceptual structure","What paper reports","Limits"],keys)]+[""]
 claims.append({"claim_id":f"IS25-D3C27-{i:02d}","paper_id":pid,"subtheme":d["subtheme"],"claim":d["ww"],"evidence_depth":"D3","pdf_sha256":c["pdf_sha256"],"full_text_sha256":c["full_text_sha256"],"support_status":"paper-reported-not-independently-verified","independent_support_status":"not-established","limitations":d["limits"]})
(D/"interspeech-2025-twentyseventh-d3-notes.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","evidence_depth":"D3","notes":notes},indent=2,ensure_ascii=False)+"\n")
(D/"interspeech-2025-twentyseventh-claim-ledger.json").write_text(json.dumps({"venue":"INTERSPEECH 2025","claim_count":len(claims),"claims":claims},indent=2,ensure_ascii=False)+"\n")
R.mkdir(exist_ok=True);(R/"INTERSPEECH_2025_TWENTYSEVENTH_D3_NOTES.md").write_text("\n".join(md)+"\n");print(json.dumps({"notes":len(notes),"claims":len(claims)}))
