#!/usr/bin/env python3
"""Write first-principles notes for the ninth captured D3 set."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPORTS = HERE / "reports"
capture = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-ninth-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

def note(subtheme, pid, bp, wh, naive, ap, mech, math, dots, ww, limits):
    return {"subtheme": subtheme, "paper_id": pid, "bp": bp, "wh": wh, "naive": naive, "ap": ap, "mech": mech, "math": math, "dots": dots, "ww": ww, "limits": limits}

notes = [
    note("recognition-and-alignment/acoustic-unit-mapping", "ahn25_interspeech", "A recognizer trained on clean speech should still map noisy speech to words.", "Noise changes acoustic statistics and can be mistaken for speech units.", "Add noise only during fine-tuning and hope the representation stays stable.", "Add variance, invariance, and covariance constraints during HuBERT pretraining.", "HuBERT-VIC applies VICReg terms to noisy representations and compares masked prediction with regularizer ablations on MUSAN-noised LibriSpeech.", "The reported target is WER; relative gains are 23.3% on test-clean and 13.2% on test-other against the noisy-pretrained baseline.", "Noise robustness is changed at the representation level before recognition, not only by filtering the final waveform.", "All three regularizers give the best reported WER and show complementary ablation effects.", "MUSAN, SNR choices, HuBERT, and LibriSpeech bound the result; real conversational noise is not established."),
    note("languages-accents-and-resources/accent-and-cultural-boundaries", "bai25_interspeech", "Accent normalization should change pronunciation while keeping the same speaker recognizable.", "Changing accent can also change timbre, duration, intelligibility, or words, and parallel data are scarce.", "Convert frames one by one using paired data and accept timing and identity drift.", "Use self-supervised discrete tokens, nonparallel conversion, flow matching, and explicit duration preservation.", "The system extracts source tokens, predicts target-accent tokens, synthesizes waveform output, and evaluates several English accents.", "NAT, ACT, SIM, WER, SECS, F0 correlation, and feature distance separately measure naturalness, accent, content, identity, and prosody.", "The desired change is pronunciation rather than erasure of the speaker, making accent a boundary between language and identity.", "The system beats a frame-to-frame baseline on naturalness, accentedness, and timbre preservation, but post-conversion WER remains high.", "Accent definitions, targets, subjective judgments, and nonparallel training bound the claim; native-like is not universally better."),
    note("listening-and-separation/noise-enhancement", "b25_interspeech", "Speech enhancement should run on a device that cannot afford a large neural network.", "Small models lose detail while large models exceed latency and memory limits.", "Compress one large network until it runs fast, even if its structure becomes opaque.", "Replace one expensive DNN with simpler hierarchical predictors backed by structured speech-parameter codebooks.", "Hierarchically clustered log-power-spectrum vectors drive codebook stages and enhancement predictors evaluated on VoiceBank-DEMAND.", "The paper compares SSNR and computational cost; codebook classifiers use cross-entropy and the table reports parameter/runtime burden.", "This is compression by exploiting speech structure, linking deployment constraints to representation choice.", "The framework reduces computation while retaining comparable or improved enhancement scores over the reference systems.", "One corpus and parameterized spectral targets bound the evidence; downstream ASR and perceptual benefit are not fully established."),
    note("sound-and-production/room-channel-and-sensing", "cordlandwehr25_interspeech", "Meeting transcription needs to know who spoke when despite overlap and movement.", "Position is not permanent identity when people move, while a single microphone loses direction information.", "Use speaker embeddings alone or permanently map one direction to one speaker.", "Segment with time-difference-of-arrival cues, cluster speaker embeddings, and combine spatial and spectral evidence.", "TDOA detects regions, embeddings assign speakers, cACGMM optionally refines them, and compact/distributed microphone setups are tested.", "DER measures segmentation/assignment and cpWER measures transcript performance after diarization.", "Room geometry is evidence, but position is not treated as identity; this is a core room-channel boundary.", "The combined pipeline outperforms single-channel pyannote in reported compact and distributed meeting scenarios.", "Layouts, datasets, overlap, and spatial cues bound the result; evaluations are author-reported."),
    note("people-variation-and-health/clinical-and-assistive-speech", "botelho25_interspeech", "Speech may contain signs of cognitive decline, but health signals must be separated from topic and class imbalance.", "Clinical labels are scarce, the dementia class is small, and acoustic and linguistic evidence can disagree.", "Choose one embedding or optimize overall accuracy.", "Combine acoustic, linguistic, knowledge-based, and neural representations, selecting complementary class-aware systems.", "PROCESS Challenge systems combine acoustic features, text features, LLM descriptors, Longformer, ECAPA-TDNN, and TRILLsson embeddings across three tasks.", "The study emphasizes UAF1 and class-specific F1 rather than accuracy alone.", "A clinical marker is meaningful only when the evaluation protects the rare class and controls confounds.", "Selected ensembles provide the strongest reported balance across train/development data and individual classes.", "Challenge data, demographic overlap, and missing metadata limit the claim; this is not clinical validation."),
    note("voice-generation-and-control/prosody-and-interactive-control", "cho25b_interspeech", "Emotion transfer should change delivery without replacing the target speaker's identity.", "Emotion and timbre are entangled, so an emotion embedding can leak the reference speaker.", "Copy speaker and emotion embeddings into TTS without testing information leakage.", "Distill speaker-independent emotion representations with cluster sampling, perturbation, and separate style/identity conditioning.", "DiEmo-TTS clusters emotion attributes, matches speaker/emotion examples, distills representations, and uses a dual-conditioning transformer.", "Naturalness, speaker similarity, emotion similarity, WER/CER, and embedding scores measure different goals; ablations remove distillation components.", "The mechanism is disentanglement: retain vocal identity while moving the emotional control variable.", "The reported system improves emotion and speaker-related measures in the chosen experiments.", "Pretrained encoders, datasets, subjective measures, and cross-speaker coverage bound the conclusion."),
    note("evaluation-deployment-and-consequence/privacy-security-and-accountability", "chen25j_interspeech", "Detecting fake speech says it is synthetic; tracing its source can explain which generator family produced it.", "Codec generators share stages, so a detector can learn dataset artifacts instead of source evidence.", "Train a binary fake detector and treat attribution as the same task with more labels.", "Organize neural codecs into a taxonomy and use codec-related auxiliary objectives for source tracing.", "Multi-task systems on CodecFake+ use codec quantization, auxiliary codec tasks, and balanced source-tracing experiments.", "F1 is reported for vector-quantization, auxiliary, and decoder/source tasks; the best cited DEC F1 is 46.45%.", "The security move is toward contestable provenance, not merely a fake/real label.", "CodecFake+ gives initial evidence that codec taxonomy helps source tracing and that balance affects generalization.", "The dataset and generator coverage bound the result; 46.45% F1 is not reliable attribution."),
    note("meaning-and-interaction/grounding-and-action", "puhach25_interspeech", "A speech model that chooses a voice can reveal social associations even when text does not request gender.", "Speech generation makes an implicit association audible through selected speaker identity.", "Evaluate TTS only for naturalness and intelligibility.", "Probe default speaker assignment with controlled profession and gender-colored-word prompts.", "Bark is prompted with two constructed datasets and assignments are counted for gender alignment and inclinations.", "The controlled assignment counts are an association probe, not population prevalence or a human perception study.", "A generated voice is a social action, so voice identity belongs in accountability analysis.", "Bark shows gender awareness and some inclinations but no strong systematic bias under the tested prompts.", "Two datasets, one model, prompt wording, and supported voices bound the conclusion; this is not a fairness guarantee."),
]
fields = [("bp", "Big picture"), ("wh", "Why hard"), ("naive", "Naive attempt"), ("ap", "Central move"), ("mech", "Mechanism"), ("math", "Mathematical idea"), ("dots", "Connections"), ("ww", "What paper reports"), ("limits", "Limits")]
out = ["# INTERSPEECH 2025 ninth-pass full-paper notes", "", "Eight additional official-PDF analyses deepen recognition, accent, enhancement, room diarization, clinical speech, expressive synthesis, spoof tracing, and bias accountability. Results remain author-reported and were not independently reproduced.", ""]
claims = []
for i, row in enumerate(notes, 1):
    paper, cap = papers[row["paper_id"]], capture[row["paper_id"]]
    out += [f"## {i}. {row['subtheme']}", "", f"**Paper:** [{paper['title']}]({paper['paper_url']})  ", f"**Evidence:** D3; PDF SHA-256 {cap['pdf_sha256']}; {cap['page_count']} pages.", ""]
    out += [f"- **{label}:** {row[key]}" for key, label in fields] + [""]
    claims.append({"claim_id": f"IS25-D3C9-{i:02d}", "paper_id": row["paper_id"], "subtheme": row["subtheme"], "claim": row["ww"], "evidence_depth": "D3", "pdf_sha256": cap["pdf_sha256"], "full_text_sha256": cap["full_text_sha256"], "support_status": "paper-reported-not-independently-verified", "independent_support_status": "not-established", "limitations": row["limits"]})
(DATA / "interspeech-2025-ninth-d3-notes.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "evidence_depth": "D3", "notes": notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-ninth-claim-ledger.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "claim_count": len(claims), "claims": claims}, indent=2, ensure_ascii=False) + "\n")
(REPORTS / "INTERSPEECH_2025_NINTH_D3_NOTES.md").write_text("\n".join(out) + "\n")
print(json.dumps({"notes": len(notes), "report": "reports/INTERSPEECH_2025_NINTH_D3_NOTES.md"}))
