"""Write first-principles notes for D3 batch 051."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REPORTS = HERE / "reports"
captured = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-fiftyfirst-d3-papers.json").read_text())["papers"]}
papers = {x["paper_id"]: x for x in json.loads((DATA / "interspeech-2025-papers.json").read_text())["papers"]}

N = {
"chen25l_interspeech": ("listening-and-separation", "source-separation-and-spatial-listening", "spatial-filtering", "A listener should be able to extract a selected sound from an ambisonic scene using both where it is and what it is.", "The target direction is continuous while semantic cues are uncertain; spatial-only extraction can confuse co-located or reverberant sources and semantic-only cues ignore acoustic geometry.", "Apply one fixed beamformer or condition a monaural extractor on a text label without modeling the multichannel sound field.", "Condition an ambisonic-in/ambisonic-out extractor jointly on target direction and semantic embeddings, and test whether the cues complement one another.", "The network maps multichannel ambisonic mixtures to a target sound field; direction and image-derived semantic embeddings guide the mask or representation used for extraction.", "Spatial filtering and semantic conditioning define complementary constraints: the output must preserve the target's spatial structure while suppressing other sources.", "SoundSculpt outperforms the reported signal-processing baselines on synthetic and real ambisonic mixtures, with joint spatial-semantic conditioning helping in difficult cases.", "Synthetic scene construction, ambisonic order, semantic detector quality, room conditions, and target definition bound transfer; benchmark improvement is not guaranteed perceptual source isolation in arbitrary rooms."),
"guzik25_interspeech": ("listening-and-separation", "source-separation-and-spatial-listening", "spatial-filtering", "A microphone array should capture a desired direction without high-frequency spatial aliasing destroying beamformer accuracy.", "Sparse or widely spaced arrays create directional ambiguity above the aliasing frequency, while an adaptive correction must preserve useful cross-channel phase and remain computationally practical.", "Use a conventional beamformer unchanged, or apply a generic post-filter that ignores the array geometry and signal dependence.", "Predict a signal-dependent de-aliasing filter with a U-Net and apply it to conventional beamforming, comparing independent-channel and cross-channel designs.", "The model estimates a filter from multichannel spectro-temporal input; the corrected beamformer output is evaluated in common spatial-capture scenarios against conventional and learned alternatives.", "The learned filter approximates an inverse of geometry-induced aliasing, but its validity depends on the array and acoustic distribution represented during training.", "The paper reports reduced spatial aliasing and improved spatial/spectral capture measures for the proposed deep-learning correction in the tested scenarios.", "Array geometry, source locations, reverberation, training mixtures, and scenario coverage constrain generalization; simulated or benchmark gains do not establish robustness for every microphone layout."),
"kim25b_interspeech": ("voice-generation-and-control", "text-to-speech-and-content", "text-to-speech-planning", "A controllable TTS system should synthesize a plausible voice from a face image and obey natural-language descriptions of speaking style and acoustic conditions.", "Face-driven corpora are limited in audio quality, artistic portraits differ from real faces, and controls such as pace, distance, tone, and noise interact rather than forming independent knobs.", "Train only on paired face-audio data and expose separate hand-tuned controls that do not generalize beyond the training corpus.", "Augment face-driven training with high-quality audio-only speech, stylize face inputs to cover artistic portraits, and condition synthesis on natural-language control descriptions.", "The face encoder supplies speaker or voice information, while text conditioning specifies controllable attributes; multi-modal training aligns these conditions with waveform generation.", "The system treats identity and controllable acoustic attributes as separate but compositional conditioning variables, evaluated through speech quality, similarity, and control-following tests.", "Revival with Voice reports controllable synthesis from real and artistic face inputs and improved use of high-quality audio-only data in the tested settings.", "Face distribution, language, control wording, subjective protocol, and disentanglement assumptions limit the claim; controllability is not proof of identity fidelity or safe use of a person's likeness."),
"kaneko25b_interspeech": ("voice-generation-and-control", "text-to-speech-and-content", "neural-vocoder", "Waveform-generating models need an adversarial signal that rewards perceptual detail without making training prohibitively expensive.", "Time-domain discrimination after waveform upsampling consumes memory and computation, while compact acoustic features can hide artifacts that appear after vocoding.", "Discriminate only mel or acoustic features, or run a full waveform discriminator at every training step despite the cost.", "Project generated acoustic features through a vocoder and discriminate in a vocoder-feature space, retaining waveform-relevant feedback with lower time-domain overhead.", "The vocoder-projected feature discriminator compares feature representations after synthesis; diffusion-based voice-conversion distillation tests whether the adversarial target improves the generated waveform.", "The discriminator changes the metric space rather than the generator's output target: it seeks features that preserve vocoder-relevant waveform distinctions while avoiding repeated raw-waveform processing.", "The paper reports improved diffusion-based VC distillation quality from the projected-feature discriminator under the evaluated settings.", "Vocoder choice, feature projection, training compute, VC data, and perceptual evaluation determine the result; a reported quality gain does not establish universal TTS or VC superiority."),
"blaschke25_interspeech": ("languages-accents-and-resources", "accent-and-cultural-boundaries", "dialect-and-variety", "Speech technology should measure and translate German dialect variation rather than treating Standard German as the only valid target.", "Dialect differences affect both acoustic realization and lexical/transcription conventions, and models can appear accurate while erasing the variety in translation to Standard German.", "Train or evaluate only on Standard German and assume the resulting error and translation behavior represent all German speakers.", "Create a multi-dialect benchmark with dialectal and Standard German transcriptions, then compare multilingual ASR systems on recognition and dialect-to-standard speech translation.", "The dataset crosses three Southeast German dialect groups and Standard German; paired transcription conventions make both recognition fidelity and normalization visible.", "Dialect identity is a structured source of variation, not merely noise: evaluation can distinguish preserving dialect words from mapping them to a standardized target.", "Betthupferl provides four hours of dialect speech plus Standard German and reports model-dependent differences in recognition and translation behavior across dialect groups.", "Read speech, regional coverage, speaker sampling, benchmark size, and translation direction constrain the conclusions; dataset inclusion does not guarantee broad fairness or dialect preservation in deployed systems."),
"gutscher25_interspeech": ("languages-accents-and-resources", "accent-and-cultural-boundaries", "dialect-and-variety", "An acoustic model should identify regional dialect variation without simply memorizing the speaker identity or location-specific recording conditions.", "Dialect and speaker cues are entangled, locations are unevenly sampled, and geographic regression requires a continuous notion of error rather than a single class label.", "Train a classifier on pooled speech and interpret speaker memorization as dialect recognition, or predict only coarse dialect groups.", "Use speaker augmentation to reduce speaker-specific bias and jointly examine dialect/location classification with geographic-coordinate regression.", "The model learns speech representations for hierarchical classification and a continuous coordinate prediction; held-out speaker and location splits test whether regional structure survives identity variation.", "Classification partitions a geographic continuum while regression measures distance in kilometers, so the two tasks expose different resolutions and failure modes of dialect modeling.", "The Austrian dataset covers 304 speakers at 108 locations; wav2vec 2.0 reports an average geographic test error of 66.7 km in the paper's evaluation.", "Sampling density, speaker augmentation, Austrian dialect geography, split design, and recording conditions limit transfer; geographic prediction is not a complete sociolinguistic account of dialect."),
"jung25b_interspeech": ("recognition-and-alignment", "adaptation-and-open-vocabulary", "open-vocabulary-recognition", "Text-enrolled keyword spotting should recognize a word not seen as a fixed acoustic class by aligning an utterance with its text description.", "Audio and text embeddings have different modality statistics; a shared space can match superficial modality cues instead of phonetic or lexical content.", "Compare audio and text embeddings directly with ordinary metric learning and assume the modality gap disappears with more data.", "Adversarially train a modality classifier so audio and text encoders produce modality-invariant embeddings, then optimize deep metric alignment for open-vocabulary KWS.", "The encoders map acoustic queries and text enrollments into a shared space; the adversarial classifier penalizes recoverable modality identity while the metric objective pulls matched keyword pairs together.", "The shared embedding is a constrained retrieval geometry: matched audio/text pairs should be close, while modality identity should be uninformative to the adversary.", "Modality-invariant alignment improves the audio-text retrieval decision used for unseen-keyword spotting in the reported experiments.", "Vocabulary, languages, negative sampling, enrollment text, threshold calibration, and speaker/channel variation bound the claim; open-vocabulary benchmark accuracy is not unrestricted lexical understanding."),
"hu25e_interspeech": ("recognition-and-alignment", "boundaries-and-sequence-structure", "alignment", "Speech recognition and translation systems need word boundaries and timestamps for retrieval, subtitles, and downstream editing without a separate forced-aligner at inference time.", "Timestamp prediction must preserve word order while generating content, and errors in one boundary can shift every later timestamp.", "Attach an external aligner after decoding or force the sequence model to emit timestamps without a training signal for their timing semantics.", "Use a forced aligner as a teacher to create timestamp supervision, add a timestamp token, and train the end-to-end Canary model to emit start and end times with words.", "Teacher-generated word intervals become sequence targets; the model's timestamp tokens interleave with recognized or translated content, allowing boundary prediction inside the decoder.", "Alignment quality is measured against teacher or reference timing and downstream recognition/translation behavior, testing whether an integrated decoder can replace a separate alignment stage.", "The paper reports word-level timestamp generation for Canary with the proposed token and teacher-supervised training in the evaluated ASR/translation settings.", "Teacher timing quality, tokenization, language, speaking rate, and evaluation alignment constrain transfer; timestamp agreement does not by itself prove subtitle readability or translation quality."),
}

notes = []; claims = []
md = ["# INTERSPEECH 2025 fifty-first-pass full-paper notes", "", "Eight official-PDF readings deepen spatial listening, TTS/content, accent/cultural boundaries, open-vocabulary recognition, and alignment.", ""]
for i, (paper_id, fields) in enumerate(N.items(), 1):
    theme, subtheme, concept, bp, wh, naive, ap, mech, math, ww, limits = fields
    p = papers[paper_id]; c = captured[paper_id]
    note = {"paper_id": paper_id, "title": p["title"], "theme_id": theme, "subtheme_id": subtheme, "concept_id": concept, "bp": bp, "wh": wh, "naive": naive, "ap": ap, "mech": mech, "math": math, "eval": math, "ww": ww, "limits": limits, "dots": {"theme_id": theme, "subtheme_id": subtheme, "concept_id": concept, "sibling_family": "batch-051"}, "source": {"kind": "official-isca-archive-paper-page-plus-captured-pdf-text", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "pdf_path": f"data/interspeech-2025-pdfs/{paper_id}.pdf", "text_path": c["full_text_path"]}, "depth": "D3", "evidence_boundary": "D3 structured analyst note backed by captured PDF/text; result remains author-reported and was not independently reproduced."}
    notes.append(note)
    claims.append({"claim_id": f"IS25-D3C51-{i:02d}", "paper_id": paper_id, "subtheme": subtheme, "claim": ww, "evidence_depth": "D3", "pdf_sha256": c["pdf_sha256"], "full_text_sha256": c["full_text_sha256"], "support_status": "paper-reported-not-independently-verified", "independent_support_status": "not-established", "limitations": limits})
    md += [f"## {i}. {subtheme}", "", f"**Paper:** [{p['title']}]({p['paper_url']})", f"**Evidence:** D3; PDF SHA-256 `{c['pdf_sha256']}`; full text captured.", ""]
    md += [f"- **{label}:** {note[key]}" for label, key in zip(["Ordinary problem", "Why hard", "Naive attempt", "Central move", "Mechanism", "Mathematical/conceptual structure", "What paper reports", "Limits"], ["bp", "wh", "naive", "ap", "mech", "math", "ww", "limits"])] + [""]
(DATA / "interspeech-2025-fiftyfirst-d3-notes.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "evidence_depth": "D3", "notes": notes}, indent=2, ensure_ascii=False) + "\n")
(DATA / "interspeech-2025-fiftyfirst-claim-ledger.json").write_text(json.dumps({"venue": "INTERSPEECH 2025", "claim_count": len(claims), "claims": claims}, indent=2, ensure_ascii=False) + "\n")
REPORTS.mkdir(exist_ok=True); (REPORTS / "INTERSPEECH_2025_FIFTYFIRST_D3_NOTES.md").write_text("\n".join(md) + "\n")
print(json.dumps({"notes": len(notes), "claims": len(claims)}))
